/* ============================================================
   🔬  SCIENCE — Class 3
   ------------------------------------------------------------
   HOW TO EDIT THIS FILE
   • Each { ... } line below is ONE question.
   • Keep this exact shape:
       { question: "your question?", answer: "Correct", options: ["Correct","B","C","D"] }
   • RULES:
       - Give exactly 4 options.
       - The "answer" text must EXACTLY match one of the 4 options.
       - Wrap text in "double quotes". If your text has a " inside it,
         write it as \" (a backslash then a quote).
   • Add or delete question lines freely.
   • Save the file, then refresh the quiz page — changes appear instantly.
   ============================================================ */
registerQuiz("science", 3, [
  { question: "Boiling point of water?", answer: "100°C", options: ["100°C", "90°C", "110°C", "120°C"] },
  { question: "Freezing point of water?", answer: "0°C", options: ["0°C", "-10°C", "10°C", "5°C"] },
  { question: "Force pulling things to Earth?", answer: "Gravity", options: ["Gravity", "Magnetism", "Friction", "Pressure"] },
  { question: "Process of plant making food?", answer: "Photosynthesis", options: ["Photosynthesis", "Respiration", "Digestion", "Excretion"] },
  { question: "Animal that eats only plants?", answer: "Herbivore", options: ["Herbivore", "Carnivore", "Omnivore", "Insectivore"] },
  { question: "Animal that eats only meat?", answer: "Carnivore", options: ["Carnivore", "Herbivore", "Omnivore", "Insectivore"] },
  { question: "Animal that eats both?", answer: "Omnivore", options: ["Omnivore", "Herbivore", "Carnivore", "Insectivore"] },
  { question: "Which gas do plants take in?", answer: "Carbon dioxide", options: ["Carbon dioxide", "Oxygen", "Nitrogen", "Hydrogen"] },
  { question: "Which gas do plants give out?", answer: "Oxygen", options: ["Oxygen", "Carbon dioxide", "Nitrogen", "Helium"] },
  { question: "Source of energy for Earth?", answer: "Sun", options: ["Sun", "Moon", "Stars", "Wind"] },
  { question: "Which animal is amphibian?", answer: "Frog", options: ["Frog", "Snake", "Lizard", "Turtle"] },
  { question: "Which animal is reptile?", answer: "Snake", options: ["Snake", "Frog", "Fish", "Bird"] },
  { question: "Backbone animal is called?", answer: "Vertebrate", options: ["Vertebrate", "Invertebrate", "Mammal", "Insect"] },
  { question: "Animal without backbone?", answer: "Invertebrate", options: ["Invertebrate", "Vertebrate", "Mammal", "Reptile"] },
  { question: "Which is non-living?", answer: "Stone", options: ["Stone", "Plant", "Animal", "Bird"] },
  { question: "Which is living?", answer: "Tree", options: ["Tree", "Stone", "Iron", "Brick"] },
  { question: "Magnet has ___ poles.", answer: "Two", options: ["Two", "One", "Three", "Four"] },
  { question: "Like poles of magnet?", answer: "Repel", options: ["Repel", "Attract", "Stick", "Stop"] },
  { question: "Unlike poles of magnet?", answer: "Attract", options: ["Attract", "Repel", "Stop", "Break"] },
  { question: "Sun is a?", answer: "Star", options: ["Star", "Planet", "Moon", "Comet"] },
  { question: "What do we call the study of living things?", answer: "Biology", options: ["Biology", "Physics", "Chemistry", "Geology"] },
  { question: "What is the basic unit of life called?", answer: "Cell", options: ["Cell", "Tissue", "Organ", "Molecule"] },
  { question: "Who discovered the cell?", answer: "Robert Hooke", options: ["Robert Hooke", "Charles Darwin", "Gregor Mendel", "Louis Pasteur"] },
  { question: "What is the green pigment in plants called?", answer: "Chlorophyll", options: ["Chlorophyll", "Hemoglobin", "Melanin", "Carotene"] },
  { question: "What is the red pigment in our blood called?", answer: "Hemoglobin", options: ["Hemoglobin", "Chlorophyll", "Melanin", "Carotene"] },
  { question: "What process do plants use to make their own food?", answer: "Photosynthesis", options: ["Photosynthesis", "Respiration", "Digestion", "Excretion"] },
  { question: "What do plants need for photosynthesis?", answer: "Sunlight, water and carbon dioxide", options: ["Sunlight, water and carbon dioxide", "Only water", "Only sunlight", "Only soil"] },
  { question: "What gas is released during photosynthesis?", answer: "Oxygen", options: ["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"] },
  { question: "What is the process by which living things get energy from food using oxygen?", answer: "Respiration", options: ["Respiration", "Photosynthesis", "Digestion", "Excretion"] },
  { question: "What is the process of removing waste from the body called?", answer: "Excretion", options: ["Excretion", "Digestion", "Respiration", "Circulation"] },
  { question: "What is the process of breaking down food into nutrients called?", answer: "Digestion", options: ["Digestion", "Respiration", "Excretion", "Circulation"] },
  { question: "What is the movement of blood throughout the body called?", answer: "Circulation", options: ["Circulation", "Digestion", "Respiration", "Excretion"] },
  { question: "What are animals without a backbone called?", answer: "Invertebrates", options: ["Invertebrates", "Vertebrates", "Mammals", "Reptiles"] },
  { question: "What are animals with a backbone called?", answer: "Vertebrates", options: ["Vertebrates", "Invertebrates", "Insects", "Arachnids"] },
  { question: "How many legs does an insect have?", answer: "6", options: ["6", "4", "8", "10"] },
  { question: "How many legs does a spider have?", answer: "8", options: ["8", "6", "4", "10"] },
  { question: "Is a spider an insect?", answer: "No, it is an arachnid", options: ["No, it is an arachnid", "Yes, it is an insect", "It is a reptile", "It is a mammal"] },
  { question: "What are the three body parts of an insect?", answer: "Head, thorax, abdomen", options: ["Head, thorax, abdomen", "Head, body, tail", "Head, neck, body", "Head, chest, legs"] },
  { question: "What do we call animals that change form completely as they grow, like butterflies?", answer: "Complete metamorphosis", options: ["Complete metamorphosis", "Incomplete metamorphosis", "No metamorphosis", "Partial growth"] },
  { question: "What are the four stages of a butterfly's life cycle?", answer: "Egg, larva, pupa, adult", options: ["Egg, larva, pupa, adult", "Egg, adult, larva, pupa", "Larva, egg, adult, pupa", "Egg, pupa, larva, adult"] },
  { question: "What do we call the resting stage of a butterfly before it becomes an adult?", answer: "Pupa (chrysalis)", options: ["Pupa (chrysalis)", "Larva", "Nymph", "Egg"] },
  { question: "What is the caterpillar stage of a butterfly called?", answer: "Larva", options: ["Larva", "Pupa", "Nymph", "Egg"] },
  { question: "What natural force keeps planets orbiting the Sun?", answer: "Gravity", options: ["Gravity", "Magnetism", "Friction", "Wind"] },
  { question: "What force pulls objects toward the center of the Earth?", answer: "Gravity", options: ["Gravity", "Friction", "Magnetism", "Air pressure"] },
  { question: "What do we call the resistance between two surfaces touching each other?", answer: "Friction", options: ["Friction", "Gravity", "Magnetism", "Tension"] },
  { question: "How does friction help us walk?", answer: "It stops our feet from slipping", options: ["It stops our feet from slipping", "It pulls us to the ground", "It makes us lighter", "It speeds us up"] },
  { question: "What are the three states of matter?", answer: "Solid, liquid, gas", options: ["Solid, liquid, gas", "Hot, warm, cold", "Big, small, medium", "Fast, slow, still"] },
  { question: "What happens to the particles in a solid compared to a liquid?", answer: "They are more tightly packed", options: ["They are more tightly packed", "They move freely", "They spread apart", "They disappear"] },
  { question: "What is it called when a solid changes directly into a gas without becoming liquid?", answer: "Sublimation", options: ["Sublimation", "Evaporation", "Condensation", "Melting"] },
  { question: "What is a common example of sublimation?", answer: "Dry ice (solid CO2)", options: ["Dry ice (solid CO2)", "Ice melting", "Water boiling", "Rain forming"] },
  { question: "What do we call a substance that cannot be broken down into simpler substances?", answer: "Element", options: ["Element", "Compound", "Mixture", "Solution"] },
  { question: "What do we call a substance made of two or more elements chemically combined?", answer: "Compound", options: ["Compound", "Element", "Mixture", "Alloy"] },
  { question: "What do we call a combination of substances that are not chemically joined?", answer: "Mixture", options: ["Mixture", "Compound", "Element", "Molecule"] },
  { question: "What is the smallest particle of an element called?", answer: "Atom", options: ["Atom", "Molecule", "Cell", "Compound"] },
  { question: "What do we call two or more atoms joined together?", answer: "Molecule", options: ["Molecule", "Atom", "Cell", "Element"] },
  { question: "What do we call a magnet's invisible area of influence?", answer: "Magnetic field", options: ["Magnetic field", "Gravity field", "Electric field", "Force field"] },
  { question: "What are the two poles of a magnet called?", answer: "North pole and South pole", options: ["North pole and South pole", "East pole and West pole", "Top pole and bottom pole", "Positive pole and negative pole"] },
  { question: "What natural material is strongly attracted by magnets?", answer: "Iron", options: ["Iron", "Wood", "Plastic", "Glass"] },
  { question: "What do we call a temporary magnet made using electricity?", answer: "Electromagnet", options: ["Electromagnet", "Permanent magnet", "Bar magnet", "Compass"] },
  { question: "What device uses a magnet to show direction?", answer: "Compass", options: ["Compass", "Thermometer", "Barometer", "Clock"] },
  { question: "What do we call energy stored in an object due to its position?", answer: "Potential energy", options: ["Potential energy", "Kinetic energy", "Chemical energy", "Heat energy"] },
  { question: "What do we call the energy of motion?", answer: "Kinetic energy", options: ["Kinetic energy", "Potential energy", "Chemical energy", "Light energy"] },
  { question: "What kind of energy is stored in food?", answer: "Chemical energy", options: ["Chemical energy", "Kinetic energy", "Light energy", "Sound energy"] },
  { question: "What is the law that says energy cannot be created or destroyed, only changed?", answer: "Law of conservation of energy", options: ["Law of conservation of energy", "Law of gravity", "Law of motion", "Law of friction"] },
  { question: "What do we call renewable sources of energy?", answer: "Sources that don't run out, like solar and wind", options: ["Sources that don't run out, like solar and wind", "Sources that run out, like coal", "Only electricity", "Only fuel"] },
  { question: "Which of these is a renewable energy source?", answer: "Solar energy", options: ["Solar energy", "Coal", "Petroleum", "Natural gas"] },
  { question: "Which of these is a non-renewable energy source?", answer: "Coal", options: ["Coal", "Solar energy", "Wind energy", "Water energy"] },
  { question: "What do we call fuels formed from dead plants and animals over millions of years?", answer: "Fossil fuels", options: ["Fossil fuels", "Renewable fuels", "Nuclear fuels", "Bio fuels"] },
  { question: "Name a fossil fuel.", answer: "Coal", options: ["Coal", "Solar power", "Wind power", "Water power"] },
  { question: "What do we call energy generated from moving water?", answer: "Hydropower", options: ["Hydropower", "Solar power", "Wind power", "Nuclear power"] },
  { question: "What do we call energy generated from the wind?", answer: "Wind power", options: ["Wind power", "Solar power", "Hydropower", "Nuclear power"] },
  { question: "What do we call the layer of gases surrounding the Earth?", answer: "Atmosphere", options: ["Atmosphere", "Biosphere", "Hydrosphere", "Lithosphere"] },
  { question: "What do we call all the water bodies on Earth together?", answer: "Hydrosphere", options: ["Hydrosphere", "Atmosphere", "Biosphere", "Lithosphere"] },
  { question: "What do we call the solid part of the Earth?", answer: "Lithosphere", options: ["Lithosphere", "Atmosphere", "Hydrosphere", "Biosphere"] },
  { question: "What do we call all living things on Earth together?", answer: "Biosphere", options: ["Biosphere", "Atmosphere", "Hydrosphere", "Lithosphere"] },
  { question: "What do we call animals that only eat plants?", answer: "Herbivores", options: ["Herbivores", "Carnivores", "Omnivores", "Insectivores"] },
  { question: "What do we call animals that eat only insects?", answer: "Insectivores", options: ["Insectivores", "Herbivores", "Carnivores", "Omnivores"] },
  { question: "What is a chain showing who eats whom in nature called?", answer: "Food chain", options: ["Food chain", "Food web", "Life cycle", "Energy chain"] },
  { question: "What is a network of many connected food chains called?", answer: "Food web", options: ["Food web", "Food chain", "Life cycle", "Energy web"] },
  { question: "What are plants called in a food chain since they make their own food?", answer: "Producers", options: ["Producers", "Consumers", "Decomposers", "Predators"] },
  { question: "What are animals called in a food chain since they eat other organisms?", answer: "Consumers", options: ["Consumers", "Producers", "Decomposers", "Predators"] },
  { question: "What organisms break down dead plants and animals?", answer: "Decomposers", options: ["Decomposers", "Producers", "Consumers", "Predators"] },
  { question: "Name an example of a decomposer.", answer: "Fungi (mushrooms)", options: ["Fungi (mushrooms)", "Grass", "Deer", "Lion"] },
  { question: "What do we call a group of the same type of living organism in an area?", answer: "Population", options: ["Population", "Community", "Ecosystem", "Habitat"] },
  { question: "What do we call all living and non-living things in an area interacting together?", answer: "Ecosystem", options: ["Ecosystem", "Population", "Community", "Habitat"] },
  { question: "What do we call the natural home of a plant or animal?", answer: "Habitat", options: ["Habitat", "Ecosystem", "Population", "Community"] },
  { question: "What do we call animals moving from one place to another with seasons?", answer: "Migration", options: ["Migration", "Hibernation", "Camouflage", "Adaptation"] },
  { question: "What do we call animals sleeping through winter to save energy?", answer: "Hibernation", options: ["Hibernation", "Migration", "Camouflage", "Adaptation"] },
  { question: "What do we call an animal's ability to blend into its surroundings?", answer: "Camouflage", options: ["Camouflage", "Migration", "Hibernation", "Mimicry"] },
  { question: "What do we call special features that help living things survive in their environment?", answer: "Adaptations", options: ["Adaptations", "Migrations", "Habitats", "Ecosystems"] },
  { question: "Why do camels have humps?", answer: "To store fat for energy and water", options: ["To store fat for energy and water", "To look tall", "To carry loads only", "To stay cool"] },
  { question: "Why do polar bears have thick white fur?", answer: "To stay warm and blend into snow", options: ["To stay warm and blend into snow", "To look beautiful", "To swim faster", "To scare prey only"] },
  { question: "Why do fish have gills?", answer: "To breathe underwater", options: ["To breathe underwater", "To swim faster", "To see better", "To eat food"] },
  { question: "Why do birds have hollow bones?", answer: "To make them lighter for flying", options: ["To make them lighter for flying", "To make them stronger", "To store food", "To keep warm"] },
  { question: "What do we call a substance that speeds up a chemical reaction without being used up?", answer: "Catalyst", options: ["Catalyst", "Reactant", "Product", "Solvent"] },
  { question: "What is the chemical process of iron combining with oxygen and water called?", answer: "Rusting", options: ["Rusting", "Melting", "Evaporation", "Sublimation"] },
  { question: "What can we do to prevent iron from rusting?", answer: "Paint or oil it", options: ["Paint or oil it", "Wet it", "Heat it", "Freeze it"] },

  { question: "What do we call water that has minerals and salts dissolved in it, unfit to drink easily?", answer: "Hard water", options: ["Hard water", "Soft water", "Distilled water", "Rain water"] },
  { question: "What do we call water without dissolved minerals, good for washing?", answer: "Soft water", options: ["Soft water", "Hard water", "Salt water", "Sea water"] },
  { question: "What natural disaster happens when the ground shakes suddenly?", answer: "Earthquake", options: ["Earthquake", "Flood", "Drought", "Cyclone"] },






]);
