/* ============================================================
   🔬  SCIENCE — Class 5
   ------------------------------------------------------------
   HOW TO EDIT THIS FILE
   • Each { ... } line below is ONE question.
   • Keep this exact shape:
       { question: "your question?", answer: "Correct", options: ["Correct","B","C","D"] }
   • RULES:
       - Give exactly 4 options.
       - The "answer" text must EXACTLY match one of the 4 options.
       - Wrap text in "double quotes". If your text has a " inside it,
         write it as \" (a backslash then a quote).
   • Add or delete question lines freely.
   • Save the file, then refresh the quiz page — changes appear instantly.
   ============================================================ */
registerQuiz("science", 5, [
  { question: "Speed of light is approx?", answer: "3×10⁸ m/s", options: ["3×10⁸ m/s", "3×10⁶ m/s", "3×10⁵ m/s", "3×10⁷ m/s"] },
  { question: "Earth's age (approx)?", answer: "4.5 billion years", options: ["4.5 billion years", "1 billion", "100 million", "10 billion"] },
  { question: "Closest star to Earth?", answer: "Sun", options: ["Sun", "Proxima Centauri", "Sirius", "Polaris"] },
  { question: "Hardest natural substance?", answer: "Diamond", options: ["Diamond", "Iron", "Gold", "Quartz"] },
  { question: "Lightest gas?", answer: "Hydrogen", options: ["Hydrogen", "Helium", "Oxygen", "Nitrogen"] },
  { question: "Most abundant gas in air?", answer: "Nitrogen", options: ["Nitrogen", "Oxygen", "CO2", "Argon"] },
  { question: "Symbol of Iron?", answer: "Fe", options: ["Fe", "Ir", "I", "In"] },
  { question: "Symbol of Sodium?", answer: "Na", options: ["Na", "So", "S", "Sd"] },
  { question: "Symbol of Potassium?", answer: "K", options: ["K", "P", "Po", "Pt"] },
  { question: "pH of pure water?", answer: "7", options: ["7", "6", "8", "0"] },
  { question: "pH less than 7 is?", answer: "Acidic", options: ["Acidic", "Basic", "Neutral", "Alkaline"] },
  { question: "pH greater than 7 is?", answer: "Basic", options: ["Basic", "Acidic", "Neutral", "Salt"] },
  { question: "Branch of science about living things?", answer: "Biology", options: ["Biology", "Physics", "Chemistry", "Geology"] },
  { question: "Branch of science about matter?", answer: "Chemistry", options: ["Chemistry", "Biology", "Physics", "Astronomy"] },
  { question: "Branch of science about forces?", answer: "Physics", options: ["Physics", "Biology", "Chemistry", "Botany"] },
  { question: "Three Rs of environment?", answer: "Reduce, Reuse, Recycle", options: ["Reduce, Reuse, Recycle", "Run, Read, Rest", "Right, Real, Ready", "Rich, Rare, Rough"] },
  { question: "Ozone layer protects from?", answer: "UV rays", options: ["UV rays", "Wind", "Rain", "Heat"] },
  { question: "Which is not a fossil fuel?", answer: "Wood", options: ["Wood", "Coal", "Petroleum", "Natural gas"] },
  { question: "Bee colony lives in?", answer: "Hive", options: ["Hive", "Nest", "Web", "Burrow"] },
  { question: "Spider makes a?", answer: "Web", options: ["Web", "Hive", "Nest", "Burrow"] },
  { question: "What is Newton's First Law of Motion also known as?", answer: "Law of Inertia", options: ["Law of Inertia", "Law of Action-Reaction", "Law of Gravitation", "Law of Momentum"] },
  { question: "What does Newton's Third Law state?", answer: "For every action, there is an equal and opposite reaction", options: ["For every action, there is an equal and opposite reaction", "Objects at rest stay at rest", "Force equals mass times acceleration", "Energy cannot be destroyed"] },
  { question: "What is the formula relating force, mass and acceleration?", answer: "F = ma", options: ["F = ma", "E = mc²", "F = mv", "P = Fv"] },
  { question: "What does 'mass' measure in physics?", answer: "Amount of matter in an object", options: ["Amount of matter in an object", "Weight due to gravity", "Volume of an object", "Speed of an object"] },
  { question: "What does 'weight' measure in physics?", answer: "Force of gravity on an object", options: ["Force of gravity on an object", "Amount of matter", "Volume", "Speed"] },
  { question: "Why does an astronaut weigh less on the Moon than on Earth?", answer: "Moon's gravity is weaker", options: ["Moon's gravity is weaker", "Moon has no air", "Moon is smaller in size only", "Moon is colder"] },
  { question: "What is the universal law of gravitation attributed to?", answer: "Isaac Newton", options: ["Isaac Newton", "Albert Einstein", "Galileo Galilei", "Johannes Kepler"] },
  { question: "Who first showed that all objects fall at the same rate regardless of mass (ignoring air resistance)?", answer: "Galileo Galilei", options: ["Galileo Galilei", "Isaac Newton", "Albert Einstein", "Johannes Kepler"] },
  { question: "What is the escape velocity needed to leave Earth's gravity roughly?", answer: "11.2 km/s", options: ["11.2 km/s", "1 km/s", "100 km/s", "343 m/s"] },
  { question: "What is the speed of sound in air approximately?", answer: "343 m/s", options: ["343 m/s", "3×10⁸ m/s", "11.2 km/s", "9.8 m/s"] },
  { question: "What is the speed of light approximately?", answer: "3×10⁸ m/s", options: ["3×10⁸ m/s", "343 m/s", "11.2 km/s", "9.8 m/s"] },
  { question: "What is the acceleration due to gravity on Earth approximately?", answer: "9.8 m/s²", options: ["9.8 m/s²", "3×10⁸ m/s", "343 m/s", "11.2 km/s"] },
  { question: "What are the periodic table's rows called?", answer: "Periods", options: ["Periods", "Groups", "Families", "Blocks"] },
  { question: "What are the periodic table's columns called?", answer: "Groups", options: ["Groups", "Periods", "Rows", "Blocks"] },
  { question: "Who arranged elements into the modern periodic table?", answer: "Dmitri Mendeleev", options: ["Dmitri Mendeleev", "Antoine Lavoisier", "John Dalton", "Marie Curie"] },
  { question: "What are elements in the same group of the periodic table known to share?", answer: "Similar chemical properties", options: ["Similar chemical properties", "Same atomic number", "Same color", "Same state"] },
  { question: "What is the most abundant element in the universe?", answer: "Hydrogen", options: ["Hydrogen", "Helium", "Oxygen", "Carbon"] },
  { question: "What is the most abundant metal in the Earth's crust?", answer: "Aluminium", options: ["Aluminium", "Iron", "Copper", "Gold"] },
  { question: "What is the most abundant gas in Earth's atmosphere?", answer: "Nitrogen", options: ["Nitrogen", "Oxygen", "Carbon dioxide", "Hydrogen"] },
  { question: "What noble gas is used in balloons because it's lighter than air?", answer: "Helium", options: ["Helium", "Neon", "Argon", "Xenon"] },
  { question: "What gas is essential for combustion (burning)?", answer: "Oxygen", options: ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"] },
  { question: "What do we call substances that speed up chemical reactions?", answer: "Catalysts", options: ["Catalysts", "Reactants", "Products", "Solvents"] },
  { question: "What do we call the substances we start with in a chemical reaction?", answer: "Reactants", options: ["Reactants", "Products", "Catalysts", "Solutions"] },
  { question: "What do we call the substances formed at the end of a chemical reaction?", answer: "Products", options: ["Products", "Reactants", "Catalysts", "Solutions"] },
  { question: "What law states mass is neither created nor destroyed in a chemical reaction?", answer: "Law of conservation of mass", options: ["Law of conservation of mass", "Law of gravity", "Newton's law", "Law of energy"] },
  { question: "Who proposed the law of conservation of mass?", answer: "Antoine Lavoisier", options: ["Antoine Lavoisier", "Dmitri Mendeleev", "John Dalton", "Marie Curie"] },
  { question: "What do we call a solution with more solute than can normally dissolve?", answer: "Supersaturated solution", options: ["Supersaturated solution", "Dilute solution", "Unsaturated solution", "Saturated solution"] },
  { question: "What do we call a substance that dissolves in a solvent?", answer: "Solute", options: ["Solute", "Solvent", "Solution", "Suspension"] },
  { question: "What do we call the liquid in which a solute dissolves?", answer: "Solvent", options: ["Solvent", "Solute", "Solution", "Suspension"] },
  { question: "What do we call a mixture where particles are visible and settle over time?", answer: "Suspension", options: ["Suspension", "Solution", "Colloid", "Compound"] },
  { question: "What do we call a mixture where particles are spread but don't settle, like milk?", answer: "Colloid", options: ["Colloid", "Solution", "Suspension", "Compound"] },
  { question: "What is the process of separating a solid from a liquid using a fine mesh called?", answer: "Filtration", options: ["Filtration", "Distillation", "Evaporation", "Sublimation"] },
  { question: "What is the process of separating a liquid mixture by boiling and condensing called?", answer: "Distillation", options: ["Distillation", "Filtration", "Evaporation", "Sedimentation"] },
  { question: "What is the process of separating dissolved salt from water called?", answer: "Evaporation", options: ["Evaporation", "Filtration", "Distillation", "Decantation"] },
  { question: "What is the DNA molecule shaped like?", answer: "Double helix", options: ["Double helix", "Single strand", "Triangle", "Circle only"] },
  { question: "Who discovered the structure of DNA?", answer: "James Watson and Francis Crick", options: ["James Watson and Francis Crick", "Gregor Mendel", "Charles Darwin", "Louis Pasteur"] },
  { question: "What do we call the basic unit of heredity?", answer: "Gene", options: ["Gene", "Cell", "Chromosome", "Protein"] },
  { question: "What do we call the thread-like structures in cells that carry genes?", answer: "Chromosomes", options: ["Chromosomes", "Genes", "Nucleus", "Ribosomes"] },
  { question: "How many chromosomes do humans have?", answer: "46", options: ["46", "23", "48", "44"] },
  { question: "What blood type is known as the universal donor?", answer: "O negative", options: ["O negative", "AB positive", "A positive", "B negative"] },
  { question: "What blood type is known as the universal recipient?", answer: "AB positive", options: ["AB positive", "O negative", "A positive", "B negative"] },
  { question: "What is the process by which the heart pumps blood through the body called?", answer: "Circulation", options: ["Circulation", "Digestion", "Respiration", "Excretion"] },
  { question: "What are the upper chambers of the heart called?", answer: "Atria", options: ["Atria", "Ventricles", "Valves", "Arteries"] },
  { question: "What are the lower chambers of the heart called?", answer: "Ventricles", options: ["Ventricles", "Atria", "Valves", "Veins"] },
  { question: "What blood vessels carry blood away from the heart?", answer: "Arteries", options: ["Arteries", "Veins", "Capillaries", "Ventricles"] },
  { question: "What blood vessels carry blood back to the heart?", answer: "Veins", options: ["Veins", "Arteries", "Capillaries", "Atria"] },
  { question: "What are the tiniest blood vessels where exchange of gases happens?", answer: "Capillaries", options: ["Capillaries", "Arteries", "Veins", "Ventricles"] },
  { question: "What is the process plants use to lose excess water called?", answer: "Transpiration", options: ["Transpiration", "Respiration", "Photosynthesis", "Excretion"] },
  { question: "What do we call plants that live in very dry conditions?", answer: "Xerophytes", options: ["Xerophytes", "Hydrophytes", "Mesophytes", "Halophytes"] },
  { question: "What do we call plants that live in water?", answer: "Hydrophytes", options: ["Hydrophytes", "Xerophytes", "Mesophytes", "Halophytes"] },
  { question: "What is the ecological term for the role an organism plays in its habitat?", answer: "Niche", options: ["Niche", "Habitat", "Population", "Community"] },
  { question: "What is the term for organisms competing for the same resources?", answer: "Competition", options: ["Competition", "Cooperation", "Symbiosis", "Predation"] },
  { question: "What do we call a relationship where both organisms benefit?", answer: "Mutualism (symbiosis)", options: ["Mutualism (symbiosis)", "Parasitism", "Competition", "Predation"] },
  { question: "What do we call a relationship where one organism benefits and harms the other?", answer: "Parasitism", options: ["Parasitism", "Mutualism", "Commensalism", "Competition"] },
  { question: "What do we call a relationship where one benefits and the other is unaffected?", answer: "Commensalism", options: ["Commensalism", "Mutualism", "Parasitism", "Competition"] },
  { question: "What do we call the total variety of life on Earth?", answer: "Biodiversity", options: ["Biodiversity", "Ecosystem", "Habitat", "Population"] },
  { question: "What do we call areas set aside to protect wildlife?", answer: "Wildlife sanctuaries / National parks", options: ["Wildlife sanctuaries / National parks", "Zoos", "Farms", "Gardens"] },
  { question: "What is India's first national park, established to protect tigers?", answer: "Jim Corbett National Park", options: ["Jim Corbett National Park", "Kaziranga National Park", "Gir National Park", "Sundarbans National Park"] },
  { question: "Which national park in India is famous for one-horned rhinoceroses?", answer: "Kaziranga National Park", options: ["Kaziranga National Park", "Jim Corbett National Park", "Gir National Park", "Ranthambore National Park"] },
  { question: "Which national park in India is the only home of the Asiatic lion?", answer: "Gir National Park", options: ["Gir National Park", "Jim Corbett National Park", "Kaziranga National Park", "Bandhavgarh National Park"] },
  { question: "What is the name of the project launched in India in 1973 to protect tigers?", answer: "Project Tiger", options: ["Project Tiger", "Project Elephant", "Project Lion", "Project Rhino"] },
  { question: "What do we call the phenomenon of the Sun and Moon aligning to cause an eclipse?", answer: "Syzygy", options: ["Syzygy", "Equinox", "Solstice", "Orbit"] },
  { question: "What is it called when the Moon comes between the Sun and Earth?", answer: "Solar eclipse", options: ["Solar eclipse", "Lunar eclipse", "Equinox", "Solstice"] },
  { question: "What is it called when the Earth comes between the Sun and Moon?", answer: "Lunar eclipse", options: ["Lunar eclipse", "Solar eclipse", "Equinox", "Solstice"] },
  { question: "What do we call the day when day and night are of equal length?", answer: "Equinox", options: ["Equinox", "Solstice", "Eclipse", "Syzygy"] },
  { question: "What do we call the day with the longest daylight in a year?", answer: "Summer solstice", options: ["Summer solstice", "Winter solstice", "Equinox", "Eclipse"] },
  { question: "What do we call the day with the shortest daylight in a year?", answer: "Winter solstice", options: ["Winter solstice", "Summer solstice", "Equinox", "Eclipse"] },
  { question: "What natural phenomenon is caused by charged particles from the sun hitting Earth's atmosphere near the poles?", answer: "Aurora (Northern/Southern Lights)", options: ["Aurora (Northern/Southern Lights)", "Rainbow", "Eclipse", "Halo"] },
  { question: "What do we call the study of the origin, structure and future of the universe?", answer: "Cosmology", options: ["Cosmology", "Astronomy", "Astrology", "Geology"] },
  { question: "What do we call a huge collection of stars, gas and dust like our Milky Way?", answer: "Galaxy", options: ["Galaxy", "Solar system", "Constellation", "Nebula"] },
  { question: "What do we call a giant cloud of gas and dust in space where stars are born?", answer: "Nebula", options: ["Nebula", "Galaxy", "Constellation", "Asteroid belt"] },
  { question: "What do we call small rocky objects orbiting the sun, mostly between Mars and Jupiter?", answer: "Asteroids", options: ["Asteroids", "Comets", "Meteors", "Planets"] },
  { question: "What do we call icy objects that develop a glowing tail near the sun?", answer: "Comets", options: ["Comets", "Asteroids", "Meteors", "Satellites"] },
  { question: "What do we call a meteoroid that burns up in Earth's atmosphere, seen as a shooting star?", answer: "Meteor", options: ["Meteor", "Meteorite", "Asteroid", "Comet"] },
  { question: "What do we call a meteor that survives and lands on Earth's surface?", answer: "Meteorite", options: ["Meteorite", "Meteor", "Asteroid", "Comet"] },
  { question: "What is the collapsed remains of a massive star with extreme gravity called?", answer: "Black hole", options: ["Black hole", "White dwarf", "Neutron star", "Supernova"] },
  { question: "What do we call the explosive death of a massive star?", answer: "Supernova", options: ["Supernova", "Black hole", "Nebula", "White dwarf"] },


  { question: "What do we call the temperature at which a substance changes from solid to liquid?", answer: "Melting point", options: ["Melting point", "Boiling point", "Freezing point", "Condensation point"] },
  { question: "What do we call the temperature at which a liquid changes to gas?", answer: "Boiling point", options: ["Boiling point", "Melting point", "Freezing point", "Condensation point"] },
]);
