/* ============================================================
   🔬  SCIENCE — Class 4
   ------------------------------------------------------------
   HOW TO EDIT THIS FILE
   • Each { ... } line below is ONE question.
   • Keep this exact shape:
       { question: "your question?", answer: "Correct", options: ["Correct","B","C","D"] }
   • RULES:
       - Give exactly 4 options.
       - The "answer" text must EXACTLY match one of the 4 options.
       - Wrap text in "double quotes". If your text has a " inside it,
         write it as \" (a backslash then a quote).
   • Add or delete question lines freely.
   • Save the file, then refresh the quiz page — changes appear instantly.
   ============================================================ */
registerQuiz("science", 4, [
  { question: "How many planets in solar system?", answer: "8", options: ["8", "9", "7", "10"] },
  { question: "Solid water is called?", answer: "Ice", options: ["Ice", "Steam", "Vapor", "Mist"] },
  { question: "Gaseous water is called?", answer: "Steam/Vapor", options: ["Steam/Vapor", "Ice", "Frost", "Snow"] },
  { question: "Process of water becoming vapor?", answer: "Evaporation", options: ["Evaporation", "Condensation", "Freezing", "Melting"] },
  { question: "Process of vapor becoming water?", answer: "Condensation", options: ["Condensation", "Evaporation", "Freezing", "Melting"] },
  { question: "Acid turns blue litmus to?", answer: "Red", options: ["Red", "Blue", "Green", "Yellow"] },
  { question: "Base turns red litmus to?", answer: "Blue", options: ["Blue", "Red", "Green", "Yellow"] },
  { question: "Sound is produced by?", answer: "Vibration", options: ["Vibration", "Heat", "Light", "Pressure"] },
  { question: "Echo is reflected?", answer: "Sound", options: ["Sound", "Light", "Heat", "Air"] },
  { question: "Unit of force?", answer: "Newton", options: ["Newton", "Joule", "Watt", "Volt"] },
  { question: "Unit of electricity (potential)?", answer: "Volt", options: ["Volt", "Watt", "Newton", "Ohm"] },
  { question: "Energy in food?", answer: "Chemical", options: ["Chemical", "Light", "Sound", "Heat"] },
  { question: "Skeleton has ___ bones (adult).", answer: "206", options: ["206", "201", "210", "220"] },
  { question: "Smallest unit of life?", answer: "Cell", options: ["Cell", "Atom", "Tissue", "Organ"] },
  { question: "Brain is in?", answer: "Skull", options: ["Skull", "Chest", "Stomach", "Back"] },
  { question: "Heart is in?", answer: "Chest", options: ["Chest", "Skull", "Stomach", "Leg"] },
  { question: "Kidneys filter?", answer: "Blood", options: ["Blood", "Air", "Food", "Bones"] },
  { question: "Lungs help in?", answer: "Breathing", options: ["Breathing", "Digestion", "Walking", "Seeing"] },
  { question: "Vitamin from sunlight?", answer: "Vitamin D", options: ["Vitamin D", "Vitamin A", "Vitamin C", "Vitamin B"] },
  { question: "Vitamin in citrus fruits?", answer: "Vitamin C", options: ["Vitamin C", "Vitamin A", "Vitamin D", "Vitamin K"] },
  { question: "What is the study of forces and energy called?", answer: "Physics", options: ["Physics", "Chemistry", "Biology", "Geology"] },
  { question: "What is the study of substances and their properties called?", answer: "Chemistry", options: ["Chemistry", "Physics", "Biology", "Geology"] },
  { question: "What are the tiny particles that make up all matter called?", answer: "Atoms", options: ["Atoms", "Cells", "Molecules only", "Ions"] },
  { question: "What is at the center of an atom called?", answer: "Nucleus", options: ["Nucleus", "Electron", "Proton shell", "Orbit"] },
  { question: "What are the negatively charged particles in an atom called?", answer: "Electrons", options: ["Electrons", "Protons", "Neutrons", "Nucleus"] },
  { question: "What are the positively charged particles in an atom called?", answer: "Protons", options: ["Protons", "Electrons", "Neutrons", "Nucleus"] },
  { question: "What are the particles with no charge in an atom's nucleus called?", answer: "Neutrons", options: ["Neutrons", "Protons", "Electrons", "Ions"] },
  { question: "What instrument is used to view very small objects like cells?", answer: "Microscope", options: ["Microscope", "Telescope", "Binoculars", "Periscope"] },
  { question: "What instrument is used to view distant objects like stars?", answer: "Telescope", options: ["Telescope", "Microscope", "Binoculars", "Periscope"] },
  { question: "What is the SI unit of force?", answer: "Newton", options: ["Newton", "Joule", "Watt", "Pascal"] },
  { question: "What is the SI unit of energy?", answer: "Joule", options: ["Joule", "Newton", "Watt", "Pascal"] },
  { question: "What is the SI unit of power?", answer: "Watt", options: ["Watt", "Newton", "Joule", "Pascal"] },
  { question: "What is the SI unit of electric current?", answer: "Ampere", options: ["Ampere", "Volt", "Watt", "Ohm"] },
  { question: "What is the SI unit of electric potential (voltage)?", answer: "Volt", options: ["Volt", "Ampere", "Watt", "Ohm"] },
  { question: "What is the SI unit of resistance?", answer: "Ohm", options: ["Ohm", "Volt", "Ampere", "Watt"] },
  { question: "What is the SI unit of temperature used in science?", answer: "Kelvin", options: ["Kelvin", "Celsius", "Fahrenheit", "Joule"] },
  { question: "What is the freezing point of water in Kelvin?", answer: "273 K", options: ["273 K", "373 K", "0 K", "100 K"] },
  { question: "What causes an echo?", answer: "Reflection of sound", options: ["Reflection of sound", "Refraction of light", "Absorption of sound", "Diffraction"] },
  { question: "What is needed for sound to travel?", answer: "A medium (like air, water, or solid)", options: ["A medium (like air, water, or solid)", "Vacuum", "Light", "Nothing"] },
  { question: "Can sound travel in a vacuum (like space)?", answer: "No", options: ["No", "Yes", "Sometimes", "Only at night"] },
  { question: "Does light need a medium to travel?", answer: "No, it can travel through vacuum", options: ["No, it can travel through vacuum", "Yes, always", "Only through air", "Only through water"] },
  { question: "What is the speed of sound compared to the speed of light?", answer: "Much slower", options: ["Much slower", "Much faster", "The same", "Cannot compare"] },
  { question: "What is the bending of light when it passes from one medium to another called?", answer: "Refraction", options: ["Refraction", "Reflection", "Diffraction", "Dispersion"] },
  { question: "What is the bouncing back of light from a surface called?", answer: "Reflection", options: ["Reflection", "Refraction", "Diffraction", "Dispersion"] },
  { question: "What splits white light into seven colors, like a rainbow?", answer: "Dispersion (through a prism)", options: ["Dispersion (through a prism)", "Reflection", "Refraction only", "Absorption"] },
  { question: "What are the seven colors of the rainbow in order?", answer: "Violet, Indigo, Blue, Green, Yellow, Orange, Red", options: ["Violet, Indigo, Blue, Green, Yellow, Orange, Red", "Red, Blue, Green, Yellow, Orange, Violet, Indigo", "Only Red, Blue, Yellow", "Black and white shades"] },
  { question: "What natural phenomenon forms after rain due to sunlight?", answer: "Rainbow", options: ["Rainbow", "Fog", "Dew", "Frost"] },
  { question: "What is the process of a liquid turning into vapor called?", answer: "Evaporation", options: ["Evaporation", "Condensation", "Sublimation", "Deposition"] },
  { question: "What is the process of a vapor turning into liquid called?", answer: "Condensation", options: ["Condensation", "Evaporation", "Sublimation", "Deposition"] },
  { question: "What is an acid's taste generally like?", answer: "Sour", options: ["Sour", "Sweet", "Bitter", "Salty"] },
  { question: "What is a base's taste generally like?", answer: "Bitter", options: ["Bitter", "Sour", "Sweet", "Salty"] },
  { question: "What tool tells us if a substance is acidic or basic?", answer: "Litmus paper", options: ["Litmus paper", "Thermometer", "Barometer", "Compass"] },
  { question: "What color does litmus paper turn in an acid?", answer: "Red", options: ["Red", "Blue", "Green", "Yellow"] },
  { question: "What color does litmus paper turn in a base?", answer: "Blue", options: ["Blue", "Red", "Green", "Yellow"] },
  { question: "What is a substance that is neither acidic nor basic called?", answer: "Neutral", options: ["Neutral", "Acidic", "Basic", "Alkaline"] },
  { question: "What is the pH value of a neutral substance?", answer: "7", options: ["7", "0", "14", "10"] },
  { question: "Name a common acid found in the kitchen.", answer: "Vinegar (acetic acid)", options: ["Vinegar (acetic acid)", "Baking soda", "Salt", "Sugar"] },
  { question: "Name a common base found in the kitchen.", answer: "Baking soda", options: ["Baking soda", "Vinegar", "Lemon juice", "Sugar"] },
  { question: "What do we call the smallest unit of life?", answer: "Cell", options: ["Cell", "Tissue", "Organ", "Atom"] },
  { question: "What is the control center of a cell called?", answer: "Nucleus", options: ["Nucleus", "Cytoplasm", "Membrane", "Wall"] },
  { question: "What is the outer covering of a cell called?", answer: "Cell membrane", options: ["Cell membrane", "Nucleus", "Cytoplasm", "Vacuole"] },
  { question: "What extra structure do plant cells have that animal cells don't?", answer: "Cell wall", options: ["Cell wall", "Nucleus", "Cytoplasm", "Membrane"] },
  { question: "What do we call organisms made of only one cell?", answer: "Unicellular organisms", options: ["Unicellular organisms", "Multicellular organisms", "Complex organisms", "Vertebrates"] },
  { question: "What do we call organisms made of many cells?", answer: "Multicellular organisms", options: ["Multicellular organisms", "Unicellular organisms", "Simple organisms", "Single-celled organisms"] },
  { question: "What structures inside cells produce energy?", answer: "Mitochondria", options: ["Mitochondria", "Nucleus", "Vacuole", "Ribosome"] },
  { question: "What are mitochondria often called?", answer: "Powerhouse of the cell", options: ["Powerhouse of the cell", "Brain of the cell", "Skin of the cell", "Heart of the cell"] },
  { question: "What do we call an organism's genetic material that carries traits?", answer: "DNA", options: ["DNA", "RNA only", "Protein", "Enzyme"] },
  { question: "What do we call the study of how traits pass from parents to offspring?", answer: "Genetics", options: ["Genetics", "Ecology", "Anatomy", "Physiology"] },
  { question: "Who is known as the father of genetics for his pea plant experiments?", answer: "Gregor Mendel", options: ["Gregor Mendel", "Charles Darwin", "Louis Pasteur", "Isaac Newton"] },
  { question: "What is the process by which living things change over generations called?", answer: "Evolution", options: ["Evolution", "Adaptation only", "Metamorphosis", "Migration"] },
  { question: "Who proposed the theory of evolution?", answer: "Charles Darwin", options: ["Charles Darwin", "Gregor Mendel", "Isaac Newton", "Albert Einstein"] },
  { question: "What do we call animals or plants that no longer exist?", answer: "Extinct species", options: ["Extinct species", "Endangered species", "Native species", "Invasive species"] },
  { question: "What do we call species at risk of becoming extinct?", answer: "Endangered species", options: ["Endangered species", "Extinct species", "Common species", "Invasive species"] },
  { question: "Name a famous extinct animal.", answer: "Dinosaur", options: ["Dinosaur", "Tiger", "Elephant", "Panda"] },
  { question: "What natural event is believed to have caused dinosaur extinction?", answer: "Asteroid impact", options: ["Asteroid impact", "Flood", "Volcanic eruption of Everest", "Ice age only"] },
  { question: "What do we call fossilized remains of ancient life?", answer: "Fossils", options: ["Fossils", "Minerals", "Rocks only", "Crystals"] },
  { question: "What is the study of fossils called?", answer: "Paleontology", options: ["Paleontology", "Archaeology", "Geology", "Biology only"] },
  { question: "What do we call rain that has become acidic due to pollution?", answer: "Acid rain", options: ["Acid rain", "Normal rain", "Monsoon rain", "Hail"] },
  { question: "What causes acid rain mainly?", answer: "Pollution from burning fossil fuels", options: ["Pollution from burning fossil fuels", "Too much sunlight", "Cold weather", "Ocean waves"] },
  { question: "What is the process of trees being cut down on a large scale called?", answer: "Deforestation", options: ["Deforestation", "Afforestation", "Reforestation", "Cultivation"] },
  { question: "What is the process of planting new trees called?", answer: "Afforestation", options: ["Afforestation", "Deforestation", "Erosion", "Pollution"] },
  { question: "What is the buildup of harmful substances in the environment called?", answer: "Pollution", options: ["Pollution", "Conservation", "Recycling", "Afforestation"] },
  { question: "What are the 3 R's of protecting our environment?", answer: "Reduce, Reuse, Recycle", options: ["Reduce, Reuse, Recycle", "Read, Write, Learn", "Run, Rest, Repeat", "Grow, Water, Harvest"] },
  { question: "What layer protects Earth from harmful UV rays from the sun?", answer: "Ozone layer", options: ["Ozone layer", "Troposphere", "Ionosphere", "Exosphere"] },
  { question: "What human activity has caused holes in the ozone layer?", answer: "Use of harmful chemicals (CFCs)", options: ["Use of harmful chemicals (CFCs)", "Planting trees", "Recycling", "Using solar energy"] },
  { question: "What do we call the gradual rise in Earth's average temperature?", answer: "Global warming", options: ["Global warming", "Climate cycle", "Ozone depletion", "Ice age"] },
  { question: "What do we call gases that trap heat and cause global warming?", answer: "Greenhouse gases", options: ["Greenhouse gases", "Noble gases", "Inert gases", "Rare gases"] },
  { question: "Name a major greenhouse gas.", answer: "Carbon dioxide", options: ["Carbon dioxide", "Nitrogen", "Oxygen", "Hydrogen"] },
  { question: "What do we call energy sources that will never run out, like sunlight?", answer: "Renewable energy", options: ["Renewable energy", "Non-renewable energy", "Fossil energy", "Chemical energy"] },
  { question: "What do we call the process of converting waste materials into reusable items?", answer: "Recycling", options: ["Recycling", "Composting", "Polluting", "Burning"] },
  { question: "What do we call decomposed organic waste used as fertilizer?", answer: "Compost", options: ["Compost", "Fertilizer only", "Manure only", "Soil"] },

  { question: "What do we call materials that can be recycled easily, like paper and glass?", answer: "Recyclable materials", options: ["Recyclable materials", "Biodegradable materials only", "Non-recyclable materials", "Hazardous materials"] },
  { question: "What do we call waste that decomposes naturally over time?", answer: "Biodegradable waste", options: ["Biodegradable waste", "Non-biodegradable waste", "Recyclable waste only", "Hazardous waste"] },
  { question: "What do we call waste that does not decompose easily, like plastic?", answer: "Non-biodegradable waste", options: ["Non-biodegradable waste", "Biodegradable waste", "Organic waste", "Compost"] },
  { question: "What are the basic building blocks of proteins called?", answer: "Amino acids", options: ["Amino acids", "Fatty acids", "Nucleotides", "Sugars"] },
  { question: "What are the basic building blocks of carbohydrates called?", answer: "Sugars (glucose)", options: ["Sugars (glucose)", "Amino acids", "Fatty acids", "Nucleotides"] },
  { question: "What do we call the process of cells dividing to form two new cells?", answer: "Cell division", options: ["Cell division", "Cell fusion", "Cell death", "Cell growth only"] },
  { question: "What natural process forms mountains over millions of years through plate movement?", answer: "Tectonic plate movement (mountain building)", options: ["Tectonic plate movement (mountain building)", "Erosion only", "Weathering only", "Volcanic eruption only"] },
  { question: "What do we call the layer of Earth's crust and upper mantle that moves as plates?", answer: "Lithosphere", options: ["Lithosphere", "Asthenosphere", "Core", "Mantle only"] },


]);
