/* ============================================================
   🔬  SCIENCE — Class 1
   ------------------------------------------------------------
   HOW TO EDIT THIS FILE
   • Each { ... } line below is ONE question.
   • Keep this exact shape:
       { question: "your question?", answer: "Correct", options: ["Correct","B","C","D"] }
   • RULES:
       - Give exactly 4 options.
       - The "answer" text must EXACTLY match one of the 4 options.
       - Wrap text in "double quotes". If your text has a " inside it,
         write it as \" (a backslash then a quote).
   • Add or delete question lines freely.
   • Save the file, then refresh the quiz page — changes appear instantly.
   ============================================================ */
registerQuiz("science", 1, [
  { question: "Which gives us light during day?", answer: "Sun", options: ["Sun", "Moon", "Star", "Lamp"] },
  { question: "Which gives us light at night (in sky)?", answer: "Moon", options: ["Moon", "Sun", "Cloud", "Tree"] },
  { question: "What do we breathe?", answer: "Air", options: ["Air", "Water", "Fire", "Sand"] },
  { question: "What do we drink?", answer: "Water", options: ["Water", "Air", "Sand", "Mud"] },
  { question: "Ice is cold or hot?", answer: "Cold", options: ["Cold", "Hot", "Warm", "Boiling"] },
  { question: "Fire is cold or hot?", answer: "Hot", options: ["Hot", "Cold", "Cool", "Frozen"] },
  { question: "Which floats on water?", answer: "Wood", options: ["Wood", "Stone", "Iron", "Coin"] },
  { question: "Which sinks in water?", answer: "Stone", options: ["Stone", "Wood", "Leaf", "Paper"] },
  { question: "Sun rises in?", answer: "East", options: ["East", "West", "North", "South"] },
  { question: "Sun sets in?", answer: "West", options: ["West", "East", "North", "South"] },
  { question: "Which is hot?", answer: "Tea", options: ["Tea", "Ice", "Snow", "Cold milk"] },
  { question: "Which is sweet?", answer: "Sugar", options: ["Sugar", "Salt", "Lemon", "Chilli"] },
  { question: "Which is sour?", answer: "Lemon", options: ["Lemon", "Sugar", "Honey", "Banana"] },
  { question: "Plants need ___ to grow.", answer: "Water", options: ["Water", "Oil", "Milk", "Juice"] },
  { question: "Where does rain come from?", answer: "Clouds", options: ["Clouds", "Sun", "Trees", "Ground"] },
  { question: "What do plants give us?", answer: "Oxygen", options: ["Oxygen", "Smoke", "Dust", "Heat"] },
  { question: "A magnet attracts?", answer: "Iron", options: ["Iron", "Wood", "Plastic", "Paper"] },
  { question: "Which is a liquid?", answer: "Milk", options: ["Milk", "Stone", "Wood", "Iron"] },
  { question: "Which is a solid?", answer: "Stone", options: ["Stone", "Water", "Milk", "Juice"] },
  { question: "Which is a gas?", answer: "Air", options: ["Air", "Water", "Stone", "Wood"] },
  { question: "What do we call something that can bend easily?", answer: "Flexible", options: ["Flexible", "Rigid", "Heavy", "Rough"] },
  { question: "What do we call something that cannot bend?", answer: "Rigid", options: ["Rigid", "Flexible", "Soft", "Light"] },
  { question: "Which is heavier, a feather or a stone?", answer: "Stone", options: ["Stone", "Feather", "Both same", "Neither"] },
  { question: "Which is lighter, a feather or a stone?", answer: "Feather", options: ["Feather", "Stone", "Both same", "Neither"] },
  { question: "What do we call things that let light pass through, like glass?", answer: "Transparent", options: ["Transparent", "Opaque", "Rough", "Heavy"] },
  { question: "What do we call things that do not let light pass through?", answer: "Opaque", options: ["Opaque", "Transparent", "Smooth", "Light"] },
  { question: "Which season do we use an umbrella most?", answer: "Rainy season", options: ["Rainy season", "Summer", "Winter", "Spring"] },
  { question: "Which season do we wear woolen clothes?", answer: "Winter", options: ["Winter", "Summer", "Rainy season", "Spring"] },
  { question: "What do we call water in its gas form?", answer: "Steam", options: ["Steam", "Ice", "Snow", "Fog"] },
  { question: "What do we call water in its solid form?", answer: "Ice", options: ["Ice", "Steam", "Vapor", "Rain"] },
  { question: "What happens to ice when it gets warm?", answer: "It melts", options: ["It melts", "It freezes", "It disappears", "It grows"] },
  { question: "What happens to water when it gets very cold?", answer: "It freezes", options: ["It freezes", "It boils", "It evaporates", "It disappears"] },
  { question: "Which of these is a natural source of light?", answer: "Sun", options: ["Sun", "Bulb", "Candle", "Torch"] },
  { question: "Which of these is a man-made source of light?", answer: "Bulb", options: ["Bulb", "Sun", "Stars", "Moon light itself"] },
  { question: "What do we call things that are alive?", answer: "Living things", options: ["Living things", "Non-living things", "Objects", "Materials"] },
  { question: "What do we call things that are not alive?", answer: "Non-living things", options: ["Non-living things", "Living things", "Animals", "Plants"] },
  { question: "Is a rock living or non-living?", answer: "Non-living", options: ["Non-living", "Living", "Both", "Neither"] },
  { question: "Is a tree living or non-living?", answer: "Living", options: ["Living", "Non-living", "Both", "Neither"] },
  { question: "What do all living things need to survive, besides food?", answer: "Water", options: ["Water", "Toys", "Books", "Money"] },
  { question: "What do we call the five things we use to sense the world?", answer: "Senses", options: ["Senses", "Feelings", "Actions", "Thoughts"] },
  { question: "How many senses do we usually have?", answer: "5", options: ["5", "3", "4", "6"] },
  { question: "What is the sense of touch felt through?", answer: "Skin", options: ["Skin", "Eyes", "Ears", "Nose"] },
  { question: "What do we call baby plants growing from seeds?", answer: "Seedlings", options: ["Seedlings", "Saplings", "Sprouts", "Buds"] },
  { question: "What do seeds need to grow into plants?", answer: "Water, air and sunlight", options: ["Water, air and sunlight", "Only water", "Only sunlight", "Only soil"] },
  { question: "What is the process of a seed starting to grow called?", answer: "Germination", options: ["Germination", "Photosynthesis", "Pollination", "Respiration"] },
  { question: "Which of these floats on water: a leaf or a coin?", answer: "Leaf", options: ["Leaf", "Coin", "Both float", "Neither floats"] },
  { question: "Which of these sinks in water: a leaf or a coin?", answer: "Coin", options: ["Coin", "Leaf", "Both sink", "Neither sinks"] },
  { question: "What do we call the pull that brings things down to Earth?", answer: "Gravity", options: ["Gravity", "Magnetism", "Friction", "Energy"] },
  { question: "What happens when you drop a ball?", answer: "It falls down", options: ["It falls down", "It floats up", "It stays still", "It disappears"] },
  { question: "Which is louder, a whisper or a shout?", answer: "Shout", options: ["Shout", "Whisper", "Both same", "Neither"] },
  { question: "What do we call things that make sound?", answer: "Sound sources", options: ["Sound sources", "Silent things", "Light sources", "Heat sources"] },
  { question: "What part of our body helps us hear sounds?", answer: "Ears", options: ["Ears", "Eyes", "Nose", "Skin"] },
  { question: "Which of these is hot: ice or fire?", answer: "Fire", options: ["Fire", "Ice", "Both same", "Neither"] },
  { question: "Which of these is cold: ice or fire?", answer: "Ice", options: ["Ice", "Fire", "Both same", "Neither"] },
  { question: "What do we use to measure how hot or cold something is?", answer: "Thermometer", options: ["Thermometer", "Ruler", "Clock", "Scale"] },
  { question: "What do we use to measure weight?", answer: "Weighing scale", options: ["Weighing scale", "Thermometer", "Ruler", "Clock"] },
  { question: "What do we use to measure length?", answer: "Ruler", options: ["Ruler", "Thermometer", "Weighing scale", "Clock"] },
  { question: "What do we use to tell time?", answer: "Clock", options: ["Clock", "Ruler", "Thermometer", "Scale"] },
  { question: "What do magnets attract?", answer: "Iron", options: ["Iron", "Wood", "Plastic", "Paper"] },
  { question: "Which of these will a magnet attract: a nail or a pencil?", answer: "Nail", options: ["Nail", "Pencil", "Both", "Neither"] },
  { question: "What do we call the two ends of a magnet?", answer: "Poles", options: ["Poles", "Tips", "Corners", "Edges"] },
  { question: "Do the same poles of two magnets attract or repel?", answer: "Repel", options: ["Repel", "Attract", "Neither", "Both"] },
  { question: "Do different poles of two magnets attract or repel?", answer: "Attract", options: ["Attract", "Repel", "Neither", "Both"] },
  { question: "What do we call food that comes from plants?", answer: "Vegetarian food", options: ["Vegetarian food", "Non-vegetarian food", "Junk food", "Fast food"] },
  { question: "What do we call food that comes from animals like meat and eggs?", answer: "Non-vegetarian food", options: ["Non-vegetarian food", "Vegetarian food", "Junk food", "Healthy food"] },
  { question: "Which of these is a fruit: apple or potato?", answer: "Apple", options: ["Apple", "Potato", "Both fruits", "Neither"] },
  { question: "Which of these is a vegetable: carrot or mango?", answer: "Carrot", options: ["Carrot", "Mango", "Both vegetables", "Neither"] },
  { question: "What do we call foods that are good for our health?", answer: "Healthy food", options: ["Healthy food", "Junk food", "Fast food", "Spoiled food"] },
  { question: "What should we do before eating food?", answer: "Wash our hands", options: ["Wash our hands", "Run around", "Sleep", "Shout"] },
  { question: "What do we call germs that can make us sick?", answer: "Bacteria/germs", options: ["Bacteria/germs", "Vitamins", "Minerals", "Nutrients"] },
  { question: "What helps our body fight germs and stay healthy?", answer: "Good food and hygiene", options: ["Good food and hygiene", "Junk food", "Dirty water", "Skipping meals"] },
  { question: "What do we call the process of breathing in and out?", answer: "Respiration", options: ["Respiration", "Digestion", "Circulation", "Excretion"] },
  { question: "Which body part helps us breathe?", answer: "Lungs", options: ["Lungs", "Heart", "Stomach", "Liver"] },
  { question: "Which body part pumps blood?", answer: "Heart", options: ["Heart", "Lungs", "Stomach", "Liver"] },
  { question: "What do we call the liquid that flows in our body carrying oxygen?", answer: "Blood", options: ["Blood", "Water", "Milk", "Sweat"] },
  { question: "What color is blood?", answer: "Red", options: ["Red", "Blue", "Green", "Yellow"] },
  { question: "What do we call the hard part inside our body that gives it shape?", answer: "Bones", options: ["Bones", "Skin", "Muscles", "Fat"] },
  { question: "What protects our brain?", answer: "Skull", options: ["Skull", "Skin", "Hair", "Ears"] },
  { question: "What do we call the outer covering of our body?", answer: "Skin", options: ["Skin", "Bones", "Muscles", "Blood"] },
  { question: "Which sense organ do we use to read a book?", answer: "Eyes", options: ["Eyes", "Ears", "Nose", "Tongue"] },
  { question: "What kind of energy does the sun give us?", answer: "Light and heat energy", options: ["Light and heat energy", "Sound energy", "Electrical energy", "Chemical energy"] },
  { question: "What do we call things that give us energy to move, like fuel?", answer: "Energy sources", options: ["Energy sources", "Waste", "Water", "Air only"] },
  { question: "What do plants release into the air that we need to breathe?", answer: "Oxygen", options: ["Oxygen", "Carbon dioxide", "Nitrogen", "Smoke"] },
  { question: "What do we call the air around the Earth?", answer: "Atmosphere", options: ["Atmosphere", "Ocean", "Ground", "Space"] },
  { question: "Which is a source of clean, renewable energy from the sun?", answer: "Solar energy", options: ["Solar energy", "Coal", "Petrol", "Diesel"] },
  { question: "Which of these is a natural material: wood or plastic?", answer: "Wood", options: ["Wood", "Plastic", "Both natural", "Neither"] },
  { question: "Which of these is a man-made material: plastic or cotton?", answer: "Plastic", options: ["Plastic", "Cotton", "Both man-made", "Neither"] },
  { question: "What is cotton used to make?", answer: "Clothes", options: ["Clothes", "Cars", "Phones", "Computers"] },
  { question: "What do bees collect from flowers?", answer: "Nectar", options: ["Nectar", "Water", "Leaves", "Soil"] },
  { question: "What is milk turned into when churned?", answer: "Butter", options: ["Butter", "Bread", "Sugar", "Rice"] },
  { question: "What is the study of the human body and health called simply?", answer: "Science", options: ["Science", "Art", "Math", "History"] },
  { question: "What do we call a scientist who studies plants?", answer: "Botanist", options: ["Botanist", "Zoologist", "Chemist", "Physicist"] },
  { question: "What do we call a scientist who studies animals?", answer: "Zoologist", options: ["Zoologist", "Botanist", "Chemist", "Physicist"] },
  { question: "What is a simple machine that helps us lift heavy things easily?", answer: "Lever", options: ["Lever", "Wheel", "Screw", "Wedge"] },
  { question: "What simple round object helps things move easily?", answer: "Wheel", options: ["Wheel", "Lever", "Screw", "Wedge"] },
  { question: "What do we call the force that slows things down when they rub together?", answer: "Friction", options: ["Friction", "Gravity", "Magnetism", "Energy"] },
  { question: "Why is it easier to walk on rough ground than on ice?", answer: "More friction on rough ground", options: ["More friction on rough ground", "Less friction on rough ground", "Ice is heavier", "Rough ground is softer"] },
  { question: "What do we call the change of state from liquid to gas?", answer: "Evaporation", options: ["Evaporation", "Condensation", "Freezing", "Melting"] },
  { question: "What do we call the change of state from gas to liquid?", answer: "Condensation", options: ["Condensation", "Evaporation", "Freezing", "Melting"] },






]);
