/* ============================================================
   👤  HUMAN BODY — Class 5
   ------------------------------------------------------------
   HOW TO EDIT THIS FILE
   • Each { ... } line below is ONE question.
   • Keep this exact shape:
       { question: "your question?", answer: "Correct", options: ["Correct","B","C","D"] }
   • RULES:
       - Give exactly 4 options.
       - The "answer" text must EXACTLY match one of the 4 options.
       - Wrap text in "double quotes". If your text has a " inside it,
         write it as \" (a backslash then a quote).
   • Add or delete question lines freely.
   • Save the file, then refresh the quiz page — changes appear instantly.
   ============================================================ */
registerQuiz("humanbody", 5, [
  { question: "Vitamin from sunlight?", answer: "Vitamin D", options: ["Vitamin D", "A", "C", "B"] },
  { question: "Vitamin in citrus fruits?", answer: "Vitamin C", options: ["Vitamin C", "A", "D", "K"] },
  { question: "Vitamin for eyesight?", answer: "Vitamin A", options: ["Vitamin A", "C", "D", "K"] },
  { question: "Vitamin for blood clotting?", answer: "Vitamin K", options: ["Vitamin K", "A", "C", "D"] },
  { question: "Lack of Vitamin C causes?", answer: "Scurvy", options: ["Scurvy", "Rickets", "Beriberi", "Anemia"] },
  { question: "Lack of Vitamin D causes?", answer: "Rickets", options: ["Rickets", "Scurvy", "Beriberi", "Anemia"] },
  { question: "Lack of iron causes?", answer: "Anemia", options: ["Anemia", "Scurvy", "Rickets", "Goiter"] },
  { question: "Lack of iodine causes?", answer: "Goiter", options: ["Goiter", "Anemia", "Scurvy", "Rickets"] },
  { question: "Lack of insulin causes?", answer: "Diabetes", options: ["Diabetes", "Goiter", "Anemia", "Asthma"] },
  { question: "Insulin made by?", answer: "Pancreas", options: ["Pancreas", "Liver", "Kidney", "Spleen"] },
  { question: "Bile is made by?", answer: "Liver", options: ["Liver", "Pancreas", "Kidney", "Stomach"] },
  { question: "Urine is made by?", answer: "Kidney", options: ["Kidney", "Liver", "Pancreas", "Spleen"] },
  { question: "Nephron is in?", answer: "Kidney", options: ["Kidney", "Liver", "Lungs", "Heart"] },
  { question: "Alveoli are in?", answer: "Lungs", options: ["Lungs", "Heart", "Liver", "Stomach"] },
  { question: "Neurons are cells of?", answer: "Nervous system", options: ["Nervous system", "Muscular", "Skeletal", "Digestive"] },
  { question: "DNA is in?", answer: "Cell nucleus", options: ["Cell nucleus", "Skin only", "Hair only", "Bones only"] },
  { question: "Reproductive cells in females?", answer: "Eggs/Ova", options: ["Eggs/Ova", "Sperm", "Cells", "Tissues"] },
  { question: "Reproductive cells in males?", answer: "Sperm", options: ["Sperm", "Eggs", "Cells", "Tissues"] },
  { question: "Adam's apple is in?", answer: "Throat (men)", options: ["Throat (men)", "Stomach", "Chest", "Nose"] },
  { question: "Sweat is produced by?", answer: "Sweat glands", options: ["Sweat glands", "Liver", "Kidney", "Heart"] },
  { question: "What is the study of genes and heredity called?", answer: "Genetics", options: ["Genetics", "Anatomy", "Physiology", "Pathology"] },
  { question: "What molecule carries genetic information in our cells?", answer: "DNA", options: ["DNA", "RNA only", "Protein", "Enzyme"] },
  { question: "What structure in the cell nucleus contains DNA organized into genes?", answer: "Chromosomes", options: ["Chromosomes", "Mitochondria", "Ribosomes", "Cytoplasm"] },
  { question: "How many pairs of chromosomes do humans have?", answer: "23 pairs", options: ["23 pairs", "20 pairs", "46 pairs (not in pairs)", "12 pairs"] },
  { question: "Which chromosome pair determines a person's biological sex?", answer: "The 23rd pair (X and Y)", options: ["The 23rd pair (X and Y)", "The 1st pair", "The 22nd pair", "All pairs equally"] },
  { question: "What combination of sex chromosomes typically results in a male?", answer: "XY", options: ["XY", "XX", "YY", "XO"] },
  { question: "What combination of sex chromosomes typically results in a female?", answer: "XX", options: ["XX", "XY", "YY", "XO"] },
  { question: "What is the term for reproductive cells in the human body?", answer: "Gametes", options: ["Gametes", "Zygotes", "Embryos", "Neurons"] },
  { question: "What is the female reproductive cell called?", answer: "Ovum (egg)", options: ["Ovum (egg)", "Sperm", "Zygote", "Embryo"] },
  { question: "What is the male reproductive cell called?", answer: "Sperm", options: ["Sperm", "Ovum", "Zygote", "Embryo"] },
  { question: "What do we call the cell formed when a sperm fertilizes an egg?", answer: "Zygote", options: ["Zygote", "Embryo", "Fetus", "Gamete"] },
  { question: "What organ in females produces eggs?", answer: "Ovaries", options: ["Ovaries", "Testes", "Uterus", "Fallopian tube"] },
  { question: "What organ in males produces sperm?", answer: "Testes", options: ["Testes", "Ovaries", "Uterus", "Prostate"] },
  { question: "What organ in females carries and nourishes a developing baby?", answer: "Uterus (womb)", options: ["Uterus (womb)", "Ovaries", "Fallopian tube", "Cervix"] },
  { question: "How many weeks does a typical human pregnancy last approximately?", answer: "40 weeks", options: ["40 weeks", "20 weeks", "60 weeks", "10 weeks"] },
  { question: "What is the developing baby called during the first eight weeks of pregnancy?", answer: "Embryo", options: ["Embryo", "Fetus", "Zygote", "Infant"] },
  { question: "What is the developing baby called after eight weeks until birth?", answer: "Fetus", options: ["Fetus", "Embryo", "Zygote", "Neonate"] },
  { question: "What organ connects the mother and baby, providing nutrients during pregnancy?", answer: "Placenta", options: ["Placenta", "Uterus", "Umbilical cord alone", "Amniotic sac"] },
  { question: "What tube connects the baby to the placenta?", answer: "Umbilical cord", options: ["Umbilical cord", "Fallopian tube", "Spinal cord", "Trachea"] },
  { question: "What fluid-filled sac protects the baby in the womb?", answer: "Amniotic sac", options: ["Amniotic sac", "Placenta", "Uterus lining", "Ovary"] },
  { question: "What is the process of cell division that produces gametes (sperm and eggs) called?", answer: "Meiosis", options: ["Meiosis", "Mitosis", "Fertilization", "Gestation"] },
  { question: "What is the process of cell division for growth and repair called?", answer: "Mitosis", options: ["Mitosis", "Meiosis", "Fertilization", "Gestation"] },
  { question: "What are the basic units of heredity, sections of DNA, called?", answer: "Genes", options: ["Genes", "Chromosomes", "Cells", "Proteins"] },
  { question: "What term describes traits that are passed from parents to children?", answer: "Hereditary traits", options: ["Hereditary traits", "Acquired traits", "Learned traits", "Environmental traits"] },
  { question: "What term describes a physical trait controlled by a dominant gene, always shown if present?", answer: "Dominant trait", options: ["Dominant trait", "Recessive trait", "Mutant trait", "Hybrid trait"] },
  { question: "What term describes a trait only shown when two copies of the gene are present?", answer: "Recessive trait", options: ["Recessive trait", "Dominant trait", "Mutant trait", "Hybrid trait"] },
  { question: "What is a change in the DNA sequence called?", answer: "Mutation", options: ["Mutation", "Reproduction", "Fertilization", "Metabolism"] },
  { question: "What system in our body is responsible for fighting off diseases and infections?", answer: "Immune system", options: ["Immune system", "Nervous system", "Circulatory system", "Digestive system"] },
  { question: "What blood cells specifically produce antibodies to fight infections?", answer: "Lymphocytes (a type of white blood cell)", options: ["Lymphocytes (a type of white blood cell)", "Red blood cells", "Platelets", "Plasma cells only, no lymphocytes"] },
  { question: "What are proteins that help fight specific germs called?", answer: "Antibodies", options: ["Antibodies", "Antigens", "Enzymes", "Hormones"] },
  { question: "What do we call substances that trigger an immune response, like on germs?", answer: "Antigens", options: ["Antigens", "Antibodies", "Enzymes", "Hormones"] },
  { question: "What organ produces lymphocytes and helps filter blood, part of the immune system?", answer: "Spleen", options: ["Spleen", "Liver", "Pancreas", "Kidney"] },
  { question: "What network of vessels carries a clear fluid to help fight infection, alongside blood vessels?", answer: "Lymphatic system", options: ["Lymphatic system", "Circulatory system", "Nervous system", "Endocrine system"] },
  { question: "What is the fluid carried by the lymphatic system called?", answer: "Lymph", options: ["Lymph", "Plasma", "Bile", "Mucus"] },
  { question: "What are small bean-shaped structures in the lymphatic system that filter lymph?", answer: "Lymph nodes", options: ["Lymph nodes", "Kidneys", "Adrenal glands", "Villi"] },
  { question: "What is the term for the body's ability to maintain a stable internal environment?", answer: "Homeostasis", options: ["Homeostasis", "Metabolism", "Digestion", "Circulation"] },
  { question: "What is the functional unit of the kidney called?", answer: "Nephron", options: ["Nephron", "Alveolus", "Neuron", "Villus"] },
  { question: "What tiny finger-like projections in the small intestine absorb nutrients?", answer: "Villi", options: ["Villi", "Alveoli", "Nephrons", "Neurons"] },
  { question: "What is the process of a cell using oxygen to release energy from food called?", answer: "Cellular respiration", options: ["Cellular respiration", "Photosynthesis", "Fermentation only", "Digestion"] },
  { question: "What organelle in a cell is responsible for producing energy (ATP)?", answer: "Mitochondria", options: ["Mitochondria", "Nucleus", "Ribosome", "Golgi apparatus"] },
  { question: "What is the chemical energy currency of the cell called?", answer: "ATP (adenosine triphosphate)", options: ["ATP (adenosine triphosphate)", "DNA", "RNA", "Glucose only"] },




  { question: "What is the term for the body's chemical processes that convert food to energy?", answer: "Metabolism", options: ["Metabolism", "Digestion only", "Respiration only", "Circulation"] },
  { question: "What hormone regulates growth in children, released by the pituitary gland?", answer: "Growth hormone", options: ["Growth hormone", "Insulin", "Adrenaline", "Thyroxine"] },
  { question: "What gland releases thyroxine, regulating metabolism?", answer: "Thyroid gland", options: ["Thyroid gland", "Pituitary gland", "Adrenal gland", "Pancreas"] },
  { question: "What is a condition caused by an underactive thyroid gland?", answer: "Hypothyroidism", options: ["Hypothyroidism", "Hyperthyroidism", "Diabetes", "Goiter only"] },
  { question: "What is a condition caused by an overactive thyroid gland?", answer: "Hyperthyroidism", options: ["Hyperthyroidism", "Hypothyroidism", "Diabetes", "Anemia"] },
  { question: "What is the swelling of the thyroid gland due to iodine deficiency called?", answer: "Goiter", options: ["Goiter", "Hypothyroidism", "Hyperthyroidism", "Diabetes"] },
  { question: "What system controls voluntary and involuntary actions using electrical signals?", answer: "Nervous system", options: ["Nervous system", "Endocrine system", "Circulatory system", "Digestive system"] },
  { question: "What is the part of the nervous system including the brain and spinal cord called?", answer: "Central nervous system", options: ["Central nervous system", "Peripheral nervous system", "Autonomic nervous system", "Somatic nervous system"] },
  { question: "What is the part of the nervous system including nerves outside the brain and spine called?", answer: "Peripheral nervous system", options: ["Peripheral nervous system", "Central nervous system", "Autonomic nervous system only", "Somatic nervous system only"] },
  { question: "What part of the nervous system controls involuntary actions like heartbeat and digestion?", answer: "Autonomic nervous system", options: ["Autonomic nervous system", "Somatic nervous system", "Central nervous system", "Peripheral nervous system only"] },
  { question: "What part of the nervous system controls voluntary muscle movements?", answer: "Somatic nervous system", options: ["Somatic nervous system", "Autonomic nervous system", "Central nervous system", "Peripheral nervous system only"] },
  { question: "What are the two branches of the autonomic nervous system?", answer: "Sympathetic and parasympathetic", options: ["Sympathetic and parasympathetic", "Central and peripheral", "Somatic and visceral", "Motor and sensory"] },
  { question: "Which branch of the autonomic nervous system triggers 'fight or flight'?", answer: "Sympathetic nervous system", options: ["Sympathetic nervous system", "Parasympathetic nervous system", "Central nervous system", "Somatic nervous system"] },
  { question: "Which branch of the autonomic nervous system helps the body 'rest and digest'?", answer: "Parasympathetic nervous system", options: ["Parasympathetic nervous system", "Sympathetic nervous system", "Central nervous system", "Somatic nervous system"] },
  { question: "What is the transmission gap between two neurons called?", answer: "Synapse", options: ["Synapse", "Axon", "Dendrite", "Myelin sheath"] },
  { question: "What chemical messengers cross the synapse to relay nerve signals?", answer: "Neurotransmitters", options: ["Neurotransmitters", "Hormones", "Enzymes", "Antibodies"] },
  { question: "What fatty substance covers nerve fibers to speed up signal transmission?", answer: "Myelin sheath", options: ["Myelin sheath", "Cartilage", "Collagen", "Keratin"] },
  { question: "What part of a neuron receives signals from other neurons?", answer: "Dendrites", options: ["Dendrites", "Axon", "Nucleus", "Cell body"] },
  { question: "What part of a neuron sends signals to other neurons?", answer: "Axon", options: ["Axon", "Dendrites", "Nucleus", "Cell body"] },
  { question: "What is the term for genetically identical offspring from asexual reproduction?", answer: "Clones", options: ["Clones", "Hybrids", "Twins always", "Mutants"] },
  { question: "What is the medical term for identical twins developing from a single fertilized egg?", answer: "Monozygotic twins", options: ["Monozygotic twins", "Dizygotic twins", "Fraternal twins", "Conjoined twins always"] },
  { question: "What is the medical term for fraternal twins developing from two separate eggs?", answer: "Dizygotic twins", options: ["Dizygotic twins", "Monozygotic twins", "Identical twins", "Conjoined twins"] },
  { question: "What structure allows the exchange of nutrients and gases between mother and fetus?", answer: "Placenta", options: ["Placenta", "Umbilical cord alone", "Amniotic sac", "Uterus wall alone"] },
  { question: "What is the medical term for childbirth?", answer: "Parturition (labor and delivery)", options: ["Parturition (labor and delivery)", "Gestation", "Fertilization", "Ovulation"] },
  { question: "What is the release of an egg from the ovary called?", answer: "Ovulation", options: ["Ovulation", "Fertilization", "Menstruation", "Gestation"] },
  { question: "What is the monthly shedding of the uterine lining in females called?", answer: "Menstruation", options: ["Menstruation", "Ovulation", "Fertilization", "Gestation"] },
  { question: "What is the period of carrying a developing baby in the womb called?", answer: "Gestation (pregnancy)", options: ["Gestation (pregnancy)", "Ovulation", "Menstruation", "Lactation"] },
  { question: "What is the production of milk by mammary glands after childbirth called?", answer: "Lactation", options: ["Lactation", "Gestation", "Ovulation", "Menstruation"] },
  { question: "What stage of life involves physical changes leading to reproductive maturity?", answer: "Puberty", options: ["Puberty", "Infancy", "Menopause", "Gestation"] },
  { question: "What is the stage in women marking the end of menstrual cycles called?", answer: "Menopause", options: ["Menopause", "Puberty", "Gestation", "Lactation"] },
  { question: "What is the term for organisms having both hereditary and environmental influences on traits?", answer: "Nature and nurture", options: ["Nature and nurture", "Only nature", "Only nurture", "Neither factor"] },
  { question: "What is the scientific term for a person's complete set of genes?", answer: "Genome", options: ["Genome", "Genotype only", "Phenotype", "Chromosome"] },
  { question: "What term describes the observable physical traits resulting from genes?", answer: "Phenotype", options: ["Phenotype", "Genotype", "Genome", "Karyotype"] },
  { question: "What term describes the genetic makeup of an organism?", answer: "Genotype", options: ["Genotype", "Phenotype", "Genome", "Karyotype"] },
  { question: "What major international effort mapped the entire human genetic code?", answer: "Human Genome Project", options: ["Human Genome Project", "Human Cell Project", "DNA Mapping Initiative", "Gene Therapy Project"] },
  { question: "What is the process of using engineered genes to treat diseases called?", answer: "Gene therapy", options: ["Gene therapy", "Chemotherapy", "Radiotherapy", "Immunotherapy"] },
  { question: "What is the medical term for cells reproducing uncontrollably, causing tumors?", answer: "Cancer", options: ["Cancer", "Anemia", "Diabetes", "Arthritis"] },
  { question: "What is a non-cancerous growth called?", answer: "Benign tumor", options: ["Benign tumor", "Malignant tumor", "Cancerous tumor", "Metastatic tumor"] },
  { question: "What is a cancerous growth called?", answer: "Malignant tumor", options: ["Malignant tumor", "Benign tumor", "Cyst", "Polyp"] },
]);
