/* ============================================================
   🌍  GK — Class 3
   ------------------------------------------------------------
   HOW TO EDIT THIS FILE
   • Each { ... } line below is ONE question.
   • Keep this exact shape:
       { question: "your question?", answer: "Correct", options: ["Correct","B","C","D"] }
   • RULES:
       - Give exactly 4 options.
       - The "answer" text must EXACTLY match one of the 4 options.
       - Wrap text in "double quotes". If your text has a " inside it,
         write it as \" (a backslash then a quote).
   • Add or delete question lines freely.
   • Save the file, then refresh the quiz page — changes appear instantly.
   ============================================================ */
registerQuiz("gk", 3, [
  { question: "Capital of Rajasthan?", answer: "Jaipur", options: ["Jaipur", "Jodhpur", "Udaipur", "Kota"] },
  { question: "Capital of Maharashtra?", answer: "Mumbai", options: ["Mumbai", "Pune", "Nagpur", "Nashik"] },
  { question: "Capital of UP?", answer: "Lucknow", options: ["Lucknow", "Kanpur", "Agra", "Varanasi"] },
  { question: "Capital of West Bengal?", answer: "Kolkata", options: ["Kolkata", "Howrah", "Darjeeling", "Siliguri"] },
  { question: "Capital of Karnataka?", answer: "Bengaluru", options: ["Bengaluru", "Mysuru", "Mangaluru", "Hubli"] },
  { question: "Capital of Tamil Nadu?", answer: "Chennai", options: ["Chennai", "Madurai", "Coimbatore", "Salem"] },
  { question: "IT capital of India?", answer: "Bengaluru", options: ["Bengaluru", "Hyderabad", "Chennai", "Pune"] },
  { question: "Financial capital of India?", answer: "Mumbai", options: ["Mumbai", "Delhi", "Kolkata", "Chennai"] },
  { question: "Longest river in India?", answer: "Ganga", options: ["Ganga", "Yamuna", "Brahmaputra", "Godavari"] },
  { question: "Highest peak in India?", answer: "Kanchenjunga", options: ["Kanchenjunga", "Mt Everest", "K2", "Nanda Devi"] },
  { question: "Who built Taj Mahal?", answer: "Shah Jahan", options: ["Shah Jahan", "Akbar", "Aurangzeb", "Babur"] },
  { question: "Smallest planet?", answer: "Mercury", options: ["Mercury", "Venus", "Mars", "Pluto"] },
  { question: "Closest planet to Sun?", answer: "Mercury", options: ["Mercury", "Venus", "Earth", "Mars"] },
  { question: "Earth's natural satellite?", answer: "Moon", options: ["Moon", "Sun", "Mars", "Venus"] },
  { question: "Largest continent?", answer: "Asia", options: ["Asia", "Africa", "Europe", "Antarctica"] },
  { question: "Largest desert?", answer: "Sahara", options: ["Sahara", "Thar", "Gobi", "Arabian"] },
  { question: "Tallest mountain in world?", answer: "Mt Everest", options: ["Mt Everest", "K2", "Kanchenjunga", "Lhotse"] },
  { question: "Longest river in world?", answer: "Nile", options: ["Nile", "Amazon", "Ganga", "Mississippi"] },
  { question: "Boiling point of water?", answer: "100°C", options: ["100°C", "90°C", "110°C", "120°C"] },
  { question: "Freezing point of water?", answer: "0°C", options: ["0°C", "-10°C", "10°C", "5°C"] },
  { question: "Who is known as the 'Missile Man of India'?", answer: "APJ Abdul Kalam", options: ["APJ Abdul Kalam", "Homi Bhabha", "Vikram Sarabhai", "CV Raman"] },
  { question: "Who was India's first satellite named after?", answer: "Aryabhata", options: ["Aryabhata", "Chandragupta", "Ashoka", "Bhaskara"] },
  { question: "What was India's first Moon mission called?", answer: "Chandrayaan-1", options: ["Chandrayaan-1", "Mangalyaan", "Aryabhata", "Gaganyaan"] },
  { question: "What was India's Mars mission called?", answer: "Mangalyaan", options: ["Mangalyaan", "Chandrayaan", "Aryabhata", "Gaganyaan"] },
  { question: "What is the name of India's planned human spaceflight mission?", answer: "Gaganyaan", options: ["Gaganyaan", "Chandrayaan", "Mangalyaan", "Aryabhata"] },
  { question: "Who was the first Indian to go to space?", answer: "Rakesh Sharma", options: ["Rakesh Sharma", "Kalpana Chawla", "Sunita Williams", "APJ Abdul Kalam"] },
  { question: "Who was the first woman of Indian origin to go to space?", answer: "Kalpana Chawla", options: ["Kalpana Chawla", "Sunita Williams", "Rakesh Sharma", "Sarojini Naidu"] },
  { question: "Who invented the telephone?", answer: "Alexander Graham Bell", options: ["Alexander Graham Bell", "Thomas Edison", "Isaac Newton", "James Watt"] },
  { question: "Who invented the electric bulb?", answer: "Thomas Edison", options: ["Thomas Edison", "Alexander Graham Bell", "Isaac Newton", "James Watt"] },
  { question: "Who discovered gravity?", answer: "Isaac Newton", options: ["Isaac Newton", "Albert Einstein", "Galileo", "Thomas Edison"] },
  { question: "Who developed the theory of relativity?", answer: "Albert Einstein", options: ["Albert Einstein", "Isaac Newton", "Galileo", "Stephen Hawking"] },
  { question: "Who is known as the father of computers?", answer: "Charles Babbage", options: ["Charles Babbage", "Alan Turing", "Bill Gates", "Steve Jobs"] },
  { question: "Who invented the steam engine?", answer: "James Watt", options: ["James Watt", "Thomas Edison", "Alexander Graham Bell", "Isaac Newton"] },
  { question: "Who painted the Mona Lisa?", answer: "Leonardo da Vinci", options: ["Leonardo da Vinci", "Pablo Picasso", "Vincent van Gogh", "Michelangelo"] },
  { question: "Who wrote the play 'Romeo and Juliet'?", answer: "William Shakespeare", options: ["William Shakespeare", "Charles Dickens", "Mark Twain", "Leo Tolstoy"] },
  { question: "Which is the currency of China?", answer: "Yuan", options: ["Yuan", "Won", "Yen", "Ringgit"] },
  { question: "Which is the currency of Russia?", answer: "Ruble", options: ["Ruble", "Yuan", "Yen", "Franc"] },
  { question: "Which is the largest desert in the world?", answer: "Sahara Desert", options: ["Sahara Desert", "Thar Desert", "Gobi Desert", "Kalahari Desert"] },
  { question: "Which is the largest continent in the world?", answer: "Asia", options: ["Asia", "Africa", "Europe", "North America"] },
  { question: "Which is the smallest continent in the world?", answer: "Australia", options: ["Australia", "Europe", "Antarctica", "South America"] },
  { question: "Which country is known as the 'Land of the Rising Sun'?", answer: "Japan", options: ["Japan", "China", "Korea", "Thailand"] },
  { question: "Which country gifted the Statue of Liberty to the USA?", answer: "France", options: ["France", "UK", "Spain", "Italy"] },
  { question: "Which is the tallest animal in the world?", answer: "Giraffe", options: ["Giraffe", "Elephant", "Camel", "Horse"] },
  { question: "Which is the largest animal in the world?", answer: "Blue whale", options: ["Blue whale", "Elephant", "Giraffe", "Shark"] },
  { question: "Which is the fastest land animal?", answer: "Cheetah", options: ["Cheetah", "Lion", "Horse", "Tiger"] },
  { question: "Which is the largest land animal?", answer: "African elephant", options: ["African elephant", "Rhino", "Hippo", "Giraffe"] },
  { question: "Which bird cannot fly but can run fast?", answer: "Ostrich", options: ["Ostrich", "Peacock", "Sparrow", "Eagle"] },
  { question: "Which bird is known for its beautiful feathers and dance?", answer: "Peacock", options: ["Peacock", "Ostrich", "Sparrow", "Crow"] },
  { question: "What do we call animals that eat only plants?", answer: "Herbivores", options: ["Herbivores", "Carnivores", "Omnivores", "Insectivores"] },
  { question: "What do we call animals that eat only meat?", answer: "Carnivores", options: ["Carnivores", "Herbivores", "Omnivores", "Insectivores"] },
  { question: "What do we call animals that eat both plants and meat?", answer: "Omnivores", options: ["Omnivores", "Herbivores", "Carnivores", "Insectivores"] },
  { question: "What is a group of lions called?", answer: "Pride", options: ["Pride", "Herd", "Flock", "Pack"] },
  { question: "What is a group of wolves called?", answer: "Pack", options: ["Pack", "Pride", "Herd", "Flock"] },
  { question: "What is a group of birds called?", answer: "Flock", options: ["Flock", "Pride", "Herd", "Pack"] },
  { question: "What is a baby kangaroo called?", answer: "Joey", options: ["Joey", "Cub", "Calf", "Fawn"] },
  { question: "What is a baby deer called?", answer: "Fawn", options: ["Fawn", "Joey", "Cub", "Calf"] },
  { question: "What is a young frog called before it grows legs?", answer: "Tadpole", options: ["Tadpole", "Fawn", "Joey", "Cub"] },
  { question: "Which insect makes silk?", answer: "Silkworm", options: ["Silkworm", "Bee", "Ant", "Butterfly"] },
  { question: "Which insect makes honey?", answer: "Bee", options: ["Bee", "Silkworm", "Ant", "Butterfly"] },
  { question: "What do we call the process of a caterpillar becoming a butterfly?", answer: "Metamorphosis", options: ["Metamorphosis", "Photosynthesis", "Germination", "Pollination"] },
  { question: "What is the study of living things called?", answer: "Biology", options: ["Biology", "Physics", "Chemistry", "Geography"] },
  { question: "What is the study of stars and planets called?", answer: "Astronomy", options: ["Astronomy", "Biology", "Chemistry", "Geology"] },
  { question: "What is the study of matter and energy called?", answer: "Physics", options: ["Physics", "Biology", "Chemistry", "Astronomy"] },
  { question: "What is the study of substances and their reactions called?", answer: "Chemistry", options: ["Chemistry", "Physics", "Biology", "Astronomy"] },
  { question: "Who is called the father of modern physics?", answer: "Albert Einstein", options: ["Albert Einstein", "Isaac Newton", "Galileo", "Stephen Hawking"] },
  { question: "Who is called the father of the Indian nuclear program?", answer: "Homi J. Bhabha", options: ["Homi J. Bhabha", "APJ Abdul Kalam", "Vikram Sarabhai", "CV Raman"] },
  { question: "Who is called the father of the Indian space program?", answer: "Vikram Sarabhai", options: ["Vikram Sarabhai", "Homi Bhabha", "APJ Abdul Kalam", "CV Raman"] },
  { question: "Which Indian scientist won the Nobel Prize for the scattering of light?", answer: "CV Raman", options: ["CV Raman", "Homi Bhabha", "Vikram Sarabhai", "APJ Abdul Kalam"] },
  { question: "Which Indian won the Nobel Prize for literature in 1913?", answer: "Rabindranath Tagore", options: ["Rabindranath Tagore", "Mother Teresa", "Amartya Sen", "CV Raman"] },
  { question: "Who was the first Indian to win a Nobel Prize?", answer: "Rabindranath Tagore", options: ["Rabindranath Tagore", "CV Raman", "Mother Teresa", "Amartya Sen"] },
  { question: "Which prize is considered the highest honor in various fields globally?", answer: "Nobel Prize", options: ["Nobel Prize", "Bharat Ratna", "Grammy Award", "Oscar Award"] },
  { question: "What award is given for excellence in films in India?", answer: "National Film Award", options: ["National Film Award", "Grammy", "Nobel Prize", "Pulitzer"] },
  { question: "What award is given for excellence in music internationally?", answer: "Grammy Award", options: ["Grammy Award", "Oscar", "Nobel Prize", "Pulitzer"] },
  { question: "What award is given for excellence in films internationally?", answer: "Academy Award (Oscar)", options: ["Academy Award (Oscar)", "Grammy", "Nobel Prize", "Pulitzer"] },
  { question: "Which is the longest wall built by humans?", answer: "Great Wall of China", options: ["Great Wall of China", "Berlin Wall", "Hadrian's Wall", "Western Wall"] },
  { question: "Which ancient wonder still stands today in Egypt?", answer: "Great Pyramid of Giza", options: ["Great Pyramid of Giza", "Colossus of Rhodes", "Hanging Gardens", "Lighthouse of Alexandria"] },
  { question: "Which new wonder of the world is located in India?", answer: "Taj Mahal", options: ["Taj Mahal", "Great Wall of China", "Machu Picchu", "Christ the Redeemer"] },
  { question: "Which new wonder of the world is located in Peru?", answer: "Machu Picchu", options: ["Machu Picchu", "Taj Mahal", "Chichen Itza", "Colosseum"] },
  { question: "Which new wonder of the world is located in Brazil?", answer: "Christ the Redeemer", options: ["Christ the Redeemer", "Taj Mahal", "Machu Picchu", "Petra"] },
  { question: "Which new wonder of the world is located in Jordan?", answer: "Petra", options: ["Petra", "Machu Picchu", "Taj Mahal", "Chichen Itza"] },
  { question: "Which new wonder of the world is located in Mexico?", answer: "Chichen Itza", options: ["Chichen Itza", "Machu Picchu", "Petra", "Taj Mahal"] },
  { question: "Which new wonder of the world is located in Rome, Italy?", answer: "Colosseum", options: ["Colosseum", "Petra", "Chichen Itza", "Machu Picchu"] },
  { question: "Which country hosted the 2020 Olympics (held in 2021)?", answer: "Japan", options: ["Japan", "China", "France", "UK"] },
  { question: "Which country hosted the 2016 Olympics?", answer: "Brazil", options: ["Brazil", "China", "UK", "Russia"] },
  { question: "Which country will host the 2028 Olympics?", answer: "USA", options: ["USA", "France", "Japan", "Australia"] },
  { question: "What is the maximum score possible in one over in cricket (with only runs off the bat, no extras, normally)?", answer: "36", options: ["36", "30", "24", "42"] },
  { question: "How many players are on the field for one cricket team while fielding?", answer: "11", options: ["11", "10", "9", "12"] },
  { question: "What do we call a score of zero in cricket?", answer: "Duck", options: ["Duck", "Golden Duck", "Century", "Half-century"] },
  { question: "What do we call scoring 100 runs in cricket?", answer: "Century", options: ["Century", "Half-century", "Duck", "Hat-trick"] },
  { question: "What do we call a bowler taking 3 wickets on 3 consecutive balls?", answer: "Hat-trick", options: ["Hat-trick", "Century", "Duck", "Maiden over"] },
  { question: "What is an over in cricket made up of?", answer: "6 balls", options: ["6 balls", "4 balls", "8 balls", "10 balls"] },
  { question: "Which trophy is awarded to the winner of the men's cricket World Cup?", answer: "ICC Cricket World Cup trophy", options: ["ICC Cricket World Cup trophy", "Ashes Urn", "Ranji Trophy", "IPL Trophy"] },
  { question: "Which country invented the game of cricket?", answer: "England", options: ["England", "India", "Australia", "USA"] },
  { question: "Which Indian league is famous for T20 cricket?", answer: "Indian Premier League (IPL)", options: ["Indian Premier League (IPL)", "Ranji Trophy", "Duleep Trophy", "Vijay Hazare Trophy"] },
  { question: "What is the national language of Japan?", answer: "Japanese", options: ["Japanese", "Chinese", "Korean", "Thai"] },
  { question: "What is the national language of France?", answer: "French", options: ["French", "Spanish", "Italian", "German"] },
  { question: "What is the official language of Brazil?", answer: "Portuguese", options: ["Portuguese", "Spanish", "French", "Italian"] },
  { question: "What is the most widely spoken language in the world?", answer: "English", options: ["English", "Mandarin Chinese", "Spanish", "Hindi"] },

  { question: "What is the most widely spoken native language in the world?", answer: "Mandarin Chinese", options: ["Mandarin Chinese", "English", "Spanish", "Hindi"] },
  { question: "What do we call a word that means the same as another word?", answer: "Synonym", options: ["Synonym", "Antonym", "Homonym", "Acronym"] },






]);
