/* ============================================================
   🌍  GK — Class 4
   ------------------------------------------------------------
   HOW TO EDIT THIS FILE
   • Each { ... } line below is ONE question.
   • Keep this exact shape:
       { question: "your question?", answer: "Correct", options: ["Correct","B","C","D"] }
   • RULES:
       - Give exactly 4 options.
       - The "answer" text must EXACTLY match one of the 4 options.
       - Wrap text in "double quotes". If your text has a " inside it,
         write it as \" (a backslash then a quote).
   • Add or delete question lines freely.
   • Save the file, then refresh the quiz page — changes appear instantly.
   ============================================================ */
registerQuiz("gk", 4, [
  { question: "Largest country by area?", answer: "Russia", options: ["Russia", "Canada", "USA", "China"] },
  { question: "Most populated country?", answer: "India", options: ["India", "China", "USA", "Indonesia"] },
  { question: "Country of Eiffel Tower?", answer: "France", options: ["France", "Italy", "UK", "Germany"] },
  { question: "Country of Great Wall?", answer: "China", options: ["China", "Japan", "Korea", "Vietnam"] },
  { question: "Country of Statue of Liberty?", answer: "USA", options: ["USA", "UK", "France", "Canada"] },
  { question: "Currency of USA?", answer: "Dollar", options: ["Dollar", "Pound", "Euro", "Yen"] },
  { question: "Currency of UK?", answer: "Pound", options: ["Pound", "Dollar", "Euro", "Franc"] },
  { question: "Currency of Japan?", answer: "Yen", options: ["Yen", "Won", "Yuan", "Rupee"] },
  { question: "Who invented telephone?", answer: "Graham Bell", options: ["Graham Bell", "Edison", "Newton", "Einstein"] },
  { question: "Who invented bulb?", answer: "Edison", options: ["Edison", "Bell", "Tesla", "Newton"] },
  { question: "Who discovered gravity?", answer: "Newton", options: ["Newton", "Einstein", "Galileo", "Edison"] },
  { question: "Space agency of India?", answer: "ISRO", options: ["ISRO", "NASA", "ESA", "DRDO"] },
  { question: "Space agency of USA?", answer: "NASA", options: ["NASA", "ISRO", "ESA", "JAXA"] },
  { question: "First man on Moon?", answer: "Neil Armstrong", options: ["Neil Armstrong", "Yuri Gagarin", "Buzz Aldrin", "Rakesh Sharma"] },
  { question: "First Indian in space?", answer: "Rakesh Sharma", options: ["Rakesh Sharma", "Kalpana Chawla", "Sunita Williams", "APJ Kalam"] },
  { question: "Missile Man of India?", answer: "APJ Abdul Kalam", options: ["APJ Abdul Kalam", "Vikram Sarabhai", "Homi Bhabha", "CV Raman"] },
  { question: "God of cricket?", answer: "Sachin Tendulkar", options: ["Sachin Tendulkar", "Virat Kohli", "MS Dhoni", "Sourav Ganguly"] },
  { question: "Cricket players per team?", answer: "11", options: ["11", "10", "12", "9"] },
  { question: "Olympics held every?", answer: "4 years", options: ["4 years", "2 years", "5 years", "3 years"] },
  { question: "How many bones in adult human?", answer: "206", options: ["206", "201", "210", "220"] },
  { question: "Who was the first man to walk on the Moon?", answer: "Neil Armstrong", options: ["Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "John Glenn"] },
  { question: "Who was the first person to travel into space?", answer: "Yuri Gagarin", options: ["Yuri Gagarin", "Neil Armstrong", "Buzz Aldrin", "Alan Shepard"] },
  { question: "Which spacecraft carried the first Moon landing mission?", answer: "Apollo 11", options: ["Apollo 11", "Apollo 13", "Sputnik", "Voyager"] },
  { question: "Which country launched the first artificial satellite, Sputnik?", answer: "Soviet Union (Russia)", options: ["Soviet Union (Russia)", "USA", "China", "Japan"] },
  { question: "Which is the largest company by market value in tech, known for iPhones?", answer: "Apple", options: ["Apple", "Microsoft", "Google", "Samsung"] },
  { question: "Who founded Microsoft?", answer: "Bill Gates", options: ["Bill Gates", "Steve Jobs", "Mark Zuckerberg", "Elon Musk"] },
  { question: "Who co-founded Apple along with Steve Wozniak?", answer: "Steve Jobs", options: ["Steve Jobs", "Bill Gates", "Mark Zuckerberg", "Larry Page"] },
  { question: "Who founded Facebook?", answer: "Mark Zuckerberg", options: ["Mark Zuckerberg", "Bill Gates", "Steve Jobs", "Jeff Bezos"] },
  { question: "Who founded Amazon?", answer: "Jeff Bezos", options: ["Jeff Bezos", "Bill Gates", "Elon Musk", "Mark Zuckerberg"] },
  { question: "Who founded Tesla and SpaceX?", answer: "Elon Musk", options: ["Elon Musk", "Jeff Bezos", "Bill Gates", "Steve Jobs"] },
  { question: "What does 'www' stand for?", answer: "World Wide Web", options: ["World Wide Web", "World Wide Wire", "Web World Wide", "Wide World Web"] },
  { question: "Who is credited with inventing the World Wide Web?", answer: "Tim Berners-Lee", options: ["Tim Berners-Lee", "Bill Gates", "Steve Jobs", "Alan Turing"] },
  { question: "What does 'CPU' stand for in computers?", answer: "Central Processing Unit", options: ["Central Processing Unit", "Computer Processing Unit", "Central Program Unit", "Central Processing Utility"] },
  { question: "What is the brain of a computer called?", answer: "CPU (Processor)", options: ["CPU (Processor)", "RAM", "Hard Disk", "Monitor"] },
  { question: "What do we call temporary memory in a computer?", answer: "RAM", options: ["RAM", "ROM", "CPU", "Hard Disk"] },
  { question: "Which country has the largest population in the world currently?", answer: "India", options: ["India", "China", "USA", "Indonesia"] },
  { question: "Which country has the second-largest population in the world?", answer: "China", options: ["China", "India", "USA", "Indonesia"] },
  { question: "Which is the most populous city in the world?", answer: "Tokyo", options: ["Tokyo", "Delhi", "Shanghai", "Mumbai"] },
  { question: "Which country has the largest economy in the world (by GDP)?", answer: "USA", options: ["USA", "China", "Japan", "Germany"] },
  { question: "Which is the largest democracy in the world?", answer: "India", options: ["India", "USA", "UK", "Brazil"] },
  { question: "How many members are there in the United Nations Security Council permanently?", answer: "5", options: ["5", "10", "15", "20"] },
  { question: "Which organization works for global peace and cooperation among nations?", answer: "United Nations (UN)", options: ["United Nations (UN)", "WHO", "UNESCO", "NATO"] },
  { question: "Which organization deals with global health issues?", answer: "World Health Organization (WHO)", options: ["World Health Organization (WHO)", "UN", "UNESCO", "UNICEF"] },
  { question: "Which organization helps children worldwide?", answer: "UNICEF", options: ["UNICEF", "WHO", "UNESCO", "UN"] },
  { question: "What does 'UNESCO' focus on?", answer: "Education, science and culture", options: ["Education, science and culture", "Health", "Trade", "Defense"] },
  { question: "What is the headquarters of the United Nations located in?", answer: "New York City", options: ["New York City", "Geneva", "Paris", "London"] },
  { question: "Which trophy is given to the winner of football's World Cup?", answer: "FIFA World Cup Trophy", options: ["FIFA World Cup Trophy", "Champions League Trophy", "Euro Cup Trophy", "Copa America Trophy"] },
  { question: "Which country has won the most FIFA World Cups?", answer: "Brazil", options: ["Brazil", "Germany", "Argentina", "Italy"] },
  { question: "Which country hosted the first FIFA World Cup?", answer: "Uruguay", options: ["Uruguay", "Brazil", "France", "England"] },
  { question: "Who is considered one of the greatest footballers, from Argentina, who won the 2022 World Cup?", answer: "Lionel Messi", options: ["Lionel Messi", "Cristiano Ronaldo", "Pele", "Neymar"] },
  { question: "Who is regarded as football's all-time great, from Brazil, who won 3 World Cups?", answer: "Pele", options: ["Pele", "Messi", "Ronaldo", "Maradona"] },
  { question: "Who holds the record for most international centuries in cricket?", answer: "Sachin Tendulkar", options: ["Sachin Tendulkar", "Virat Kohli", "Ricky Ponting", "Brian Lara"] },
  { question: "Who is known as the 'God of Cricket' in India?", answer: "Sachin Tendulkar", options: ["Sachin Tendulkar", "Virat Kohli", "MS Dhoni", "Kapil Dev"] },
  { question: "Who captained India to win the 1983 Cricket World Cup?", answer: "Kapil Dev", options: ["Kapil Dev", "Sachin Tendulkar", "MS Dhoni", "Sourav Ganguly"] },
  { question: "Who captained India to win the 2011 Cricket World Cup?", answer: "MS Dhoni", options: ["MS Dhoni", "Sachin Tendulkar", "Virat Kohli", "Kapil Dev"] },
  { question: "Who is known as 'Captain Cool' in Indian cricket?", answer: "MS Dhoni", options: ["MS Dhoni", "Virat Kohli", "Sourav Ganguly", "Rohit Sharma"] },
  { question: "Who won the most Grand Slam titles in men's tennis (as of recent record)?", answer: "Novak Djokovic", options: ["Novak Djokovic", "Roger Federer", "Rafael Nadal", "Pete Sampras"] },
  { question: "Who is the fastest man in the world (100m sprint record holder)?", answer: "Usain Bolt", options: ["Usain Bolt", "Carl Lewis", "Justin Gatlin", "Tyson Gay"] },
  { question: "Which country does Usain Bolt come from?", answer: "Jamaica", options: ["Jamaica", "USA", "UK", "Kenya"] },
  { question: "Who won the most Olympic gold medals of all time (swimmer)?", answer: "Michael Phelps", options: ["Michael Phelps", "Usain Bolt", "Carl Lewis", "Mark Spitz"] },
  { question: "What sport does Michael Phelps play?", answer: "Swimming", options: ["Swimming", "Athletics", "Gymnastics", "Cycling"] },
  { question: "Who is a famous Indian badminton player who won an Olympic medal?", answer: "PV Sindhu", options: ["PV Sindhu", "Saina Nehwal", "Sania Mirza", "Mary Kom"] },
  { question: "Who is a famous Indian boxer who won an Olympic medal?", answer: "Mary Kom", options: ["Mary Kom", "PV Sindhu", "Saina Nehwal", "Sania Mirza"] },
  { question: "Who is a famous Indian wrestler who won multiple Olympic medals?", answer: "Sushil Kumar", options: ["Sushil Kumar", "Milkha Singh", "Abhinav Bindra", "Vijender Singh"] },
  { question: "Who won India's first individual Olympic gold medal?", answer: "Abhinav Bindra", options: ["Abhinav Bindra", "Sushil Kumar", "Neeraj Chopra", "Milkha Singh"] },
  { question: "Who won gold for India in javelin throw at the Tokyo Olympics?", answer: "Neeraj Chopra", options: ["Neeraj Chopra", "Abhinav Bindra", "Sushil Kumar", "PV Sindhu"] },
  { question: "Which Indian sprinter was known as the 'Flying Sikh'?", answer: "Milkha Singh", options: ["Milkha Singh", "Neeraj Chopra", "Abhinav Bindra", "PT Usha"] },
  { question: "Which famous Indian athlete is called the 'Payyoli Express'?", answer: "PT Usha", options: ["PT Usha", "Milkha Singh", "Mary Kom", "PV Sindhu"] },
  { question: "What is the capital of the country famous for chocolates and watches?", answer: "Bern (Switzerland)", options: ["Bern (Switzerland)", "Vienna (Austria)", "Brussels (Belgium)", "Amsterdam (Netherlands)"] },
  { question: "Which country is famous for pizza and pasta?", answer: "Italy", options: ["Italy", "France", "Spain", "Greece"] },
  { question: "Which country is famous for sushi and origami?", answer: "Japan", options: ["Japan", "China", "Korea", "Thailand"] },
  { question: "Which country is famous for the tango dance?", answer: "Argentina", options: ["Argentina", "Brazil", "Spain", "Mexico"] },
  { question: "Which country is famous for flamenco dance?", answer: "Spain", options: ["Spain", "Italy", "France", "Portugal"] },
  { question: "Which Indian dance form comes from Tamil Nadu?", answer: "Bharatanatyam", options: ["Bharatanatyam", "Kathak", "Odissi", "Kathakali"] },
  { question: "Which Indian dance form comes from Uttar Pradesh?", answer: "Kathak", options: ["Kathak", "Bharatanatyam", "Odissi", "Kathakali"] },
  { question: "Which Indian dance form comes from Kerala with elaborate makeup?", answer: "Kathakali", options: ["Kathakali", "Kathak", "Bharatanatyam", "Odissi"] },
  { question: "Which Indian dance form comes from Odisha?", answer: "Odissi", options: ["Odissi", "Kathak", "Bharatanatyam", "Manipuri"] },
  { question: "Which Indian musical instrument is a stringed instrument played by plucking?", answer: "Sitar", options: ["Sitar", "Tabla", "Flute", "Harmonium"] },
  { question: "Which Indian musical instrument is a pair of hand drums?", answer: "Tabla", options: ["Tabla", "Sitar", "Flute", "Harmonium"] },
  { question: "Who is a famous sitar player from India who performed worldwide?", answer: "Ravi Shankar", options: ["Ravi Shankar", "Zakir Hussain", "AR Rahman", "Lata Mangeshkar"] },
  { question: "Who is a famous tabla player from India?", answer: "Zakir Hussain", options: ["Zakir Hussain", "Ravi Shankar", "AR Rahman", "Bismillah Khan"] },
  { question: "Who is a famous Indian playback singer known as the 'Nightingale of India' in music?", answer: "Lata Mangeshkar", options: ["Lata Mangeshkar", "Asha Bhosle", "Sarojini Naidu", "Kishore Kumar"] },
  { question: "Which Indian composer won an Oscar for the song 'Jai Ho'?", answer: "AR Rahman", options: ["AR Rahman", "Ravi Shankar", "Zakir Hussain", "Ilaiyaraaja"] },
  { question: "Which is the highest-grossing Indian film industry by number of films made?", answer: "Bollywood (Hindi cinema)", options: ["Bollywood (Hindi cinema)", "Tollywood", "Kollywood", "Hollywood"] },
  { question: "What is the nickname for the Hindi film industry based in Mumbai?", answer: "Bollywood", options: ["Bollywood", "Tollywood", "Kollywood", "Sandalwood"] },
  { question: "Which continent is the Sahara Desert located in?", answer: "Africa", options: ["Africa", "Asia", "Australia", "South America"] },
  { question: "Which continent is the Amazon Rainforest located in?", answer: "South America", options: ["South America", "Africa", "Asia", "North America"] },
  { question: "Which is the largest coral reef and where is it found?", answer: "Great Barrier Reef, Australia", options: ["Great Barrier Reef, Australia", "Red Sea Reef, Egypt", "Belize Reef", "Andaman Reef, India"] },
  { question: "Which is the deepest part of the ocean, located in the Pacific?", answer: "Mariana Trench", options: ["Mariana Trench", "Puerto Rico Trench", "Java Trench", "Tonga Trench"] },
  { question: "What is the name of the process by which water turns into vapor?", answer: "Evaporation", options: ["Evaporation", "Condensation", "Precipitation", "Sublimation"] },
  { question: "What is the name of the process by which vapor turns into water droplets?", answer: "Condensation", options: ["Condensation", "Evaporation", "Precipitation", "Sublimation"] },
  { question: "What is the name for water falling from clouds as rain or snow?", answer: "Precipitation", options: ["Precipitation", "Evaporation", "Condensation", "Transpiration"] },
  { question: "What is the continuous movement of water on Earth called?", answer: "Water cycle", options: ["Water cycle", "Carbon cycle", "Rock cycle", "Nitrogen cycle"] },
  { question: "What is the process by which plants lose water through leaves called?", answer: "Transpiration", options: ["Transpiration", "Evaporation", "Condensation", "Respiration"] },
  { question: "What gas do plants absorb from the air for photosynthesis?", answer: "Carbon dioxide", options: ["Carbon dioxide", "Oxygen", "Nitrogen", "Hydrogen"] },
  { question: "What gas makes up the largest portion of Earth's atmosphere?", answer: "Nitrogen", options: ["Nitrogen", "Oxygen", "Carbon dioxide", "Hydrogen"] },
  { question: "What percentage of Earth's atmosphere is oxygen approximately?", answer: "21%", options: ["21%", "50%", "78%", "10%"] },

  { question: "What percentage of Earth's atmosphere is nitrogen approximately?", answer: "78%", options: ["78%", "21%", "50%", "10%"] },
  { question: "What is the study of ancient human history through remains called?", answer: "Archaeology", options: ["Archaeology", "Anthropology", "Geology", "Biology"] },
  { question: "What is the study of coins and currency called?", answer: "Numismatics", options: ["Numismatics", "Philately", "Archaeology", "Cartography"] },
  { question: "What is the study and collection of stamps called?", answer: "Philately", options: ["Philately", "Numismatics", "Archaeology", "Cartography"] },


]);
