/* ============================================================
   🌍  GK — Class 1
   ------------------------------------------------------------
   HOW TO EDIT THIS FILE
   • Each { ... } line below is ONE question.
   • Keep this exact shape:
       { question: "your question?", answer: "Correct", options: ["Correct","B","C","D"] }
   • RULES:
       - Give exactly 4 options.
       - The "answer" text must EXACTLY match one of the 4 options.
       - Wrap text in "double quotes". If your text has a " inside it,
         write it as \" (a backslash then a quote).
   • Add or delete question lines freely.
   • Save the file, then refresh the quiz page — changes appear instantly.
   ============================================================ */
registerQuiz("gk", 1, [
  { question: "How many days in a week?", answer: "7", options: ["7", "5", "6", "8"] },
  { question: "How many months in a year?", answer: "12", options: ["12", "10", "11", "13"] },
  { question: "How many seasons in a year?", answer: "4", options: ["4", "3", "5", "2"] },
  { question: "First month of year?", answer: "January", options: ["January", "February", "March", "December"] },
  { question: "Last month of year?", answer: "December", options: ["December", "November", "January", "October"] },
  { question: "Day after Sunday?", answer: "Monday", options: ["Monday", "Tuesday", "Saturday", "Friday"] },
  { question: "Day before Sunday?", answer: "Saturday", options: ["Saturday", "Monday", "Friday", "Sunday"] },
  { question: "How many fingers on one hand?", answer: "5", options: ["5", "4", "6", "10"] },
  { question: "How many eyes do we have?", answer: "2", options: ["2", "1", "3", "4"] },
  { question: "How many ears do we have?", answer: "2", options: ["2", "1", "3", "4"] },
  { question: "Color of sun?", answer: "Yellow", options: ["Yellow", "Blue", "Green", "Black"] },
  { question: "Color of leaf?", answer: "Green", options: ["Green", "Blue", "Red", "Yellow"] },
  { question: "Where do fish live?", answer: "Water", options: ["Water", "Tree", "Land", "Sky"] },
  { question: "Where do birds live?", answer: "Nest", options: ["Nest", "Hole", "Den", "Cave"] },
  { question: "What gives us light?", answer: "Sun", options: ["Sun", "Moon", "Star", "Cloud"] },
  { question: "Capital of India?", answer: "New Delhi", options: ["New Delhi", "Mumbai", "Kolkata", "Chennai"] },
  { question: "National animal of India?", answer: "Tiger", options: ["Tiger", "Lion", "Elephant", "Peacock"] },
  { question: "National bird of India?", answer: "Peacock", options: ["Peacock", "Sparrow", "Parrot", "Eagle"] },
  { question: "Currency of India?", answer: "Rupee", options: ["Rupee", "Dollar", "Euro", "Yen"] },
  { question: "Color of Indian flag bottom stripe?", answer: "Green", options: ["Green", "Orange", "White", "Blue"] },
  { question: "What do we call a baby dog?", answer: "Puppy", options: ["Puppy", "Kitten", "Calf", "Cub"] },
  { question: "What do we call a baby cat?", answer: "Kitten", options: ["Kitten", "Puppy", "Calf", "Foal"] },
  { question: "What do we call a baby cow?", answer: "Calf", options: ["Calf", "Kitten", "Puppy", "Cub"] },
  { question: "How many days are there in a leap year?", answer: "366", options: ["366", "365", "364", "367"] },
  { question: "How many hours are there in a day?", answer: "24", options: ["24", "12", "20", "30"] },
  { question: "How many minutes are there in an hour?", answer: "60", options: ["60", "100", "30", "50"] },
  { question: "How many seconds are there in a minute?", answer: "60", options: ["60", "100", "30", "50"] },
  { question: "What color do you get by mixing blue and yellow?", answer: "Green", options: ["Green", "Purple", "Orange", "Pink"] },
  { question: "What color do you get by mixing red and yellow?", answer: "Orange", options: ["Orange", "Green", "Purple", "Brown"] },
  { question: "What color do you get by mixing red and blue?", answer: "Purple", options: ["Purple", "Green", "Orange", "Brown"] },
  { question: "What shape has 3 sides?", answer: "Triangle", options: ["Triangle", "Square", "Circle", "Rectangle"] },
  { question: "What shape has 4 equal sides?", answer: "Square", options: ["Square", "Triangle", "Circle", "Oval"] },
  { question: "What shape has no sides or corners?", answer: "Circle", options: ["Circle", "Square", "Triangle", "Rectangle"] },
  { question: "How many letters are there in the English alphabet?", answer: "26", options: ["26", "24", "25", "27"] },
  { question: "How many vowels are there in English?", answer: "5", options: ["5", "4", "6", "7"] },
  { question: "What is the first letter of the English alphabet?", answer: "A", options: ["A", "B", "Z", "C"] },
  { question: "What is the last letter of the English alphabet?", answer: "Z", options: ["Z", "A", "Y", "X"] },
  { question: "Which animal is called man's best friend?", answer: "Dog", options: ["Dog", "Cat", "Horse", "Cow"] },
  { question: "Which animal gives us milk?", answer: "Cow", options: ["Cow", "Dog", "Cat", "Hen"] },
  { question: "Which bird lays eggs we usually eat?", answer: "Hen", options: ["Hen", "Peacock", "Sparrow", "Crow"] },
  { question: "What do bees make?", answer: "Honey", options: ["Honey", "Milk", "Butter", "Silk"] },
  { question: "What do we call the place where we buy books?", answer: "Bookstore", options: ["Bookstore", "Bakery", "Pharmacy", "Bank"] },
  { question: "What do we call the place where we buy medicine?", answer: "Pharmacy", options: ["Pharmacy", "Bookstore", "Bakery", "Bank"] },
  { question: "What do we call the place where doctors treat sick people?", answer: "Hospital", options: ["Hospital", "School", "Bank", "Market"] },
  { question: "What do we call the place where we learn?", answer: "School", options: ["School", "Hospital", "Bank", "Market"] },
  { question: "What do we call a person who teaches us?", answer: "Teacher", options: ["Teacher", "Doctor", "Driver", "Farmer"] },
  { question: "What do we call a person who treats sick people?", answer: "Doctor", options: ["Doctor", "Teacher", "Driver", "Farmer"] },
  { question: "What do we call a person who grows crops?", answer: "Farmer", options: ["Farmer", "Doctor", "Teacher", "Driver"] },
  { question: "What do we call a person who flies a plane?", answer: "Pilot", options: ["Pilot", "Driver", "Sailor", "Farmer"] },
  { question: "What do we call a person who fights fires?", answer: "Firefighter", options: ["Firefighter", "Police officer", "Doctor", "Farmer"] },
  { question: "What do we call a person who catches criminals?", answer: "Police officer", options: ["Police officer", "Firefighter", "Doctor", "Farmer"] },
  { question: "How many days are there in a week?", answer: "7", options: ["7", "5", "6", "8"] },
  { question: "How many months are there in a year?", answer: "12", options: ["12", "10", "11", "13"] },
  { question: "How many weeks are there in a year approximately?", answer: "52", options: ["52", "48", "50", "60"] },
  { question: "What is the first day of the week (as per calendar)?", answer: "Sunday", options: ["Sunday", "Monday", "Saturday", "Friday"] },
  { question: "What is the day after Friday?", answer: "Saturday", options: ["Saturday", "Sunday", "Thursday", "Monday"] },
  { question: "How many fingers do you have on both hands?", answer: "10", options: ["10", "8", "12", "5"] },
  { question: "How many toes do you have on both feet?", answer: "10", options: ["10", "8", "12", "5"] },
  { question: "Which part of the body do we use to see?", answer: "Eyes", options: ["Eyes", "Ears", "Nose", "Mouth"] },
  { question: "Which part of the body do we use to hear?", answer: "Ears", options: ["Ears", "Eyes", "Nose", "Mouth"] },
  { question: "Which part of the body do we use to smell?", answer: "Nose", options: ["Nose", "Eyes", "Ears", "Mouth"] },
  { question: "Which part of the body do we use to taste?", answer: "Tongue", options: ["Tongue", "Nose", "Ears", "Eyes"] },
  { question: "What do we use to write on paper?", answer: "Pen", options: ["Pen", "Spoon", "Fork", "Comb"] },
  { question: "What do we use to cut paper?", answer: "Scissors", options: ["Scissors", "Pen", "Spoon", "Comb"] },
  { question: "What do we use to eat food with in most Indian homes?", answer: "Hand or spoon", options: ["Hand or spoon", "Scissors", "Comb", "Brush"] },
  { question: "What is our national flower?", answer: "Lotus", options: ["Lotus", "Rose", "Sunflower", "Marigold"] },
  { question: "What is our national animal?", answer: "Tiger", options: ["Tiger", "Lion", "Elephant", "Peacock"] },
  { question: "What is our national bird?", answer: "Peacock", options: ["Peacock", "Parrot", "Sparrow", "Eagle"] },
  { question: "What is our national fruit?", answer: "Mango", options: ["Mango", "Banana", "Apple", "Grapes"] },
  { question: "What is our national tree?", answer: "Banyan", options: ["Banyan", "Neem", "Peepal", "Mango"] },
  { question: "What is our national sport (traditionally recognized)?", answer: "Hockey", options: ["Hockey", "Cricket", "Football", "Kabaddi"] },
  { question: "What do we call our country's song that we sing with pride?", answer: "National Anthem", options: ["National Anthem", "National Song", "Prayer", "Poem"] },
  { question: "What colors are on the Indian flag?", answer: "Saffron, White, Green", options: ["Saffron, White, Green", "Red, White, Blue", "Red, Yellow, Green", "Blue, White, Red"] },
  { question: "What is at the center of the Indian flag?", answer: "Ashoka Chakra", options: ["Ashoka Chakra", "Star", "Sun", "Moon"] },
  { question: "How many spokes does the Ashoka Chakra have?", answer: "24", options: ["24", "12", "20", "30"] },
  { question: "Who is the Father of our Nation?", answer: "Mahatma Gandhi", options: ["Mahatma Gandhi", "Jawaharlal Nehru", "Subhas Chandra Bose", "Sardar Patel"] },
  { question: "On which day do we celebrate Independence Day?", answer: "15 August", options: ["15 August", "26 January", "2 October", "14 November"] },
  { question: "On which day do we celebrate Republic Day?", answer: "26 January", options: ["26 January", "15 August", "2 October", "14 November"] },
  { question: "On which day was Mahatma Gandhi born?", answer: "2 October", options: ["2 October", "15 August", "26 January", "14 November"] },
  { question: "On which day do we celebrate Children's Day in India?", answer: "14 November", options: ["14 November", "15 August", "26 January", "5 September"] },
  { question: "What season comes after summer in India?", answer: "Monsoon", options: ["Monsoon", "Winter", "Spring", "Autumn"] },
  { question: "What do plants need to grow, besides water and sunlight?", answer: "Air", options: ["Air", "Sand", "Salt", "Plastic"] },
  { question: "What do we call baby plants that just started growing?", answer: "Seedling", options: ["Seedling", "Sapling", "Sprout", "Bud"] },
  { question: "What is the source of light and heat for the Earth?", answer: "The Sun", options: ["The Sun", "The Moon", "Stars", "Clouds"] },
  { question: "What shape is a ball?", answer: "Sphere", options: ["Sphere", "Cube", "Cone", "Cylinder"] },
  { question: "What do we call the sound a dog makes?", answer: "Bark", options: ["Bark", "Meow", "Moo", "Neigh"] },
  { question: "What do we call the sound a cat makes?", answer: "Meow", options: ["Meow", "Bark", "Moo", "Neigh"] },
  { question: "What do we call the sound a cow makes?", answer: "Moo", options: ["Moo", "Bark", "Meow", "Neigh"] },
  { question: "What do we call the sound a lion makes?", answer: "Roar", options: ["Roar", "Bark", "Moo", "Chirp"] },
  { question: "What number comes after 9?", answer: "10", options: ["10", "11", "8", "12"] },
  { question: "What number comes before 1?", answer: "0", options: ["0", "2", "-1", "10"] },
  { question: "How many zeros are there in 100?", answer: "2", options: ["2", "1", "3", "4"] },
  { question: "What is 5 + 5?", answer: "10", options: ["10", "9", "11", "15"] },
  { question: "What is 10 - 5?", answer: "5", options: ["5", "4", "6", "10"] },
  { question: "What is half of 10?", answer: "5", options: ["5", "4", "6", "2"] },
  { question: "What do we call two of the same thing?", answer: "Pair", options: ["Pair", "Dozen", "Trio", "Single"] },
  { question: "How many items are there in a dozen?", answer: "12", options: ["12", "10", "6", "20"] },
  { question: "What do we call a group of 100 years?", answer: "Century", options: ["Century", "Decade", "Millennium", "Era"] },
  { question: "What do we call a group of 10 years?", answer: "Decade", options: ["Decade", "Century", "Millennium", "Era"] },





]);
