/* ============================================================
   🌍  GK — Class 5
   ------------------------------------------------------------
   HOW TO EDIT THIS FILE
   • Each { ... } line below is ONE question.
   • Keep this exact shape:
       { question: "your question?", answer: "Correct", options: ["Correct","B","C","D"] }
   • RULES:
       - Give exactly 4 options.
       - The "answer" text must EXACTLY match one of the 4 options.
       - Wrap text in "double quotes". If your text has a " inside it,
         write it as \" (a backslash then a quote).
   • Add or delete question lines freely.
   • Save the file, then refresh the quiz page — changes appear instantly.
   ============================================================ */
registerQuiz("gk", 5, [
  { question: "First President of India?", answer: "Rajendra Prasad", options: ["Rajendra Prasad", "Nehru", "Radhakrishnan", "APJ Kalam"] },
  { question: "Author of Indian National Anthem?", answer: "Tagore", options: ["Tagore", "Bankim Chandra", "Iqbal", "Nehru"] },
  { question: "Author of Vande Mataram?", answer: "Bankim Chandra", options: ["Bankim Chandra", "Tagore", "Iqbal", "Nehru"] },
  { question: "National anthem first sung in?", answer: "1911", options: ["1911", "1947", "1950", "1905"] },
  { question: "Author of Ramayana?", answer: "Valmiki", options: ["Valmiki", "Vyasa", "Tulsidas", "Kalidas"] },
  { question: "Author of Mahabharata?", answer: "Vyasa", options: ["Vyasa", "Valmiki", "Tulsidas", "Kalidas"] },
  { question: "Founder of Mauryan empire?", answer: "Chandragupta Maurya", options: ["Chandragupta Maurya", "Ashoka", "Bindusara", "Chanakya"] },
  { question: "Greatest Mauryan emperor?", answer: "Ashoka", options: ["Ashoka", "Chandragupta", "Bindusara", "Bimbisara"] },
  { question: "Founder of Mughal empire?", answer: "Babur", options: ["Babur", "Akbar", "Aurangzeb", "Humayun"] },
  { question: "Greatest Mughal emperor?", answer: "Akbar", options: ["Akbar", "Babur", "Aurangzeb", "Shah Jahan"] },
  { question: "Light travels fastest in?", answer: "Vacuum", options: ["Vacuum", "Air", "Water", "Glass"] },
  { question: "Sound travels fastest in?", answer: "Solid", options: ["Solid", "Liquid", "Gas", "Vacuum"] },
  { question: "Chemical symbol of water?", answer: "H2O", options: ["H2O", "CO2", "O2", "H2"] },
  { question: "Chemical symbol of gold?", answer: "Au", options: ["Au", "Ag", "Go", "Gd"] },
  { question: "Chemical symbol of silver?", answer: "Ag", options: ["Ag", "Au", "Si", "Sl"] },
  { question: "Largest organ of human body?", answer: "Skin", options: ["Skin", "Liver", "Heart", "Brain"] },
  { question: "Pumps blood in body?", answer: "Heart", options: ["Heart", "Lungs", "Liver", "Kidney"] },
  { question: "Days in a leap year?", answer: "366", options: ["366", "365", "364", "367"] },
  { question: "E=mc² was given by?", answer: "Einstein", options: ["Einstein", "Newton", "Bohr", "Curie"] },
  { question: "Who wrote 'Discovery of India'?", answer: "Nehru", options: ["Nehru", "Gandhi", "Tagore", "Bose"] },
  { question: "Who was the second President of India?", answer: "Sarvepalli Radhakrishnan", options: ["Sarvepalli Radhakrishnan", "Rajendra Prasad", "Zakir Husain", "VV Giri"] },
  { question: "Who was India's first woman President?", answer: "Pratibha Patil", options: ["Pratibha Patil", "Indira Gandhi", "Droupadi Murmu", "Sarojini Naidu"] },
  { question: "Who is India's current form of government headed by, ceremonially?", answer: "President", options: ["President", "Prime Minister", "Chief Justice", "Speaker"] },
  { question: "Who holds executive power and heads the government in India?", answer: "Prime Minister", options: ["Prime Minister", "President", "Chief Justice", "Speaker"] },
  { question: "Who is the head of the Indian judiciary?", answer: "Chief Justice of India", options: ["Chief Justice of India", "President", "Prime Minister", "Speaker"] },
  { question: "Who presides over the Lok Sabha in India?", answer: "Speaker", options: ["Speaker", "President", "Prime Minister", "Chief Justice"] },
  { question: "What are the two houses of the Indian Parliament called?", answer: "Lok Sabha and Rajya Sabha", options: ["Lok Sabha and Rajya Sabha", "Senate and Congress", "Commons and Lords", "Assembly and Council"] },
  { question: "Which house of Parliament is known as the 'House of the People'?", answer: "Lok Sabha", options: ["Lok Sabha", "Rajya Sabha", "Vidhan Sabha", "Vidhan Parishad"] },
  { question: "Which house of Parliament is known as the 'Council of States'?", answer: "Rajya Sabha", options: ["Rajya Sabha", "Lok Sabha", "Vidhan Sabha", "Vidhan Parishad"] },
  { question: "In which year was the Indian Constitution adopted?", answer: "1949", options: ["1949", "1947", "1950", "1952"] },
  { question: "On which date did the Indian Constitution come into effect?", answer: "26 January 1950", options: ["26 January 1950", "15 August 1947", "26 November 1949", "2 October 1950"] },
  { question: "Who is known as the 'Father of the Indian Constitution'?", answer: "Dr. B.R. Ambedkar", options: ["Dr. B.R. Ambedkar", "Mahatma Gandhi", "Jawaharlal Nehru", "Sardar Patel"] },
  { question: "Who was the chairman of the Constitution Drafting Committee?", answer: "Dr. B.R. Ambedkar", options: ["Dr. B.R. Ambedkar", "Rajendra Prasad", "Jawaharlal Nehru", "Sardar Patel"] },
  { question: "In which year did India gain independence from British rule?", answer: "1947", options: ["1947", "1945", "1950", "1857"] },
  { question: "Which event in 1857 is called India's First War of Independence?", answer: "Sepoy Mutiny", options: ["Sepoy Mutiny", "Jallianwala Bagh massacre", "Salt March", "Quit India Movement"] },
  { question: "Who led the Salt March (Dandi March) in 1930?", answer: "Mahatma Gandhi", options: ["Mahatma Gandhi", "Jawaharlal Nehru", "Subhas Chandra Bose", "Sardar Patel"] },
  { question: "What year did the Jallianwala Bagh massacre take place?", answer: "1919", options: ["1919", "1930", "1942", "1857"] },
  { question: "Who founded the Indian National Army (Azad Hind Fauj)?", answer: "Subhas Chandra Bose", options: ["Subhas Chandra Bose", "Bhagat Singh", "Mahatma Gandhi", "Chandrashekhar Azad"] },
  { question: "Which freedom fighter is known for the slogan 'Inquilab Zindabad'?", answer: "Bhagat Singh", options: ["Bhagat Singh", "Mahatma Gandhi", "Subhas Chandra Bose", "Lal Bahadur Shastri"] },
  { question: "Which movement did Mahatma Gandhi launch in 1942 asking the British to leave?", answer: "Quit India Movement", options: ["Quit India Movement", "Non-Cooperation Movement", "Civil Disobedience Movement", "Salt March"] },
  { question: "Which Indian leader gave the slogan 'Jai Jawan Jai Kisan'?", answer: "Lal Bahadur Shastri", options: ["Lal Bahadur Shastri", "Mahatma Gandhi", "Jawaharlal Nehru", "Indira Gandhi"] },
  { question: "Who was India's Prime Minister during the 1971 war with Pakistan?", answer: "Indira Gandhi", options: ["Indira Gandhi", "Jawaharlal Nehru", "Lal Bahadur Shastri", "Morarji Desai"] },
  { question: "Which new country was formed after the 1971 war, previously East Pakistan?", answer: "Bangladesh", options: ["Bangladesh", "Sri Lanka", "Nepal", "Myanmar"] },
  { question: "Who founded the Mauryan Empire?", answer: "Chandragupta Maurya", options: ["Chandragupta Maurya", "Ashoka", "Bimbisara", "Chanakya"] },
  { question: "Who was Chandragupta Maurya's chief advisor and strategist?", answer: "Chanakya (Kautilya)", options: ["Chanakya (Kautilya)", "Ashoka", "Bindusara", "Vishnugupta's teacher"] },
  { question: "Which Mauryan emperor embraced Buddhism after the Kalinga War?", answer: "Ashoka", options: ["Ashoka", "Chandragupta Maurya", "Bindusara", "Samudragupta"] },
  { question: "Who founded the Gupta Empire?", answer: "Sri Gupta / Chandragupta I", options: ["Sri Gupta / Chandragupta I", "Chandragupta Maurya", "Samudragupta", "Ashoka"] },
  { question: "Which Gupta emperor is called the 'Napoleon of India' for his conquests?", answer: "Samudragupta", options: ["Samudragupta", "Chandragupta II", "Ashoka", "Chandragupta Maurya"] },
  { question: "Who founded the Mughal Empire in India?", answer: "Babur", options: ["Babur", "Akbar", "Humayun", "Aurangzeb"] },
  { question: "Which Mughal emperor is known as 'Akbar the Great'?", answer: "Akbar", options: ["Akbar", "Babur", "Humayun", "Jahangir"] },
  { question: "Which Mughal emperor built the Red Fort in Delhi?", answer: "Shah Jahan", options: ["Shah Jahan", "Akbar", "Babur", "Aurangzeb"] },
  { question: "Who was the last Mughal emperor of India?", answer: "Bahadur Shah Zafar", options: ["Bahadur Shah Zafar", "Aurangzeb", "Shah Jahan", "Akbar"] },
  { question: "Which dynasty ruled the Vijayanagara Empire's capital famously known for ruins today?", answer: "Vijayanagara Empire (Hampi)", options: ["Vijayanagara Empire (Hampi)", "Chola Empire", "Maratha Empire", "Mughal Empire"] },
  { question: "Who founded the Maratha Empire?", answer: "Chhatrapati Shivaji Maharaj", options: ["Chhatrapati Shivaji Maharaj", "Bajirao I", "Sambhaji", "Aurangzeb"] },
  { question: "Which ancient Indian university was a famous center of learning, now in ruins in Bihar?", answer: "Nalanda University", options: ["Nalanda University", "Takshashila University", "Vikramshila University", "Somapura University"] },
  { question: "Which ancient university is considered the world's oldest, located in ancient India (now Pakistan)?", answer: "Takshashila (Taxila)", options: ["Takshashila (Taxila)", "Nalanda", "Vikramshila", "Somapura"] },
  { question: "Who wrote the epic 'Ramayana'?", answer: "Valmiki", options: ["Valmiki", "Vyasa", "Kalidasa", "Tulsidas"] },
  { question: "Who wrote the epic 'Mahabharata'?", answer: "Ved Vyasa", options: ["Ved Vyasa", "Valmiki", "Kalidasa", "Tulsidas"] },
  { question: "Who wrote 'Ramcharitmanas', a version of Ramayana in Hindi?", answer: "Tulsidas", options: ["Tulsidas", "Valmiki", "Vyasa", "Kalidasa"] },
  { question: "Who wrote India's national song 'Vande Mataram' as part of a novel?", answer: "Bankim Chandra Chattopadhyay", options: ["Bankim Chandra Chattopadhyay", "Rabindranath Tagore", "Premchand", "Sarat Chandra"] },
  { question: "Which Indian author wrote 'Discovery of India'?", answer: "Jawaharlal Nehru", options: ["Jawaharlal Nehru", "Mahatma Gandhi", "Rabindranath Tagore", "Sardar Patel"] },
  { question: "Which book did Mahatma Gandhi write about his life?", answer: "The Story of My Experiments with Truth", options: ["The Story of My Experiments with Truth", "Discovery of India", "Gitanjali", "Godaan"] },
  { question: "Which poetry collection by Tagore won him the Nobel Prize?", answer: "Gitanjali", options: ["Gitanjali", "Discovery of India", "Godaan", "Kamayani"] },
  { question: "Which chemical symbol represents Gold?", answer: "Au", options: ["Au", "Ag", "Fe", "Cu"] },
  { question: "Which chemical symbol represents Silver?", answer: "Ag", options: ["Ag", "Au", "Fe", "Cu"] },
  { question: "Which chemical symbol represents Iron?", answer: "Fe", options: ["Fe", "Au", "Ag", "Cu"] },
  { question: "Which chemical symbol represents Sodium?", answer: "Na", options: ["Na", "K", "Ca", "Mg"] },
  { question: "Which chemical symbol represents Potassium?", answer: "K", options: ["K", "Na", "Ca", "Mg"] },
  { question: "Which chemical symbol represents Copper?", answer: "Cu", options: ["Cu", "Au", "Ag", "Fe"] },
  { question: "Which chemical symbol represents Oxygen?", answer: "O", options: ["O", "H", "N", "C"] },
  { question: "Which chemical symbol represents Hydrogen?", answer: "H", options: ["H", "O", "N", "C"] },
  { question: "Which chemical symbol represents Carbon?", answer: "C", options: ["C", "O", "H", "N"] },
  { question: "Which is the lightest metal known?", answer: "Lithium", options: ["Lithium", "Aluminium", "Sodium", "Magnesium"] },
  { question: "Which is the hardest natural substance on Earth?", answer: "Diamond", options: ["Diamond", "Gold", "Iron", "Quartz"] },
  { question: "What is the chemical name for common table salt?", answer: "Sodium chloride", options: ["Sodium chloride", "Sodium bicarbonate", "Potassium chloride", "Calcium carbonate"] },
  { question: "What is the formula E=mc² famous for describing?", answer: "Relation between mass and energy", options: ["Relation between mass and energy", "Speed of sound", "Force and acceleration", "Gravity"] },
  { question: "Who proposed the theory of evolution by natural selection?", answer: "Charles Darwin", options: ["Charles Darwin", "Gregor Mendel", "Louis Pasteur", "Isaac Newton"] },
  { question: "Who is known as the father of genetics for his pea plant experiments?", answer: "Gregor Mendel", options: ["Gregor Mendel", "Charles Darwin", "Louis Pasteur", "Alexander Fleming"] },
  { question: "Who discovered penicillin, the first antibiotic?", answer: "Alexander Fleming", options: ["Alexander Fleming", "Louis Pasteur", "Gregor Mendel", "Edward Jenner"] },
  { question: "Who developed the smallpox vaccine?", answer: "Edward Jenner", options: ["Edward Jenner", "Alexander Fleming", "Louis Pasteur", "Jonas Salk"] },
  { question: "Who developed the polio vaccine?", answer: "Jonas Salk", options: ["Jonas Salk", "Edward Jenner", "Alexander Fleming", "Louis Pasteur"] },
  { question: "Who is known as the father of the periodic table?", answer: "Dmitri Mendeleev", options: ["Dmitri Mendeleev", "Antoine Lavoisier", "John Dalton", "Marie Curie"] },
  { question: "Who discovered radioactivity and won two Nobel Prizes?", answer: "Marie Curie", options: ["Marie Curie", "Albert Einstein", "Isaac Newton", "Niels Bohr"] },
  { question: "Which two elements did Marie Curie discover?", answer: "Radium and Polonium", options: ["Radium and Polonium", "Uranium and Thorium", "Helium and Neon", "Sodium and Potassium"] },
  { question: "Who proposed the laws of motion and universal gravitation?", answer: "Isaac Newton", options: ["Isaac Newton", "Albert Einstein", "Galileo Galilei", "Johannes Kepler"] },
  { question: "Who is credited with inventing the light bulb's practical design and many other inventions?", answer: "Thomas Edison", options: ["Thomas Edison", "Nikola Tesla", "Alexander Graham Bell", "James Watt"] },
  { question: "Who developed alternating current (AC) electricity systems?", answer: "Nikola Tesla", options: ["Nikola Tesla", "Thomas Edison", "James Watt", "Michael Faraday"] },
  { question: "Who discovered electromagnetic induction?", answer: "Michael Faraday", options: ["Michael Faraday", "Nikola Tesla", "James Watt", "Isaac Newton"] },
  { question: "Which scientist is famous for the equation describing the photoelectric effect?", answer: "Albert Einstein", options: ["Albert Einstein", "Isaac Newton", "Niels Bohr", "Max Planck"] },
  { question: "Who proposed the model of the atom with a nucleus and electron shells?", answer: "Niels Bohr", options: ["Niels Bohr", "Albert Einstein", "Isaac Newton", "John Dalton"] },
  { question: "Who is known as the father of modern chemistry?", answer: "Antoine Lavoisier", options: ["Antoine Lavoisier", "Dmitri Mendeleev", "John Dalton", "Marie Curie"] },
  { question: "Who proposed the modern atomic theory of matter?", answer: "John Dalton", options: ["John Dalton", "Antoine Lavoisier", "Dmitri Mendeleev", "Niels Bohr"] },
  { question: "Which prize is awarded for outstanding work in economics, sciences, literature, and peace?", answer: "Nobel Prize", options: ["Nobel Prize", "Pulitzer Prize", "Booker Prize", "Grammy Award"] },
  { question: "Which prize honors outstanding achievement in American journalism and literature?", answer: "Pulitzer Prize", options: ["Pulitzer Prize", "Nobel Prize", "Booker Prize", "Man Booker International Prize"] },
  { question: "Which literary prize is given for the best novel written in English?", answer: "Booker Prize", options: ["Booker Prize", "Pulitzer Prize", "Nobel Prize", "Grammy Award"] },
  { question: "Which Indian author won the Booker Prize for 'The God of Small Things'?", answer: "Arundhati Roy", options: ["Arundhati Roy", "Kiran Desai", "Salman Rushdie", "Vikram Seth"] },
  { question: "What is the term for a government ruled by one person with absolute power?", answer: "Dictatorship", options: ["Dictatorship", "Democracy", "Monarchy", "Republic"] },
  { question: "What is the term for a government where citizens vote for their leaders?", answer: "Democracy", options: ["Democracy", "Dictatorship", "Monarchy", "Autocracy"] },
  { question: "What is the term for a government ruled by a king or queen?", answer: "Monarchy", options: ["Monarchy", "Democracy", "Dictatorship", "Republic"] },
  { question: "What is a country called where the head of state is elected, not a king?", answer: "Republic", options: ["Republic", "Monarchy", "Dictatorship", "Colony"] },
]);
