/* My Travel Map · lang.js
   English / Hindi: the Hindi dictionary and the T() translation helper. */
// ---- Language: English / हिंदी ----
let LANG=localStorage.getItem("myIndiaLangV2")==="hi"?"hi":"en";
const HI={
"🇮🇳 My Visiting Places in India":"🇮🇳 भारत में मेरी घूमी हुई जगहें",
"My Visiting Places in India":"भारत में मेरी घूमी हुई जगहें",
"Mark places you visited or dream of, colour in states, win badges, and share your travel map.":"घूमी हुई या सपनों की जगहें जोड़ें, राज्यों में रंग भरें, बैज जीतें और अपना यात्रा नक्शा शेयर करें।",
"Add a place":"जगह जोड़ें","Place / City / State":"जगह / शहर / राज्य",
"✅ Visited":"✅ घूम लिया","⭐ Wishlist":"⭐ विशलिस्ट","＋ Add Place":"＋ जगह जोड़ें",
"📷 Pins from my photos":"📷 मेरी फ़ोटो से पिन बनाएँ","🗺️ My progress":"🗺️ मेरी प्रगति",
"Show journey line on map":"नक्शे पर यात्रा की रेखा दिखाएँ","🧭 Where should I go next?":"🧭 अब कहाँ जाऊँ?",
"🧳 Plan wishlist trips":"🧳 विशलिस्ट की योजना","🧠 India quiz":"🧠 भारत क्विज़",
"Your name (shown on the picture)":"आपका नाम (तस्वीर पर दिखेगा)","⬇ Download PNG":"⬇ तस्वीर डाउनलोड","↺ Reset":"↺ रीसेट",
"Share my map":"मेरा नक्शा शेयर करें","Backup (move to another phone)":"बैकअप (दूसरे फ़ोन में ले जाएँ)",
"💾 Backup to file":"💾 फ़ाइल में बैकअप","📂 Restore from file":"📂 फ़ाइल से वापस लाएँ",
"Show on map":"नक्शे पर दिखाएँ","Show one year":"एक साल दिखाएँ","▶ Play my journey":"▶ मेरी यात्रा चलाएँ","⏹ Stop":"⏹ रोकें",
"e.g. Puri, Varanasi, Somnath":"जैसे पुरी, वाराणसी, सोमनाथ","e.g. Mayank":"जैसे मयंक",
"🪄 Category: pick for me":"🪄 श्रेणी: अपने आप चुनें",
"Temple":"मंदिर","Beach":"समुद्र तट","Hill station":"हिल स्टेशन","Fort & monument":"किला और स्मारक","Wildlife":"वन्यजीव","City & other":"शहर और अन्य",
"All":"सभी","❤️ Favourites":"❤️ पसंदीदा","All years":"सभी साल",
"🎉 Share my “{0} in Travel” card":"🎉 मेरा “{0} की यात्राएँ” कार्ड शेयर करें",
"{0}: {1} in Travel":"{0}: {1} की यात्राएँ","My {0} in Travel":"मेरी {0} की यात्राएँ",
"{0} of 28 states visited":"28 में से {0} राज्य घूमे","{0} of 8 union territories":"8 में से {0} केंद्र शासित प्रदेश",
"{0} km travelled":"{0} किमी का सफ़र",
"{0} place":"{0} जगह","{0} places":"{0} जगहें","{0} visited, {1} wishlist":"{0} घूमी, {1} विशलिस्ट","Showing {0} of {1} places":"{1} में से {0} जगहें दिख रही हैं",
"Uh-oh! Your browser storage is full. Try removing some of your own photos.":"अरे! ब्राउज़र की जगह भर गई है। अपनी कुछ फ़ोटो हटाकर देखें।",
"First Step":"पहला कदम","Add your first visited place":"अपनी पहली घूमी हुई जगह जोड़ें",
"High Five":"हाई फ़ाइव","Visit 5 places":"5 जगहें घूमें","10 Places!":"10 जगहें!","Visit 10 places":"10 जगहें घूमें",
"Travel Champ":"यात्रा चैंपियन","Visit 25 places":"25 जगहें घूमें",
"Mountain Lover":"पहाड़ प्रेमी","Visit 3 hill stations":"3 हिल स्टेशन घूमें","Beach Explorer":"समुद्र तट खोजी","Visit 3 beaches":"3 समुद्र तट घूमें",
"Temple Trail":"मंदिर यात्रा","Visit 3 temples":"3 मंदिर घूमें","Fort Hunter":"किला खोजी","Visit 3 forts or monuments":"3 किले या स्मारक घूमें",
"Jungle Buddy":"जंगल का दोस्त","Visit 2 wildlife places":"2 वन्यजीव जगहें घूमें",
"State Hopper":"राज्य घुमक्कड़","Visit 5 different states":"5 अलग-अलग राज्य घूमें","Bharat Darshan":"भारत दर्शन","Visit 15 different states":"15 अलग-अलग राज्य घूमें",
"Road Warrior":"सड़क का योद्धा","Travel 5,000 km":"5,000 किमी का सफ़र करें","Big Dreamer":"बड़े सपने वाला","Put 3 places on your wishlist":"विशलिस्ट में 3 जगहें जोड़ें",
"Memory Keeper":"यादों का रखवाला","Add a note or your own photo to 3 places":"3 जगहों पर नोट या अपनी फ़ोटो जोड़ें",
"Quiz Whiz":"क्विज़ चैंपियन","Get a perfect score in the quiz":"भारत क्विज़ में पूरे अंक लाएँ",
"Star Critic":"सितारा समीक्षक","Give stars to 5 places":"5 जगहों को स्टार दें",
"You won a new badge: {0}!":"आपने नया बैज जीता: {0}!","Woohoo! 🥳":"वाह! 🥳",
"{0} — you got it! {1}.":"{0} — यह आपको मिल गया! {1}।","{0} — how to win: {1}.":"{0} — कैसे जीतें: {1}।",
"Yes yes! 🎉":"हाँ हाँ! 🎉","Nooo 🙈":"नहीं 🙈","Okie dokie! 👍":"ठीक है! 👍","Cancel":"रद्द करें",
"Searching…":"खोज रहे हैं…","No India place found":"भारत में ऐसी जगह नहीं मिली","Try city, temple, tourist place or state name":"शहर, मंदिर, पर्यटन स्थल या राज्य का नाम लिखकर देखें",
"Oopsie! Type a place name first!":"अरे! पहले जगह का नाम लिखें!","Uh-oh! That place is not in India!":"अरे! यह जगह भारत में नहीं है!",
"{0} is already on your map, silly!":"{0} तो पहले से आपके नक्शे पर है!",
"Please add your Groq API key in the GROQ_API_KEY constant in this HTML file.":"कृपया इस HTML फ़ाइल में GROQ_API_KEY की जगह अपनी Groq API key डालें।",
"Hmm, I could not find that place! Try picking one from the suggestions.":"यह जगह नहीं मिली! सुझावों में से कोई चुनकर देखें।",
"Bye-bye {0}? Really take it off the map?":"{0} को टाटा? सच में नक्शे से हटाना है?","Yes, bye-bye! 👋":"हाँ, टाटा! 👋","No, keep it! 💖":"नहीं, रहने दो! 💖",
"Your map is already empty! Add a place first.":"आपका नक्शा पहले से खाली है! पहले कोई जगह जोड़ें।",
"Whoa! Wipe ALL {0} places off the map and start fresh?":"अरे! क्या सभी {0} जगहें हटाकर नए सिरे से शुरू करें?","Yes, start over! 🔄":"हाँ, नए सिरे से! 🔄","Nooo, keep them! 🛑":"नहीं, रहने दो! 🛑",
"India":"भारत","Year I visited":"किस साल घूमे","My memory":"मेरी याद","What was the best part?":"सबसे अच्छा क्या लगा?","e.g. {0}":"जैसे {0}",
"My stars":"मेरे स्टार","📷 Use my own photo":"📷 अपनी फ़ोटो लगाएँ","↩ Use web photo":"↩ वेब फ़ोटो लगाएँ",
"✨ Tell me a fun fact!":"✨ मज़ेदार बात बताओ!","✨ Another fact!":"✨ एक और बात!","Thinking… 🤔":"सोच रहा हूँ… 🤔",
"Save 💾":"सेव करें 💾","Remove 🗑️":"हटाएँ 🗑️",
"Hmm, I could not open that photo. Try another one!":"यह फ़ोटो नहीं खुली। कोई दूसरी चुनें!",
"That year looks funny! Pick a year from 1950 to {0}.":"साल ठीक नहीं लग रहा! 1950 से {0} के बीच का साल चुनें।",
"I could not find a fact right now. Check your internet and try again!":"अभी कोई जानकारी नहीं मिली। इंटरनेट जाँचकर फिर कोशिश करें!",
"Where next?":"अब कहाँ?","Picked for you by Groq AI":"Groq AI ने आपके लिए चुना","Here are some ideas!":"ये रहे कुछ सुझाव!","Wow, you have been everywhere I know!":"वाह, आप तो हर जगह घूम चुके हैं!",
"A brand new state to colour in!":"रंग भरने के लिए एक नया राज्य!","Famous spot: {0}.":"मशहूर जगह: {0}।","⭐ Add":"⭐ जोड़ें","Added ✓":"जुड़ गया ✓",
"📍 Places List":"📍 जगहों की सूची","Visited":"घूम लिया","Wishlist":"विशलिस्ट","Badges":"बैज","⭐ My Top {0}":"⭐ मेरी टॉप {0}",
"My Visiting Places in India 🇮🇳 — {0} places!":"भारत में मेरी घूमी हुई जगहें 🇮🇳 — {0} जगहें!",
"Your map picture is saved and copied! Paste or attach it in {0}.":"नक्शे की तस्वीर सेव और कॉपी हो गई! इसे {0} में पेस्ट या अटैच करें।",
"Your map picture is saved! Attach it in {0}.":"नक्शे की तस्वीर सेव हो गई! इसे {0} में अटैच करें।",
"Add at least 2 visited places to play your journey!":"यात्रा चलाने के लिए कम से कम 2 घूमी हुई जगहें जोड़ें!",
"🎉 {0} places · {1} km!":"🎉 {0} जगहें · {1} किमी!",
"places":"जगहें","states & UTs":"राज्य और केंद्र शासित प्रदेश","km travelled":"किमी का सफ़र","memories":"यादें",
"⭐ Top picks: {0}":"⭐ सबसे पसंदीदा: {0}",
"Your {0} card is saved! Attach it in WhatsApp or Instagram.":"आपका {0} का कार्ड सेव हो गया! इसे WhatsApp या Instagram में अटैच करें।",
"Add a place first, then make a backup!":"पहले कोई जगह जोड़ें, फिर बैकअप बनाएँ!",
"Backup saved: {0} places with notes and photos. Send this file to your other phone and tap “Restore from file” there.":"बैकअप सेव हो गया: {0} जगहें, नोट और फ़ोटो के साथ। यह फ़ाइल दूसरे फ़ोन पर भेजें और वहाँ “फ़ाइल से वापस लाएँ” दबाएँ।",
"Hmm, that is not a backup file from this map.":"यह इस नक्शे की बैकअप फ़ाइल नहीं लगती।",
"This backup has {0} places and you already have {1} here. What should I do?":"इस बैकअप में {0} जगहें हैं और यहाँ पहले से {1} हैं। क्या करूँ?",
"Add to my map ➕":"मेरे नक्शे में जोड़ें ➕","Replace my map 🔄":"मेरा नक्शा बदल दें 🔄",
"All done! {0} places are on your map now.":"हो गया! अब आपके नक्शे पर {0} जगहें हैं।",
"Your wishlist is empty! Add a ⭐ Wishlist place first.":"आपकी विशलिस्ट खाली है! पहले कोई ⭐ विशलिस्ट जगह जोड़ें।",
"Wishlist trip planner":"विशलिस्ट यात्रा योजना","🔄 Plan again":"🔄 फिर से योजना बनाएँ",
"Planned for you by Groq AI":"Groq AI ने आपके लिए योजना बनाई","Built-in ideas. Add your Groq API key for smarter plans.":"ये सामान्य सुझाव हैं। बेहतर योजना के लिए अपनी Groq API key जोड़ें।",
"Built-in ideas (Groq did not answer).":"ये सामान्य सुझाव हैं (Groq से जवाब नहीं मिला)।",
"🌤️ Best time: {0}":"🌤️ सबसे अच्छा समय: {0}","📅 Days needed: {0}":"📅 कितने दिन: {0}","➕ Combine with: {0}":"➕ साथ में घूमें: {0}",
"June to September":"जून से सितंबर","March to June":"मार्च से जून","November to February":"नवंबर से फ़रवरी","November to April":"नवंबर से अप्रैल","October to March":"अक्टूबर से मार्च",
"Only about {0} km away":"सिर्फ़ लगभग {0} किमी दूर",
"Visit a place first! The quiz is about places you have visited.":"पहले कोई जगह घूमें! क्विज़ आपकी घूमी हुई जगहों पर है।",
"India quiz":"भारत क्विज़","Making your questions… 🤔":"आपके सवाल बन रहे हैं… 🤔","Question {0} of {1}":"सवाल {0} / {1}",
"✅ Correct!":"✅ सही!","❌ Not quite!":"❌ सही नहीं!","Next ➡️":"अगला ➡️","See my score 🏁":"मेरा स्कोर देखें 🏁",
"You scored {0} out of {1}!":"आपके {1} में से {0} अंक आए!","Perfect score! You win the Quiz Whiz badge!":"पूरे अंक! आपने क्विज़ चैंपियन बैज जीत लिया!",
"Good try! Get every answer right to win the Quiz Whiz badge.":"अच्छी कोशिश! क्विज़ चैंपियन बैज जीतने के लिए सभी जवाब सही दें।","Play again 🔁":"फिर से खेलें 🔁",
"Which state or union territory is {0} in?":"{0} किस राज्य या केंद्र शासित प्रदेश में है?","{0} is in {1}.":"{0}, {1} में है।",
"Which of these places is in {0}?":"इनमें से कौन-सी जगह {0} में है?",
"Which place is farther north?":"कौन-सी जगह ज़्यादा उत्तर में है?","{0} is farther north than {1}.":"{0}, {1} से ज़्यादा उत्तर में है।",
"In which year did you visit {0}?":"आप {0} किस साल घूमे थे?","You visited {0} in {1}.":"आप {0} साल {1} में घूमे थे।",
"About how far is {0} from {1} in a straight line?":"{0} से {1} सीधी रेखा में लगभग कितनी दूर है?","{0} km":"{0} किमी","It is about {0} km.":"यह लगभग {0} किमी है।",
"How many states have you visited so far?":"आप अब तक कितने राज्य घूम चुके हैं?","You have visited {0} states.":"आप {0} राज्य घूम चुके हैं।",
"Pins from my photos":"मेरी फ़ोटो से पिन","Reading photo {0} of {1}…":"फ़ोटो {0} / {1} पढ़ रहे हैं…","Finding place names…":"जगहों के नाम खोज रहे हैं…",
"Photo spot {0}":"फ़ोटो की जगह {0}",
"Found {0} places in {1} photos.":"{1} फ़ोटो में {0} जगहें मिलीं।","{0} photos had no location saved and were skipped.":"{0} फ़ोटो में लोकेशन नहीं थी, इसलिए छोड़ दी गईं।",
"{0} photos were taken outside India and were skipped.":"{0} फ़ोटो भारत के बाहर की थीं, इसलिए छोड़ दी गईं।",
"None of these photos has a location saved inside it. Tip: choose the original camera photos (photos received on WhatsApp lose their location), and on Android pick them through “Files” or “Browse”.":"इनमें से किसी फ़ोटो में लोकेशन सेव नहीं है। सुझाव: कैमरे की असली फ़ोटो चुनें (WhatsApp से आई फ़ोटो में लोकेशन नहीं रहती), और Android पर इन्हें “Files” या “Browse” से चुनें।",
"{0} photos":"{0} फ़ोटो","New pin":"नया पिन","Already on your map: photo will be added":"पहले से नक्शे पर है: फ़ोटो जुड़ जाएगी",
"Add pins 📍":"पिन जोड़ें 📍",
"Loading the world map…":"दुनिया का नक्शा लोड हो रहा है…","I could not load the world map. Check your internet and try again.":"दुनिया का नक्शा लोड नहीं हुआ। इंटरनेट जाँचकर फिर कोशिश करें।",
"In {0}":"{0} में",
"Near {0}":"{0} के आसपास",

"Add your first place":"अपनी पहली जगह जोड़ें",
"Type a place name here and tap ＋. To add many at once, separate them with commas, like: Jaipur, Agra, Goa.":"यहाँ जगह का नाम लिखें और ＋ दबाएँ। एक साथ कई जोड़ने के लिए कॉमा लगाएँ, जैसे: Jaipur, Agra, Goa।",
"Visited or wishlist":"घूम लिया या विशलिस्ट",
"Pick Visited for places you have been to, or Wishlist for places you dream of. The category is chosen for you, or pick your own.":"जहाँ जा चुके हैं उनके लिए 'घूम लिया' चुनें, और सपनों की जगहों के लिए 'विशलिस्ट'। श्रेणी अपने आप चुन ली जाती है, या आप खुद चुनें।",
"Your map":"आपका नक्शा",
"Pins appear here and each visited state gets coloured in. Pinch to zoom, drag to move, and tap a pin to add the year, a photo, stars and a memory.":"पिन यहाँ दिखते हैं और हर घूमे हुए राज्य में रंग भर जाता है। ज़ूम के लिए दो उँगलियाँ फैलाएँ, खिसकाने के लिए खींचें, और साल, फ़ोटो, स्टार और याद जोड़ने के लिए पिन पर टैप करें।",
"India or World":"भारत या दुनिया",
"Switch between your India map and your World map. Your India places show on the World map too.":"अपने भारत और दुनिया के नक्शे के बीच बदलें। आपकी भारत की जगहें दुनिया के नक्शे पर भी दिखती हैं।",
"Play and share":"चलाएँ और शेयर करें",
"Watch your journey like a short film, share your map picture with friends, or tap 💡 for a fun fact about your places.":"अपनी यात्रा छोटी फ़िल्म की तरह देखें, नक्शे की तस्वीर दोस्तों को भेजें, या अपनी जगहों की मज़ेदार बात के लिए 💡 दबाएँ।",
"Everything else is here":"बाकी सब यहाँ है",
"Places is your list. Leaders has the leaderboard and friends groups. Explore has games, collections and your progress. More has backup and settings.":"'जगहें' आपकी सूची है। 'लीडरबोर्ड' में रैंकिंग और दोस्तों के ग्रुप हैं। 'खोजें' में खेल, संग्रह और आपकी प्रगति है। 'और' में बैकअप और सेटिंग हैं।",
"Back":"पीछे",
"Start exploring 🎉":"शुरू करें 🎉",
"❓ Show the quick guide":"❓ छोटी गाइड फिर दिखाएँ",

"🧭 Add nearby places I visited":"🧭 आसपास की घूमी हुई जगहें जोड़ें",
"Looking for places near {0}…":"{0} के आसपास की जगहें खोज रहे हैं…",
"I could not find more places near {0}.":"{0} के आसपास और जगहें नहीं मिलीं।",

"Tick the places you have also visited":"जो जगहें आपने भी घूमी हैं, उन पर निशान लगाएँ",
"Add ticked places ✅":"चुनी हुई जगहें जोड़ें ✅",
"Skip":"छोड़ें",
"Been near {0} too?":"क्या {0} के आसपास भी घूमे हैं?",
"Add {0} places ✅":"{0} जगहें जोड़ें ✅",
"Less than 1 km away":"1 किमी से भी पास",
"{0} km away":"{0} किमी दूर",
"Suggest nearby places after I add one":"जगह जोड़ने के बाद आसपास की जगहें सुझाएँ",

"Open in your browser":"अपने ब्राउज़र में खोलें",
"Google sign-in does not work inside the small browser of WhatsApp, Instagram and similar apps. Open this page in Safari or Chrome and sign in there.":"WhatsApp, Instagram जैसे ऐप के अंदर वाले छोटे ब्राउज़र में Google साइन इन नहीं चलता। यह पेज Safari या Chrome में खोलें और वहाँ साइन इन करें।",
"How: tap the ⋯ or share button on this screen and choose “Open in Safari” or “Open in Chrome”.":"कैसे: इस स्क्रीन पर ⋯ या शेयर बटन दबाएँ और “Open in Safari” या “Open in Chrome” चुनें।",
"Open in browser 🌐":"ब्राउज़र में खोलें 🌐",
"Copy the link 🔗":"लिंक कॉपी करें 🔗",
"Link copied! Now open Safari or Chrome and paste it in the address bar.":"लिंक कॉपी हो गया! अब Safari या Chrome खोलें और इसे पते की पट्टी में पेस्ट करें।",
"You opened this inside another app. Google sign-in may not work here: open the page in Safari or Chrome.":"आपने इसे किसी दूसरे ऐप के अंदर खोला है। यहाँ Google साइन इन शायद न चले: पेज को Safari या Chrome में खोलें।",
"Trouble signing in?":"साइन इन में दिक्कत?",

"{0} visited {1}":"{0} ने {1} घूमा",
"{0} coloured in {1}":"{0} ने {1} में रंग भरा",
"{0} is now: {1}":"{0} अब हैं: {1}",
"{0} completed the collection {1}":"{0} ने संग्रह {1} पूरा किया",
"{0} scored {1} in the pin-drop challenge":"{0} ने पिन-ड्रॉप चुनौती में {1} अंक बनाए",
"{0} scored {1} in Guess the place":"{0} ने 'जगह पहचानो' में {1} अंक बनाए",
"{0} planned a group trip: {1}":"{0} ने ग्रुप यात्रा बनाई: {1}",
"{0} is joining the trip {1}":"{0} यात्रा {1} में शामिल हो रहे हैं",
"{0} scored {1} in the quiz about {2}":"{0} ने {2} वाले क्विज़ में {1} अंक बनाए",
"{0} min ago":"{0} मिनट पहले",
"{0} h ago":"{0} घंटे पहले",
"{0} d ago":"{0} दिन पहले",
"Today’s games":"आज के खेल",
"Nobody has played today. Be the first and your friends will see your score!":"आज अभी किसी ने नहीं खेला। सबसे पहले खेलें, आपका स्कोर दोस्तों को दिखेगा!",
"Group trips":"ग्रुप यात्राएँ",
"No trips yet. Plan one and see who is in!":"अभी कोई यात्रा नहीं। एक बनाएँ और देखें कौन साथ चलेगा!",
"planned by {0}":"{0} ने बनाई",
"Going ({0}): {1}":"जा रहे हैं ({0}): {1}",
"Delete":"हटाएँ",
"Delete the trip {0}?":"यात्रा {0} हटानी है?",
"I am out":"मैं नहीं जा रहा",
"I am in ✋":"मैं चलूँगा ✋",
"⭐ Add to my wishlist":"⭐ मेरी विशलिस्ट में जोड़ें",
"Join us on My Travel Map with group code {0}":"My Travel Map पर ग्रुप कोड {0} से हमारे साथ जुड़ें",
"➕ Plan a group trip":"➕ ग्रुप यात्रा बनाएँ",
"Friend activity":"दोस्तों की गतिविधि",
"Nothing yet. When your friends add places or play games, you will see it here.":"अभी कुछ नहीं। जब आपके दोस्त जगहें जोड़ेंगे या खेल खेलेंगे, तो यहाँ दिखेगा।",
"Copied! Paste it in WhatsApp or any chat.":"कॉपी हो गया! इसे WhatsApp या किसी भी चैट में पेस्ट करें।",
"Plan a group trip":"ग्रुप यात्रा बनाएँ",
"Trip name":"यात्रा का नाम",
"When (for example December 2026)":"कब (जैसे दिसंबर 2026)",
"Other places, with commas":"और जगहें, कॉमा लगाकर",
"Save and tell my friends 📣":"सेव करें और दोस्तों को बताएँ 📣",
"{0}’s trip":"{0} की यात्रा",
"Tip: places on your wishlist appear here to tick.":"सुझाव: आपकी विशलिस्ट की जगहें यहाँ चुनने के लिए दिखती हैं।",
"Give your trip a name first!":"पहले यात्रा का नाम लिखें!",
"{0} needs at least 2 visited places for a quiz.":"क्विज़ के लिए {0} की कम से कम 2 घूमी हुई जगहें चाहिए।",
"Which of these places has {0} visited?":"इनमें से {0} कौन-सी जगह घूम चुके हैं?",
"Yes":"हाँ",
"No":"नहीं",
"Has {0} been to {1}?":"क्या {0}, {1} गए हैं?",
"How many places has {0} visited?":"{0} कितनी जगहें घूम चुके हैं?",
"Which of these countries has {0} NOT visited?":"इनमें से {0} कौन-सा देश नहीं घूमे?",
"Which of these states has {0} NOT visited?":"इनमें से {0} कौन-सा राज्य नहीं घूमे?",
"How well do you know {0}?":"आप {0} को कितना जानते हैं?",
"best time {0}, {1} days":"सबसे अच्छा समय {0}, {1} दिन",
"combine with {0}":"साथ में {0}",
"My travel wishlist plans":"मेरी यात्रा विशलिस्ट की योजनाएँ",
"📤 Share my trip plans":"📤 मेरी यात्रा योजनाएँ शेयर करें",
"🧠 Quiz: how well do I know {0}?":"🧠 क्विज़: मैं {0} को कितना जानता हूँ?",

"Games and fun":"खेल और मज़ा",
"Pin-drop challenge":"पिन-ड्रॉप चुनौती",
"Guess the place":"जगह पहचानो",
"Surprise me":"मुझे चौंकाओ",
"My traveller type":"मेरा यात्री प्रकार",
"My travel in numbers":"आँकड़ों में मेरी यात्रा",
"My home town (draws a line from home to every place)":"मेरा घर का शहर (घर से हर जगह तक रेखा बनती है)",
"Set":"सेट करें",
"e.g. Jaipur":"जैसे जयपुर",
"Where is {0}? Tap the map!":"{0} कहाँ है? नक्शे पर टैप करें!",
"{0} km away · +{1} points":"{0} किमी दूर · +{1} अंक",
"Pin-drop score: {0} out of {1}! Your best: {2}.":"पिन-ड्रॉप स्कोर: {1} में से {0}! आपका सबसे अच्छा: {2}।",
"Finding photos… 🤔":"फ़ोटो खोज रहे हैं… 🤔",
"I could not load the photos. Check your internet and try again.":"फ़ोटो लोड नहीं हुईं। इंटरनेट जाँचकर फिर कोशिश करें।",
"Photo {0} of {1}":"फ़ोटो {0} / {1}",
"✅ Correct! +{0} points":"✅ सही! +{0} अंक",
"❌ It is {0}.":"❌ यह {0} है।",
"⭐ Add to wishlist":"⭐ विशलिस्ट में जोड़ें",
"🎲 Another":"🎲 कोई और",
"{0} is on your wishlist!":"{0} आपकी विशलिस्ट में जुड़ गया!",
"Mountain Soul":"पहाड़ों का दीवाना",
"You are happiest where the air is cool and the roads keep climbing.":"आपको वहीं सबसे अच्छा लगता है जहाँ हवा ठंडी हो और रास्ते ऊपर चढ़ते जाएँ।",
"Beach Lover":"समुद्र तट प्रेमी",
"Sand, waves and sunsets are your idea of a perfect trip.":"रेत, लहरें और डूबता सूरज: यही आपकी मनपसंद यात्रा है।",
"Temple Trailblazer":"मंदिरों का यात्री",
"You follow the sound of bells and the stories of old shrines.":"आप घंटियों की आवाज़ और पुराने मंदिरों की कहानियों के पीछे चलते हैं।",
"History Hunter":"इतिहास खोजी",
"Forts, palaces and old walls pull you in every time.":"किले, महल और पुरानी दीवारें आपको हर बार खींच लाती हैं।",
"Jungle Explorer":"जंगल का खोजी",
"You would swap any hotel for a safari at sunrise.":"आप किसी भी होटल के बदले सुबह की सफ़ारी चुनेंगे।",
"City Wanderer":"शहरों का घुमक्कड़",
"Busy streets, food lanes and city lights are your playground.":"भीड़ भरी सड़कें, खाने की गलियाँ और शहर की रोशनी आपका मैदान हैं।",
"All-Rounder":"हरफ़नमौला",
"Mountains, beaches, temples or cities: you say yes to all of it.":"पहाड़, समुद्र, मंदिर या शहर: आप सबके लिए तैयार रहते हैं।",
"Add a few visited places and I will tell you your traveller type!":"कुछ घूमी हुई जगहें जोड़ें, फिर मैं आपका यात्री प्रकार बताऊँगा!",
"📤 Share my type":"📤 मेरा प्रकार शेयर करें",
"I am a {0}! What is your traveller type?":"मैं हूँ {0}! आपका यात्री प्रकार क्या है?",
"Add a few visited places and I will show your travel in numbers!":"कुछ घूमी हुई जगहें जोड़ें, फिर मैं आपकी यात्रा के आँकड़े दिखाऊँगा!",
"{0} km travelled: that is {1} times around the Earth":"{0} किमी का सफ़र: यानी पृथ्वी के {1} चक्कर",
"{0} km travelled: like crossing India top to bottom {1} times":"{0} किमी का सफ़र: जैसे भारत को ऊपर से नीचे {1} बार पार करना",
"You have seen {0}% of the world’s countries":"आप दुनिया के {0}% देश देख चुके हैं",
"You have seen {0}% of India’s states and union territories":"आप भारत के {0}% राज्य और केंद्र शासित प्रदेश देख चुके हैं",
"Furthest north: {0} · furthest south: {1}":"सबसे उत्तर में: {0} · सबसे दक्षिण में: {1}",
"Longest hop: {0} to {1}, {2} km":"सबसे लंबी छलाँग: {0} से {1}, {2} किमी",
"Busiest year: {0} with {1} places":"सबसे व्यस्त साल: {0}, {1} जगहें",
"Furthest from home: {0}, {1} km away":"घर से सबसे दूर: {0}, {1} किमी",
"{0} favourites and {1} places with a memory":"{0} पसंदीदा और {1} जगहें यादों के साथ",
"Your friends have not added places yet. Invite them to find your travel twin!":"आपके दोस्तों ने अभी जगहें नहीं जोड़ीं। अपना यात्रा जुड़वाँ खोजने के लिए उन्हें बुलाएँ!",
"Your travel twin is {0}! Your maps are {1}% the same, with {2} places in common.":"आपका यात्रा जुड़वाँ है {0}! आपके नक्शे {1}% एक जैसे हैं और {2} जगहें दोनों में हैं।",
"Compare our maps":"हमारे नक्शों की तुलना करें",
"👯 Find my travel twin":"👯 मेरा यात्रा जुड़वाँ खोजें",
"👑 Kings and queens":"👑 राजा और रानी",
"Kings and queens":"राजा और रानी",
"You rule {0} of {1} countries":"{1} में से {0} देशों पर आपका राज है",
"You rule {0} of {1} states":"{1} में से {0} राज्यों पर आपका राज है",
"Tie: {0}":"बराबरी: {0}",
"🙈 Hide crowns from my map":"🙈 मेरे नक्शे से ताज हटाएँ",
"👑 Show crowns on my map":"👑 मेरे नक्शे पर ताज दिखाएँ",
"👑 Crowns show who leads each place in your group":"👑 ताज बताते हैं कि आपके ग्रुप में हर जगह कौन आगे है",
"Home town removed":"घर का शहर हटा दिया",
"Home set: {0}":"घर सेट हुआ: {0}",
"Scratch the silver to reveal your new place!":"अपनी नई जगह देखने के लिए चाँदी को खुरचें!",
"Scratch here":"यहाँ खुरचें",
"You won this week’s mystery stamp: {0}! +30 points":"आपने इस हफ़्ते का रहस्यमय स्टैम्प जीता: {0}! +30 अंक",
"Mystery stamp of the week":"हफ़्ते का रहस्यमय स्टैम्प",
"You have it: {0}! +30 points":"यह आपके पास है: {0}! +30 अंक",
"Clue: it is in {0}. Been there? Add it to win a rare stamp.":"संकेत: यह {0} में है। वहाँ गए हैं? जोड़ें और दुर्लभ स्टैम्प जीतें।",
"Rare stamps won: {0}":"जीते हुए दुर्लभ स्टैम्प: {0}",

"Visited ✓":"घूम लिया ✓","Not visited yet":"अभी नहीं घूमे",
"India · {0} places":"भारत · {0} जगहें","From my India map · {0} places":"मेरे भारत के नक्शे से · {0} जगहें",
"{0} comes from your India map. Open the India map to change it.":"{0} आपके भारत के नक्शे से है। इसे बदलने के लिए भारत का नक्शा खोलें।","Open India map 🇮🇳":"भारत का नक्शा खोलें 🇮🇳",
"Getting your picture ready…":"आपकी तस्वीर तैयार हो रही है…",
"World":"दुनिया",
"{0} countries visited":"{0} देश घूमे",
"countries":"देश",
"states":"राज्य",
"Countries":"देश",
"I have visited {0} countries and {1} places around the world. Can you beat me?":"मैं दुनिया के {0} देश और {1} जगहें घूम चुका हूँ। क्या आप मुझसे आगे निकल सकते हैं?",
"🌍 My world journey so far: {0} places, {1} countries and {2} km!":"🌍 मेरी अब तक की विश्व यात्रा: {0} जगहें, {1} देश और {2} किमी!",
"My world travel map 🌍 — {0} places!":"मेरा विश्व यात्रा नक्शा 🌍 — {0} जगहें!",
"Uh-oh! That place is off my map!":"अरे! यह जगह मेरे नक्शे से बाहर है!",
"No place found":"ऐसी कोई जगह नहीं मिली",
"A brand new country to colour in!":"रंग भरने के लिए एक नया देश!",
"Which country is {0} in?":"{0} किस देश में है?",
"How many countries have you visited so far?":"आप अब तक कितने देश घूम चुके हैं?",
"You have visited {0} countries.":"आप {0} देश घूम चुके हैं।",
"March to May or September to November":"मार्च से मई या सितंबर से नवंबर",
"Colour in 1 new country":"1 नए देश में रंग भरें",
"Travel quiz":"यात्रा क्विज़",
"Get a perfect score in the quiz":"क्विज़ में पूरे अंक लाएँ",
"Country Hopper":"देश घुमक्कड़",
"Visit 5 different countries":"5 अलग-अलग देश घूमें",
"Globe Trotter":"विश्व यात्री",
"Visit 15 different countries":"15 अलग-अलग देश घूमें",
"Six Continents":"छह महाद्वीप",
"New Seven Wonders":"दुनिया के सात नए अजूबे",
"India’s Neighbours":"भारत के पड़ोसी",
"Southeast Asia":"दक्षिण-पूर्व एशिया",
"Great World Cities":"दुनिया के बड़े शहर",
"Asia":"एशिया",
"Europe":"यूरोप",
"Africa":"अफ़्रीका",
"North America":"उत्तरी अमेरिका",
"South America":"दक्षिणी अमेरिका",
"Oceania":"ओशिनिया",
"{0} country stamps collected":"{0} देशों के स्टैम्प मिले",
"My country passport":"मेरा देश पासपोर्ट",
"Both":"दोनों",
"Places only {0} has visited":"सिर्फ़ {0} की घूमी हुई जगहें",
"Places only you have visited":"सिर्फ़ आपकी घूमी हुई जगहें",
"Countries {0} has and you do not":"वे देश जो {0} ने घूमे और आपने नहीं",
"🙈 Hide their places from my map":"🙈 उनकी जगहें मेरे नक्शे से हटाएँ",
"Hide {0}’s places from your map?":"{0} की जगहें अपने नक्शे से हटानी हैं?",
"Hide":"हटाएँ",
"Finding a fun fact… 🤔":"मज़ेदार बात खोज रहे हैं… 🤔",
"Tap for a fun fact about one of your places.":"अपनी किसी जगह की मज़ेदार बात के लिए टैप करें।",
"✨ Did you know?":"✨ क्या आप जानते हैं?",
"🔄 Another fact":"🔄 एक और बात",
"Add a place first and I will tell you fun facts about it!":"पहले कोई जगह जोड़ें, फिर मैं उसकी मज़ेदार बातें बताऊँगा!",
"One place, or many with commas: Paris, Dubai, Tokyo":"एक जगह, या कॉमा लगाकर कई: Paris, Dubai, Tokyo",
"Pin the places you have visited in India or around the world, colour in the map and climb the travellers’ leaderboard.":"भारत या दुनिया भर में घूमी हुई जगहों पर पिन लगाएँ, नक्शे में रंग भरें और यात्रियों के लीडरबोर्ड में ऊपर चढ़ें।",

"🇮🇳 My India journey so far: {0} places, {1} states and {2} km!":"🇮🇳 मेरी अब तक की भारत यात्रा: {0} जगहें, {1} राज्य और {2} किमी!",
"⭐ My favourite so far: {0}.":"⭐ अब तक की मेरी सबसे पसंदीदा जगह: {0}।","✈️ Next on my wishlist: {0}.":"✈️ मेरी विशलिस्ट में अगला: {0}।",
"{0} My level on My Travel Map: {1}. Can you beat me?":"{0} My Travel Map पर मेरा लेवल: {1}। क्या आप मुझसे आगे निकल सकते हैं?",
"Make your own map here: {0}":"अपना नक्शा यहाँ बनाएँ: {0}",
"Your journey picture is saved and the message with the link is copied. Paste it in WhatsApp or Instagram and attach the picture.":"आपकी यात्रा की तस्वीर सेव हो गई और लिंक वाला संदेश कॉपी हो गया। इसे WhatsApp या Instagram में पेस्ट करें और तस्वीर अटैच करें।",
"Your journey picture is saved! Attach it in WhatsApp or Instagram.":"आपकी यात्रा की तस्वीर सेव हो गई! इसे WhatsApp या Instagram में अटैच करें।",
"📤 More ways to share":"📤 शेयर करने के और तरीके",
"Drag ⠿ to change the order":"क्रम बदलने के लिए ⠿ को खींचें",
"12 Jyotirlingas":"12 ज्योतिर्लिंग",
"Add 2 places you visited":"2 घूमी हुई जगहें जोड़ें",
"Add 3 places you visited":"3 घूमी हुई जगहें जोड़ें",
"Add a beach you visited":"कोई घूमा हुआ समुद्र तट जोड़ें",
"Add a fort or monument you visited":"कोई घूमा हुआ किला या स्मारक जोड़ें",
"Add a hill station you visited":"कोई घूमा हुआ हिल स्टेशन जोड़ें",
"Add a temple you visited":"कोई घूमा हुआ मंदिर जोड़ें",
"Add a wildlife place you visited":"कोई घूमी हुई वन्यजीव जगह जोड़ें",
"Answer now · streak {0}":"अभी जवाब दें · लगातार {0} दिन",
"Bharat Champion":"भारत चैंपियन",
"Bharat Yatri":"भारत यात्री",
"Big Six Cities":"छह बड़े शहर",
"Can you beat me?":"क्या आप मुझसे आगे निकल सकते हैं?",
"Celebration sounds":"जश्न की आवाज़ें",
"Char Dham":"चार धाम",
"Coastline States":"समुद्र तट वाले राज्य",
"Collection complete: {0}!":"संग्रह पूरा हुआ: {0}!",
"Collections":"संग्रह",
"Colour in 1 new state":"1 नए राज्य में रंग भरें",
"Daily question":"रोज़ का सवाल",
"Done for today! Streak: {0}":"आज का हो गया! लगातार {0} दिन",
"Done! +50 points":"पूरा हुआ! +50 अंक",
"Exact date (optional)":"सही तारीख (ज़रूरी नहीं)",
"Explorer":"खोजी",
"Friends groups need the new database rules. Publish the rules file that came with this version in Firebase.":"दोस्तों के ग्रुप के लिए नए डेटाबेस नियम चाहिए। इस संस्करण के साथ मिली नियम फ़ाइल को Firebase में पब्लिश करें।",
"Ghumakkad":"घुमक्कड़",
"Golden Triangle":"स्वर्ण त्रिभुज",
"Himalayan States":"हिमालयी राज्य",
"I could not find a group with that code.":"इस कोड का कोई ग्रुप नहीं मिला।",
"I have visited {0} of 28 states and {1} places in India. Can you beat me?":"मैं भारत के 28 में से {0} राज्य और {1} जगहें घूम चुका हूँ। क्या आप मुझसे आगे निकल सकते हैं?",
"Join my travel group “{0}” on My Travel Map! Group code: {1}":"My Travel Map पर मेरे यात्रा ग्रुप “{0}” से जुड़ें! ग्रुप कोड: {1}",
"Journey video":"यात्रा का वीडियो",
"Keep this phone’s map 📱":"इस फ़ोन का नक्शा रखें 📱",
"Keep this screen open for a few seconds.":"कुछ सेकंड यह स्क्रीन खुली रखें।",
"Leave the group {0}?":"ग्रुप {0} छोड़ना है?",
"Leave this group":"यह ग्रुप छोड़ें",
"Level up! You are now: {0}":"लेवल बढ़ गया! अब आप हैं: {0}",
"Level {0}":"लेवल {0}",
"Make a private leaderboard for your family and friends. People in a group can see each other’s place names and scores.":"अपने परिवार और दोस्तों के लिए निजी लीडरबोर्ड बनाएँ। ग्रुप के लोग एक-दूसरे की जगहों के नाम और स्कोर देख सकते हैं।",
"Making your video…":"आपका वीडियो बन रहा है…",
"Map picture":"नक्शे की तस्वीर",
"Monthly challenge done! +50 points":"महीने की चुनौती पूरी! +50 अंक",
"My state passport":"मेरा राज्य पासपोर्ट",
"Name your friends group":"अपने दोस्तों के ग्रुप का नाम रखें",
"New on your map: {0}!":"आपके नक्शे पर नया: {0}!",
"Only you":"सिर्फ़ आप",
"Only {0}":"सिर्फ़ {0}",
"Passport stamps":"पासपोर्ट के स्टैम्प",
"Points":"अंक",
"Purple pins: {0}’s places":"बैंगनी पिन: {0} की जगहें",
"Put 2 dream places on your wishlist":"विशलिस्ट में 2 सपनों की जगहें जोड़ें",
"Put 3 dream places on your wishlist":"विशलिस्ट में 3 सपनों की जगहें जोड़ें",
"Saved! Attach it in WhatsApp or Instagram.":"सेव हो गया! इसे WhatsApp या Instagram में अटैच करें।",
"Send this code to your friends: {0} (the invite message is copied).":"यह कोड अपने दोस्तों को भेजें: {0} (न्योते का संदेश कॉपी हो गया है)।",
"Seven Sisters":"सात बहनें",
"States {0} has and you do not":"वे राज्य जो {0} ने घूमे और आपने नहीं",
"Story card (tall)":"स्टोरी कार्ड (लंबा)",
"Tap a friend to compare your maps.":"नक्शों की तुलना के लिए किसी दोस्त पर टैप करें।",
"Tap to open this memory":"यह याद खोलने के लिए टैप करें",
"That did not work: {0}":"यह नहीं हो पाया: {0}",
"This browser cannot make videos. Try it in Chrome.":"यह ब्राउज़र वीडियो नहीं बना सकता। Chrome में आज़माएँ।",
"This month, 1 year ago: {0}":"इसी महीने, 1 साल पहले: {0}",
"This month, {0} years ago: {1}":"इसी महीने, {0} साल पहले: {1}",
"Tourist":"पर्यटक",
"Type the group code your friend sent you":"दोस्त का भेजा हुआ ग्रुप कोड लिखें",
"Use the saved map ☁️":"सेव किया हुआ नक्शा लें ☁️",
"Wanderer":"घुमंतू",
"World Heritage Wonders":"विश्व धरोहर स्थल",
"Yatri":"यात्री",
"You already answered today. Come back tomorrow to keep your streak going!":"आज का जवाब आप दे चुके हैं। अपना सिलसिला जारी रखने के लिए कल फिर आएँ!",
"You and {0}":"आप और {0}",
"You both visited":"दोनों ने घूमा",
"You joined {0}!":"आप {0} से जुड़ गए!",
"Your account has a saved map with {0} places and this phone has {1}. Which one should I keep?":"आपके खाते में {0} जगहों वाला नक्शा सेव है और इस फ़ोन में {1} जगहें हैं। कौन-सा रखूँ?",
"{0} challenge":"{0} की चुनौती",
"{0} of 36 stamps collected":"36 में से {0} स्टैम्प मिले",
"{0} of {1} done":"{1} में से {0} पूरे",
"{0} points":"{0} अंक",
"{0} points · top level!":"{0} अंक · सबसे ऊँचा लेवल!",
"{0} points · {1} more to become {2}":"{0} अंक · {2} बनने के लिए {1} और",
"{0}’s travel gang":"{0} की यात्रा टोली",
"☁️ Cloud save is off. Publish the new database rules in Firebase to turn it on. Your places are still saved on this phone.":"☁️ क्लाउड सेव बंद है। इसे चालू करने के लिए Firebase में नए डेटाबेस नियम पब्लिश करें। आपकी जगहें इस फ़ोन में सेव हैं।",
"☁️ Saved to your Google account. Sign in on another phone to get your map there.":"☁️ आपके Google खाते में सेव है। दूसरे फ़ोन पर साइन इन करके अपना नक्शा वहाँ पाएँ।",
"☁️ Saving to your Google account…":"☁️ आपके Google खाते में सेव हो रहा है…",
"✅ Correct! Your streak is now {0}. Come back tomorrow!":"✅ सही! अब आपका सिलसिला {0} दिन का है। कल फिर आएँ!",
"❌ Not quite! The answer is {0}. Try again tomorrow.":"❌ सही नहीं! सही जवाब है {0}। कल फिर कोशिश करें।",
"➕ Create a friends group":"➕ दोस्तों का ग्रुप बनाएँ",
"🌍 Everyone":"🌍 सभी",
"👀 Show their places on my map":"👀 उनकी जगहें मेरे नक्शे पर दिखाएँ",
"👥 Friends":"👥 दोस्त",
"📤 Share my passport":"📤 मेरा पासपोर्ट शेयर करें",
"📨 Invite friends · code {0}":"📨 दोस्तों को बुलाएँ · कोड {0}",
"🔑 Join with a code":"🔑 कोड से जुड़ें",

"📤 Share":"📤 शेयर","Add a place first, then share your map!":"पहले कोई जगह जोड़ें, फिर अपना नक्शा शेयर करें!",
"Sign in is needed to use the map. Your places stay saved on this phone and your scores go to the leaderboard.":"नक्शा इस्तेमाल करने के लिए साइन इन ज़रूरी है। आपकी जगहें इसी फ़ोन में सेव रहती हैं और स्कोर लीडरबोर्ड पर जाते हैं।",
"Adding {0} of {1}: {2}…":"{1} में से {0} जोड़ रहे हैं: {2}…","Added {0}: {1}.":"{0} जगहें जुड़ीं: {1}।","Already on your map: {0}.":"पहले से नक्शे पर हैं: {0}।",
"Could not find: {0}. Check the spelling and try again.":"ये नहीं मिलीं: {0}। स्पेलिंग जाँचकर फिर कोशिश करें।",
"One place, or many with commas: Puri, Goa, Agra":"एक जगह, या कॉमा लगाकर कई: Puri, Goa, Agra",
"🇮🇳 My Travel Map":"🇮🇳 मेरा भारत यात्रा नक्शा","My Travel Map":"मेरा यात्रा नक्शा",
"Pin the places you have visited, colour in the states and climb the travellers’ leaderboard.":"घूमी हुई जगहों पर पिन लगाएँ, राज्यों में रंग भरें और यात्रियों के लीडरबोर्ड में ऊपर चढ़ें।",
"Sign in with Google":"Google से साइन इन करें","Continue without signing in":"बिना साइन इन के आगे बढ़ें",
"Sign in to appear on the leaderboard. Your places stay saved on this phone.":"लीडरबोर्ड में आने के लिए साइन इन करें। आपकी जगहें इसी फ़ोन में सेव रहती हैं।",
"Sign in":"साइन इन","Map":"नक्शा","Places":"जगहें","Leaders":"लीडरबोर्ड","Explore":"खोजें","More":"और",
"📋 My places":"📋 मेरी जगहें","🏆 Leaderboard":"🏆 लीडरबोर्ड","🎯 Explore":"🎯 खोजें","⚙️ More":"⚙️ और विकल्प",
"States":"राज्य","Km":"किमी","Loading…":"लोड हो रहा है…","🔄 Refresh":"🔄 रीफ़्रेश",
"The leaderboard needs internet. Check your connection and tap Refresh.":"लीडरबोर्ड के लिए इंटरनेट चाहिए। कनेक्शन जाँचकर रीफ़्रेश दबाएँ।",
"Could not load the leaderboard: {0}":"लीडरबोर्ड लोड नहीं हुआ: {0}","No travellers here yet. Be the first!":"अभी यहाँ कोई यात्री नहीं है। सबसे पहले आप बनें!",
"You are #{0} of {1} travellers":"आप {1} यात्रियों में #{0} पर हैं","Add a visited place to join the leaderboard.":"लीडरबोर्ड में आने के लिए कोई घूमी हुई जगह जोड़ें।",
"Sign in with Google to put your name on the leaderboard.":"लीडरबोर्ड पर अपना नाम लाने के लिए Google से साइन इन करें।",
"Scores update by themselves when your map changes.":"आपका नक्शा बदलते ही स्कोर अपने आप अपडेट हो जाते हैं।",
"You":"आप","Traveller":"यात्री","Signed in as {0}":"{0} के नाम से साइन इन हैं","Sign out":"साइन आउट","Close":"बंद करें",
"I could not reach Google. Check your internet and try again.":"Google से संपर्क नहीं हुआ। इंटरनेट जाँचकर फिर कोशिश करें।",
"Google sign-in works only when this page is opened from a website (https), not from a saved file.":"Google साइन इन तभी चलता है जब यह पेज किसी वेबसाइट (https) से खोला जाए, सेव की हुई फ़ाइल से नहीं।",
"This website address is not allowed for Google sign-in yet. Add it in Firebase → Authentication → Settings → Authorized domains.":"इस वेबसाइट के पते को अभी Google साइन इन की अनुमति नहीं है। इसे Firebase → Authentication → Settings → Authorized domains में जोड़ें।",
"Google sign-in did not work: {0}":"Google साइन इन नहीं हुआ: {0}",
"Play my journey":"मेरी यात्रा चलाएँ","Where should I go next?":"अब कहाँ जाऊँ?","Plan wishlist trips":"विशलिस्ट की योजना","Pins from my photos":"मेरी फ़ोटो से पिन बनाएँ","{0} new pins added and {1} places updated from your photos!":"आपकी फ़ोटो से {0} नए पिन जुड़े और {1} जगहें अपडेट हुईं!"
};
const HI_STATES={"Andaman and Nicobar Islands":"अंडमान और निकोबार द्वीप समूह","Andhra Pradesh":"आंध्र प्रदेश","Arunachal Pradesh":"अरुणाचल प्रदेश","Assam":"असम","Bihar":"बिहार","Chandigarh":"चंडीगढ़","Chhattisgarh":"छत्तीसगढ़","Dadra and Nagar Haveli and Daman and Diu":"दादरा और नगर हवेली और दमन और दीव","Delhi":"दिल्ली","Goa":"गोवा","Gujarat":"गुजरात","Haryana":"हरियाणा","Himachal Pradesh":"हिमाचल प्रदेश","Jammu and Kashmir":"जम्मू और कश्मीर","Jammu & Kashmir":"जम्मू और कश्मीर","Jharkhand":"झारखंड","Karnataka":"कर्नाटक","Kerala":"केरल","Ladakh":"लद्दाख","Lakshadweep":"लक्षद्वीप","Madhya Pradesh":"मध्य प्रदेश","Maharashtra":"महाराष्ट्र","Manipur":"मणिपुर","Meghalaya":"मेघालय","Mizoram":"मिज़ोरम","Nagaland":"नागालैंड","Odisha":"ओडिशा","Puducherry":"पुडुचेरी","Punjab":"पंजाब","Rajasthan":"राजस्थान","Sikkim":"सिक्किम","Tamil Nadu":"तमिलनाडु","Telangana":"तेलंगाना","Tripura":"त्रिपुरा","Uttar Pradesh":"उत्तर प्रदेश","Uttarakhand":"उत्तराखंड","West Bengal":"पश्चिम बंगाल","Arabian Sea":"अरब सागर","Bay of Bengal":"बंगाल की खाड़ी","Indian Ocean":"हिंद महासागर"};
function T(s){
  let out=(LANG==="hi" && HI[s]) || s;
  for(let i=1;i<arguments.length;i++) out=out.split("{"+(i-1)+"}").join(arguments[i]);
  return out;
}
function stName(n){return (LANG==="hi" && HI_STATES[n]) || n;}
function catLabel(c){return T(CATS[c][1]);}
// Extra line for Groq prompts so that answers come back in the chosen language.
function aiLang(){return LANG==="hi"?" Write every text value in simple Hindi (Devanagari script), but keep place names in English letters.":"";}
function applyLang(){
  document.documentElement.lang=LANG;
  document.title=T("My Travel Map");
  document.querySelectorAll("[data-t]").forEach(el=>{ if(!el.dataset.t) el.dataset.t=el.textContent.trim(); el.textContent=T(el.dataset.t); });
  document.querySelectorAll("[data-tp]").forEach(el=>{ if(!el.dataset.tp) el.dataset.tp=el.placeholder; el.placeholder=T(el.dataset.tp); });
  document.querySelectorAll("#mapSvg text:not(#mapTitle)").forEach(el=>{
    if(!el.getAttribute("data-en")) el.setAttribute("data-en",el.textContent);
    el.textContent=stName(el.getAttribute("data-en"));
  });
  document.getElementById("langBtn").textContent=LANG==="hi"?"English":"हिंदी";
  const sel=document.getElementById("catSel"), v=sel.value;
  sel.innerHTML='<option value="">'+T("🪄 Category: pick for me")+'</option>'+Object.keys(CATS).map(c=>'<option value="'+c+'">'+CATS[c][0]+' '+catLabel(c)+'</option>').join("");
  sel.value=v;
  document.getElementById("placeName").placeholder=isWorld()?T("One place, or many with commas: Paris, Dubai, Tokyo"):T("One place, or many with commas: Puri, Goa, Agra");
}
function toggleLang(){
  LANG=LANG==="hi"?"en":"hi";
  localStorage.setItem("myIndiaLangV2",LANG);
  applyLang(); render(); refreshChrome();
}
const DEFAULT_PLACES = [];   // the map starts empty
