/* ============================================================
   🗺️  GEOGRAPHY — Class 1
   ------------------------------------------------------------
   HOW TO EDIT THIS FILE
   • Each { ... } line below is ONE question.
   • Keep this exact shape:
       { question: "your question?", answer: "Correct", options: ["Correct","B","C","D"] }
   • RULES:
       - Give exactly 4 options.
       - The "answer" text must EXACTLY match one of the 4 options.
       - Wrap text in "double quotes". If your text has a " inside it,
         write it as \" (a backslash then a quote).
   • Add or delete question lines freely.
   • Save the file, then refresh the quiz page — changes appear instantly.
   ============================================================ */
registerQuiz("geography", 1, [
  { question: "What lights up the sky in day?", answer: "Sun", options: ["Sun", "Moon", "Star", "Cloud"] },
  { question: "What lights up at night?", answer: "Moon", options: ["Moon", "Sun", "Cloud", "Wind"] },
  { question: "Where do we live?", answer: "Earth", options: ["Earth", "Moon", "Mars", "Sun"] },
  { question: "Earth is round or flat?", answer: "Round", options: ["Round", "Flat", "Square", "Triangle"] },
  { question: "What covers most of Earth?", answer: "Water", options: ["Water", "Land", "Sand", "Forest"] },
  { question: "Mountain is high or low?", answer: "High", options: ["High", "Low", "Flat", "Deep"] },
  { question: "Sea has salty or sweet water?", answer: "Salty", options: ["Salty", "Sweet", "Sour", "Bitter"] },
  { question: "River has salty or sweet water?", answer: "Sweet", options: ["Sweet", "Salty", "Sour", "Bitter"] },
  { question: "Where does rain come from?", answer: "Cloud", options: ["Cloud", "Sun", "Tree", "Mountain"] },
  { question: "What is hot - Sun or Ice?", answer: "Sun", options: ["Sun", "Ice", "Snow", "River"] },
  { question: "What is cold - Ice or Fire?", answer: "Ice", options: ["Ice", "Fire", "Sun", "Lava"] },
  { question: "Sun rises in?", answer: "East", options: ["East", "West", "North", "South"] },
  { question: "Sun sets in?", answer: "West", options: ["West", "East", "North", "South"] },
  { question: "Capital of India?", answer: "New Delhi", options: ["New Delhi", "Mumbai", "Kolkata", "Chennai"] },
  { question: "Country we live in?", answer: "India", options: ["India", "China", "Japan", "Nepal"] },
  { question: "Big water body is called?", answer: "Ocean", options: ["Ocean", "Pond", "Pool", "Tank"] },
  { question: "Hot dry place?", answer: "Desert", options: ["Desert", "Forest", "Mountain", "River"] },
  { question: "Place with many trees?", answer: "Forest", options: ["Forest", "Desert", "Sea", "Mountain"] },
  { question: "Hot place is?", answer: "Tropical", options: ["Tropical", "Polar", "Cold", "Frozen"] },
  { question: "Where is North Pole?", answer: "Top of Earth", options: ["Top of Earth", "Bottom", "Middle", "Side"] },
  { question: "What do we call the place we live called Earth also known as?", answer: "Planet", options: ["Planet", "Star", "Moon", "Sun"] },
  { question: "What shape is the Earth?", answer: "Sphere", options: ["Sphere", "Square", "Triangle", "Flat"] },
  { question: "What do we call frozen water?", answer: "Ice", options: ["Ice", "Steam", "Cloud", "Sand"] },
  { question: "What falls from clouds?", answer: "Rain", options: ["Rain", "Sand", "Snow only", "Leaves"] },
  { question: "What do we call a small hill of sand?", answer: "Dune", options: ["Dune", "Valley", "Cliff", "Cave"] },
  { question: "What is the top of a mountain called?", answer: "Peak", options: ["Peak", "Base", "Slope", "Foot"] },
  { question: "What is a very big group of trees called?", answer: "Forest", options: ["Forest", "Desert", "Ocean", "Field"] },
  { question: "What is land surrounded by water called?", answer: "Island", options: ["Island", "Peninsula", "Coast", "Valley"] },
  { question: "What do we call a place with lots of sand and little water?", answer: "Desert", options: ["Desert", "Forest", "Ocean", "Valley"] },
  { question: "Which is bigger, an ocean or a river?", answer: "Ocean", options: ["Ocean", "River", "Both same", "Lake"] },
  { question: "What do we call flowing water on land?", answer: "River", options: ["River", "Ocean", "Lake", "Sea"] },
  { question: "What do we call still water surrounded by land?", answer: "Lake", options: ["Lake", "River", "Ocean", "Waterfall"] },
  { question: "What is the name of our country?", answer: "India", options: ["India", "China", "Japan", "Nepal"] },
  { question: "What is the capital city of India?", answer: "New Delhi", options: ["New Delhi", "Mumbai", "Kolkata", "Chennai"] },
  { question: "Which season is very hot?", answer: "Summer", options: ["Summer", "Winter", "Monsoon", "Autumn"] },
  { question: "Which season has lots of rain?", answer: "Monsoon", options: ["Monsoon", "Summer", "Winter", "Spring"] },
  { question: "Which season is very cold?", answer: "Winter", options: ["Winter", "Summer", "Monsoon", "Autumn"] },
  { question: "What do we wear in winter to stay warm?", answer: "Sweater", options: ["Sweater", "T-shirt", "Shorts", "Slippers"] },
  { question: "What is the color of the sky on a clear day?", answer: "Blue", options: ["Blue", "Green", "Red", "Black"] },
  { question: "What do birds build to live in?", answer: "Nest", options: ["Nest", "Cave", "Den", "Hive"] },
  { question: "What do we call a very tall landform?", answer: "Mountain", options: ["Mountain", "Valley", "Plain", "Plateau"] },
  { question: "What do we call flat, low land?", answer: "Plain", options: ["Plain", "Mountain", "Hill", "Plateau"] },
  { question: "Where does a fish live?", answer: "Water", options: ["Water", "Tree", "Sand", "Sky"] },
  { question: "What do we call the place where land meets the sea?", answer: "Coast", options: ["Coast", "Desert", "Forest", "Mountain"] },
  { question: "What is snow made of?", answer: "Frozen water", options: ["Frozen water", "Sand", "Cotton", "Salt"] },
  { question: "Which is colder, North Pole or Equator?", answer: "North Pole", options: ["North Pole", "Equator", "Both same", "Neither"] },
  { question: "What do we call a huge amount of salty water?", answer: "Sea", options: ["Sea", "Lake", "Pond", "River"] },
  { question: "What comes after night?", answer: "Day", options: ["Day", "Evening", "Noon", "Dusk"] },
  { question: "What comes after day?", answer: "Night", options: ["Night", "Morning", "Noon", "Sunrise"] },
  { question: "How many seasons are there in India mainly?", answer: "3", options: ["3", "2", "4", "6"] },
  { question: "What do plants need from the sky to grow?", answer: "Sunlight", options: ["Sunlight", "Sand", "Rocks", "Smoke"] },
  { question: "What is the name of the star that gives us light?", answer: "Sun", options: ["Sun", "Moon", "Earth", "Mars"] },
  { question: "What is the closest big body of water to a beach?", answer: "Sea", options: ["Sea", "Desert", "Mountain", "Forest"] },
  { question: "Which is taller, a hill or a mountain?", answer: "Mountain", options: ["Mountain", "Hill", "Both same", "Neither"] },
  { question: "What do we call the middle part of the Earth that is very hot?", answer: "Core", options: ["Core", "Crust", "Surface", "Sky"] },
  { question: "What covers the top layer of Earth where we live?", answer: "Crust", options: ["Crust", "Core", "Cloud", "Sky"] },
  { question: "What do we call soil that is good for growing plants?", answer: "Fertile soil", options: ["Fertile soil", "Rock", "Sand only", "Ice"] },
  { question: "What do we call a place where camels live?", answer: "Desert", options: ["Desert", "Forest", "Ocean", "Mountain"] },
  { question: "What is the opposite of hot?", answer: "Cold", options: ["Cold", "Warm", "Dry", "Wet"] },
  { question: "What can we use to see faraway mountains clearly?", answer: "Binoculars", options: ["Binoculars", "Umbrella", "Mirror", "Fan"] },
  { question: "What do we call heavy rain with strong wind?", answer: "Storm", options: ["Storm", "Breeze", "Fog", "Dew"] },
  { question: "Which is bigger, a village or a city?", answer: "City", options: ["City", "Village", "Both same", "Neither"] },
  { question: "What do we call a place where many people live close together?", answer: "City", options: ["City", "Forest", "Desert", "Ocean"] },
  { question: "What kind of water is found in the sea?", answer: "Salty water", options: ["Salty water", "Sweet water", "Fresh water", "No water"] },
  { question: "What kind of water do we usually drink?", answer: "Fresh water", options: ["Fresh water", "Salty water", "Sea water", "Muddy water"] },
  { question: "What is the name for a very small piece of land in water?", answer: "Island", options: ["Island", "Ocean", "Continent", "Coast"] },
  { question: "How many main directions are there?", answer: "4", options: ["4", "2", "3", "6"] },
  { question: "Which direction does the sun rise from?", answer: "East", options: ["East", "West", "North", "South"] },
  { question: "Which direction does the sun set in?", answer: "West", options: ["West", "East", "North", "South"] },
  { question: "What is a group of many islands called?", answer: "Archipelago", options: ["Archipelago", "Peninsula", "Continent", "Plateau"] },
  { question: "What falls on mountains instead of rain when it is cold?", answer: "Snow", options: ["Snow", "Sand", "Dew", "Hail only"] },
  { question: "What do we call water vapor floating in the sky?", answer: "Cloud", options: ["Cloud", "Fog", "Smoke", "Dust"] },
  { question: "What tool shows us directions - North, South, East, West?", answer: "Compass", options: ["Compass", "Clock", "Ruler", "Calendar"] },
  { question: "What do we call the drawing that shows countries and places?", answer: "Map", options: ["Map", "Chart", "Graph", "Poster"] },
  { question: "What is our planet called?", answer: "Earth", options: ["Earth", "Mars", "Venus", "Moon"] },
  { question: "What is the name of the huge round object that lights our night sky?", answer: "Moon", options: ["Moon", "Sun", "Star", "Cloud"] },
  { question: "Where do polar bears live?", answer: "Cold places", options: ["Cold places", "Desert", "Rainforest", "Ocean floor"] },
  { question: "Where do camels live mostly?", answer: "Desert", options: ["Desert", "Ice", "Ocean", "Forest"] },
  { question: "What is the tallest thing on Earth's surface usually?", answer: "Mountain", options: ["Mountain", "River", "Lake", "Plain"] },
  { question: "What do we call low land between hills?", answer: "Valley", options: ["Valley", "Peak", "Plateau", "Plain"] },
  { question: "What is the name for very cold and icy land?", answer: "Glacier", options: ["Glacier", "Desert", "Forest", "Plain"] },
  { question: "What is a flat raised piece of land called?", answer: "Plateau", options: ["Plateau", "Valley", "Island", "Coast"] },
  { question: "What do we call the line dividing day and night on Earth?", answer: "Terminator line", options: ["Terminator line", "Equator", "Meridian", "Horizon"] },
  { question: "What word means 'very hot and rainy forest'?", answer: "Rainforest", options: ["Rainforest", "Desert", "Tundra", "Grassland"] },
  { question: "What is a large area of grass with few trees called?", answer: "Grassland", options: ["Grassland", "Forest", "Desert", "Wetland"] },
  { question: "What is wet, marshy land called?", answer: "Wetland", options: ["Wetland", "Desert", "Plateau", "Plain"] },
  { question: "What word describes land covered in snow all year?", answer: "Tundra", options: ["Tundra", "Desert", "Rainforest", "Grassland"] },
  { question: "What is the name of the place where a river meets the sea?", answer: "Delta", options: ["Delta", "Source", "Bank", "Bed"] },
  { question: "What do we call the beginning point of a river?", answer: "Source", options: ["Source", "Mouth", "Delta", "Bank"] },
  { question: "What is the edge of a river or lake called?", answer: "Bank", options: ["Bank", "Source", "Delta", "Bed"] },
  { question: "What do we call water falling from a great height?", answer: "Waterfall", options: ["Waterfall", "Fountain", "Spring", "Stream"] },
  { question: "What is a small stream of water called?", answer: "Brook", options: ["Brook", "Ocean", "Sea", "Lake"] },
  { question: "What natural thing can shake the ground?", answer: "Earthquake", options: ["Earthquake", "Rainbow", "Breeze", "Frost"] },
  { question: "What is a big wave caused by an earthquake at sea called?", answer: "Tsunami", options: ["Tsunami", "Whirlpool", "Tide", "Ripple"] },
  { question: "What is a large spinning storm with strong wind called?", answer: "Cyclone", options: ["Cyclone", "Drizzle", "Breeze", "Mist"] },
  { question: "What do we call a mountain that can erupt with lava?", answer: "Volcano", options: ["Volcano", "Glacier", "Cliff", "Cave"] },
  { question: "What hot liquid rock comes out of a volcano?", answer: "Lava", options: ["Lava", "Water", "Ice", "Sand"] },
  { question: "What is the name for a hole underground you can walk into?", answer: "Cave", options: ["Cave", "Valley", "Plateau", "Dune"] },
  { question: "What is India's southern tip called?", answer: "Kanyakumari", options: ["Kanyakumari", "Kashmir", "Kolkata", "Kerala"] },
  { question: "Which mountains are in the north of India?", answer: "The Himalayas", options: ["The Himalayas", "The Alps", "The Andes", "The Rockies"] },
  { question: "What is the name of the ocean south of India?", answer: "Indian Ocean", options: ["Indian Ocean", "Pacific Ocean", "Atlantic Ocean", "Arctic Ocean"] },


]);
