/* ============================================================
   🗺️  GEOGRAPHY — Class 5
   ------------------------------------------------------------
   HOW TO EDIT THIS FILE
   • Each { ... } line below is ONE question.
   • Keep this exact shape:
       { question: "your question?", answer: "Correct", options: ["Correct","B","C","D"] }
   • RULES:
       - Give exactly 4 options.
       - The "answer" text must EXACTLY match one of the 4 options.
       - Wrap text in "double quotes". If your text has a " inside it,
         write it as \" (a backslash then a quote).
   • Add or delete question lines freely.
   • Save the file, then refresh the quiz page — changes appear instantly.
   ============================================================ */
registerQuiz("geography", 5, [
  { question: "Earth rotates around?", answer: "Its axis", options: ["Its axis", "Sun", "Moon", "Stars"] },
  { question: "Earth revolves around?", answer: "Sun", options: ["Sun", "Moon", "Stars", "Mars"] },
  { question: "Time taken for rotation?", answer: "24 hours", options: ["24 hours", "12 hours", "365 days", "1 month"] },
  { question: "Time taken for revolution?", answer: "365 days", options: ["365 days", "24 hours", "30 days", "1 year"] },
  { question: "Imaginary line through middle?", answer: "Equator", options: ["Equator", "Prime Meridian", "Tropic", "Pole"] },
  { question: "Tropic in northern hemisphere?", answer: "Cancer", options: ["Cancer", "Capricorn", "Equator", "Arctic"] },
  { question: "Tropic in southern hemisphere?", answer: "Capricorn", options: ["Capricorn", "Cancer", "Equator", "Antarctic"] },
  { question: "0° longitude is called?", answer: "Prime Meridian", options: ["Prime Meridian", "Equator", "Tropic", "Pole"] },
  { question: "Greenwich is in?", answer: "UK", options: ["UK", "USA", "France", "Germany"] },
  { question: "Day & night are equal at?", answer: "Equator", options: ["Equator", "Poles", "Tropics", "Hemisphere"] },
  { question: "Land between two oceans?", answer: "Isthmus", options: ["Isthmus", "Peninsula", "Island", "Strait"] },
  { question: "Land surrounded by water?", answer: "Island", options: ["Island", "Peninsula", "Isthmus", "Cape"] },
  { question: "Land with water on 3 sides?", answer: "Peninsula", options: ["Peninsula", "Island", "Isthmus", "Cape"] },
  { question: "India is a?", answer: "Peninsula", options: ["Peninsula", "Island", "Isthmus", "Continent"] },
  { question: "Highest plateau in world?", answer: "Tibet", options: ["Tibet", "Deccan", "Anatolian", "Iranian"] },
  { question: "Strait between India & Sri Lanka?", answer: "Palk Strait", options: ["Palk Strait", "Bering", "Bass", "Bering"] },
  { question: "Tropic of Cancer passes through how many Indian states?", answer: "8", options: ["8", "5", "10", "12"] },
  { question: "Largest river basin in world?", answer: "Amazon", options: ["Amazon", "Nile", "Congo", "Ganga"] },
  { question: "Most volcanoes in?", answer: "Pacific Ring of Fire", options: ["Pacific Ring of Fire", "Atlantic", "Indian", "Arctic"] },
  { question: "Highest waterfall in world?", answer: "Angel Falls", options: ["Angel Falls", "Niagara", "Victoria", "Iguazu"] },
  { question: "What is the name for the boundary where two tectonic plates meet?", answer: "Fault line", options: ["Fault line", "Delta", "Isthmus", "Strait"] },
  { question: "What causes earthquakes according to geology?", answer: "Movement of tectonic plates", options: ["Movement of tectonic plates", "Ocean currents", "Wind patterns", "Volcanic ash"] },
  { question: "What is the ring of volcanoes around the Pacific Ocean called?", answer: "Ring of Fire", options: ["Ring of Fire", "Fire Belt", "Volcano Chain", "Magma Circle"] },
  { question: "What is the study of Earth's physical structure called?", answer: "Geology", options: ["Geology", "Geography", "Meteorology", "Astronomy"] },
  { question: "What is the imaginary line at 23.5° North called?", answer: "Tropic of Cancer", options: ["Tropic of Cancer", "Tropic of Capricorn", "Equator", "Arctic Circle"] },
  { question: "What is the imaginary line at 23.5° South called?", answer: "Tropic of Capricorn", options: ["Tropic of Capricorn", "Tropic of Cancer", "Equator", "Antarctic Circle"] },
  { question: "What is the imaginary line at 66.5° North called?", answer: "Arctic Circle", options: ["Arctic Circle", "Antarctic Circle", "Tropic of Cancer", "Equator"] },
  { question: "What is the imaginary line at 66.5° South called?", answer: "Antarctic Circle", options: ["Antarctic Circle", "Arctic Circle", "Tropic of Capricorn", "Equator"] },
  { question: "How many time zones does the Earth have roughly?", answer: "24", options: ["24", "12", "36", "7"] },
  { question: "What causes the different seasons on Earth?", answer: "Tilt of Earth's axis", options: ["Tilt of Earth's axis", "Distance from sun changes a lot", "Moon's gravity", "Ocean currents"] },
  { question: "What is the angle of Earth's tilt approximately?", answer: "23.5 degrees", options: ["23.5 degrees", "45 degrees", "10 degrees", "90 degrees"] },
  { question: "What is the term for the average weather of a region over a long time?", answer: "Climate", options: ["Climate", "Weather", "Season", "Forecast"] },
  { question: "What is the short-term condition of the atmosphere called?", answer: "Weather", options: ["Weather", "Climate", "Season", "Ecosystem"] },
  { question: "What is a region with hot, humid climate near the Equator called?", answer: "Tropical climate", options: ["Tropical climate", "Polar climate", "Temperate climate", "Arid climate"] },
  { question: "What is a dry climate with very little rain called?", answer: "Arid climate", options: ["Arid climate", "Tropical climate", "Temperate climate", "Polar climate"] },
  { question: "What is a mild climate with four seasons called?", answer: "Temperate climate", options: ["Temperate climate", "Tropical climate", "Arid climate", "Polar climate"] },
  { question: "What is a very cold climate near the poles called?", answer: "Polar climate", options: ["Polar climate", "Tropical climate", "Arid climate", "Temperate climate"] },
  { question: "What causes monsoon winds in India?", answer: "Seasonal reversal of wind direction", options: ["Seasonal reversal of wind direction", "Ocean currents only", "Earth's rotation only", "Mountain height only"] },
  { question: "Which winds bring rain to India in summer?", answer: "Southwest Monsoon", options: ["Southwest Monsoon", "Northeast Monsoon", "Trade Winds", "Westerlies"] },
  { question: "Which winds bring rain to Tamil Nadu in winter?", answer: "Northeast Monsoon", options: ["Northeast Monsoon", "Southwest Monsoon", "Trade Winds", "Westerlies"] },
  { question: "What is the term for permanent ice sheets that move slowly?", answer: "Glaciers", options: ["Glaciers", "Icebergs", "Snowfields", "Frost"] },
  { question: "What is a large piece of ice floating in the sea called?", answer: "Iceberg", options: ["Iceberg", "Glacier", "Snowdrift", "Floe"] },
  { question: "What is the phenomenon of global temperature rising called?", answer: "Global warming", options: ["Global warming", "Climate cycle", "Ozone depletion", "Greenhouse cooling"] },
  { question: "What gases trap heat in Earth's atmosphere, causing warming?", answer: "Greenhouse gases", options: ["Greenhouse gases", "Noble gases", "Inert gases", "Halogens"] },
  { question: "What is the protective layer in the atmosphere that blocks UV rays?", answer: "Ozone layer", options: ["Ozone layer", "Troposphere", "Ionosphere", "Stratosphere clouds"] },
  { question: "What is the lowest layer of the atmosphere, where weather happens?", answer: "Troposphere", options: ["Troposphere", "Stratosphere", "Mesosphere", "Thermosphere"] },
  { question: "What is the layer of the atmosphere containing the ozone layer?", answer: "Stratosphere", options: ["Stratosphere", "Troposphere", "Mesosphere", "Exosphere"] },
  { question: "What is the term for erosion caused by wind in deserts?", answer: "Wind erosion", options: ["Wind erosion", "Water erosion", "Glacial erosion", "Chemical weathering"] },
  { question: "What is the breaking down of rocks by natural forces called?", answer: "Weathering", options: ["Weathering", "Erosion", "Deposition", "Sedimentation"] },
  { question: "What is the movement of eroded material to a new place called?", answer: "Erosion", options: ["Erosion", "Weathering", "Deposition", "Sedimentation"] },
  { question: "What is the settling of eroded material called?", answer: "Deposition", options: ["Deposition", "Erosion", "Weathering", "Sedimentation only"] },
  { question: "What type of rock forms from cooled lava or magma?", answer: "Igneous rock", options: ["Igneous rock", "Sedimentary rock", "Metamorphic rock", "Mineral rock"] },
  { question: "What type of rock forms from layers of sediment over time?", answer: "Sedimentary rock", options: ["Sedimentary rock", "Igneous rock", "Metamorphic rock", "Mineral rock"] },
  { question: "What type of rock forms when existing rock is changed by heat and pressure?", answer: "Metamorphic rock", options: ["Metamorphic rock", "Igneous rock", "Sedimentary rock", "Mineral rock"] },
  { question: "What is marble an example of?", answer: "Metamorphic rock", options: ["Metamorphic rock", "Igneous rock", "Sedimentary rock", "Mineral rock"] },
  { question: "What is granite an example of?", answer: "Igneous rock", options: ["Igneous rock", "Sedimentary rock", "Metamorphic rock", "Mineral rock"] },
  { question: "What is limestone an example of?", answer: "Sedimentary rock", options: ["Sedimentary rock", "Igneous rock", "Metamorphic rock", "Mineral rock"] },
  { question: "What is the hard, dense center of the Earth made mostly of?", answer: "Iron and nickel", options: ["Iron and nickel", "Rock and sand", "Water and ice", "Magma only"] },
  { question: "What is the layer between Earth's crust and core called?", answer: "Mantle", options: ["Mantle", "Crust", "Core", "Lithosphere"] },
  { question: "Which is the thinnest layer of the Earth?", answer: "Crust", options: ["Crust", "Mantle", "Outer core", "Inner core"] },
  { question: "What type of crust is found under oceans?", answer: "Oceanic crust", options: ["Oceanic crust", "Continental crust", "Volcanic crust", "Mantle crust"] },
  { question: "What type of crust makes up the continents?", answer: "Continental crust", options: ["Continental crust", "Oceanic crust", "Volcanic crust", "Mantle crust"] },
  { question: "What are large sections of Earth's crust called?", answer: "Tectonic plates", options: ["Tectonic plates", "Fault lines", "Continents", "Landmasses"] },
  { question: "What is the theory that continents were once joined called?", answer: "Continental drift", options: ["Continental drift", "Plate collision", "Tectonic shift", "Land bridge theory"] },
  { question: "What was the name of the supercontinent before it split apart?", answer: "Pangaea", options: ["Pangaea", "Gondwana", "Laurasia", "Atlantis"] },
  { question: "Which two supercontinents did Pangaea split into?", answer: "Laurasia and Gondwana", options: ["Laurasia and Gondwana", "Asia and Africa", "Europe and America", "Arctic and Antarctic"] },
  { question: "What is a region prone to frequent earthquakes called?", answer: "Seismic zone", options: ["Seismic zone", "Fault belt", "Volcanic belt", "Tectonic zone"] },
  { question: "What natural disaster is measured using the Richter scale?", answer: "Earthquake", options: ["Earthquake", "Cyclone", "Flood", "Drought"] },
  { question: "What scale measures the strength of a hurricane or cyclone?", answer: "Saffir-Simpson scale", options: ["Saffir-Simpson scale", "Richter scale", "Beaufort scale", "Fujita scale"] },
  { question: "What scale measures wind speed generally?", answer: "Beaufort scale", options: ["Beaufort scale", "Richter scale", "Saffir-Simpson scale", "Fujita scale"] },
  { question: "What do we call a tropical cyclone in the Atlantic Ocean region?", answer: "Hurricane", options: ["Hurricane", "Typhoon", "Cyclone", "Tornado"] },
  { question: "What do we call a tropical cyclone in the Pacific near Asia?", answer: "Typhoon", options: ["Typhoon", "Hurricane", "Tornado", "Monsoon"] },
  { question: "What do we call a tropical cyclone in the Indian Ocean region?", answer: "Cyclone", options: ["Cyclone", "Hurricane", "Typhoon", "Tornado"] },
  { question: "What is a violently rotating column of air touching the ground called?", answer: "Tornado", options: ["Tornado", "Hurricane", "Cyclone", "Typhoon"] },
  { question: "Which country experiences the most tornadoes?", answer: "USA", options: ["USA", "India", "Australia", "Brazil"] },
  { question: "What area of the USA is known for frequent tornadoes?", answer: "Tornado Alley", options: ["Tornado Alley", "Silicon Valley", "Rust Belt", "Bible Belt"] },
  { question: "What is a long period of unusually low rainfall called?", answer: "Drought", options: ["Drought", "Famine", "Flood", "Monsoon failure"] },
  { question: "What is the overflow of water onto normally dry land called?", answer: "Flood", options: ["Flood", "Drought", "Tsunami", "Cyclone"] },
  { question: "What is the world's largest hot desert region located in?", answer: "North Africa", options: ["North Africa", "Central Asia", "Southern Africa", "Australia"] },
  { question: "What is a mirage commonly seen in deserts caused by?", answer: "Bending of light due to heat", options: ["Bending of light due to heat", "Reflection off sand", "Wind patterns", "Cloud shadows"] },
  { question: "What percentage of Earth's surface is covered by water approximately?", answer: "71%", options: ["71%", "50%", "60%", "80%"] },
  { question: "What percentage of Earth's water is freshwater approximately?", answer: "3%", options: ["3%", "10%", "25%", "50%"] },
  { question: "Where is most of Earth's fresh water stored?", answer: "Glaciers and ice caps", options: ["Glaciers and ice caps", "Rivers", "Lakes", "Underground only"] },
  { question: "What is groundwater stored in called?", answer: "Aquifer", options: ["Aquifer", "Reservoir", "Basin", "Delta"] },
  { question: "What human-made structure stores water by blocking a river?", answer: "Dam", options: ["Dam", "Canal", "Aqueduct", "Levee"] },
  { question: "What is India's tallest dam?", answer: "Tehri Dam", options: ["Tehri Dam", "Bhakra Dam", "Hirakud Dam", "Sardar Sarovar Dam"] },
  { question: "Which is the largest dam in India by volume?", answer: "Hirakud Dam", options: ["Hirakud Dam", "Tehri Dam", "Bhakra Dam", "Sardar Sarovar Dam"] },
  { question: "What is the world's largest dam by generation capacity?", answer: "Three Gorges Dam, China", options: ["Three Gorges Dam, China", "Hoover Dam", "Itaipu Dam", "Tehri Dam"] },
  { question: "What is a channel built to carry water called?", answer: "Canal", options: ["Canal", "Dam", "Aqueduct", "Levee"] },
  { question: "What natural region is called the 'lungs of the Earth'?", answer: "Amazon Rainforest", options: ["Amazon Rainforest", "Sahara Desert", "Siberian Tundra", "Congo Basin"] },
  { question: "What do we call animals and plants found only in one region?", answer: "Endemic species", options: ["Endemic species", "Migratory species", "Invasive species", "Native species only"] },
  { question: "What line represents the boundary of permanent snow on mountains?", answer: "Snow line", options: ["Snow line", "Tree line", "Equator", "Fault line"] },
  { question: "What line represents the highest altitude where trees can grow?", answer: "Tree line", options: ["Tree line", "Snow line", "Coastline", "Fault line"] },
  { question: "What do geographers call the study of population patterns?", answer: "Demography", options: ["Demography", "Geology", "Cartography", "Meteorology"] },
  { question: "What is the science and art of mapmaking called?", answer: "Cartography", options: ["Cartography", "Demography", "Geology", "Topography"] },
  { question: "What does topography refer to?", answer: "Shape and features of land", options: ["Shape and features of land", "Weather patterns", "Population data", "Ocean currents"] },
  { question: "Which line on a map connects points of equal elevation?", answer: "Contour line", options: ["Contour line", "Latitude line", "Longitude line", "Fault line"] },
  { question: "What do we call a country's total land and water area under its control?", answer: "Territory", options: ["Territory", "Border", "Region", "Zone"] },

  { question: "What is the term for a region's natural plant and animal life together?", answer: "Ecosystem", options: ["Ecosystem", "Habitat", "Biome", "Terrain"] },
  { question: "What is a large natural area with similar climate, plants and animals called?", answer: "Biome", options: ["Biome", "Ecosystem", "Habitat", "Terrain"] },
]);
