/* ============================================================
   🗺️  GEOGRAPHY — Class 3
   ------------------------------------------------------------
   HOW TO EDIT THIS FILE
   • Each { ... } line below is ONE question.
   • Keep this exact shape:
       { question: "your question?", answer: "Correct", options: ["Correct","B","C","D"] }
   • RULES:
       - Give exactly 4 options.
       - The "answer" text must EXACTLY match one of the 4 options.
       - Wrap text in "double quotes". If your text has a " inside it,
         write it as \" (a backslash then a quote).
   • Add or delete question lines freely.
   • Save the file, then refresh the quiz page — changes appear instantly.
   ============================================================ */
registerQuiz("geography", 3, [
  { question: "Capital of Maharashtra?", answer: "Mumbai", options: ["Mumbai", "Pune", "Nagpur", "Nashik"] },
  { question: "Capital of Rajasthan?", answer: "Jaipur", options: ["Jaipur", "Jodhpur", "Udaipur", "Kota"] },
  { question: "Capital of UP?", answer: "Lucknow", options: ["Lucknow", "Kanpur", "Agra", "Varanasi"] },
  { question: "Capital of West Bengal?", answer: "Kolkata", options: ["Kolkata", "Howrah", "Darjeeling", "Asansol"] },
  { question: "Capital of Karnataka?", answer: "Bengaluru", options: ["Bengaluru", "Mysuru", "Mangaluru", "Hubli"] },
  { question: "Capital of Tamil Nadu?", answer: "Chennai", options: ["Chennai", "Madurai", "Coimbatore", "Salem"] },
  { question: "Capital of Gujarat?", answer: "Gandhinagar", options: ["Gandhinagar", "Ahmedabad", "Surat", "Vadodara"] },
  { question: "Capital of Punjab?", answer: "Chandigarh", options: ["Chandigarh", "Amritsar", "Ludhiana", "Patiala"] },
  { question: "Capital of Haryana?", answer: "Chandigarh", options: ["Chandigarh", "Faridabad", "Gurgaon", "Hisar"] },
  { question: "Capital of Bihar?", answer: "Patna", options: ["Patna", "Gaya", "Bhagalpur", "Muzaffarpur"] },
  { question: "Capital of MP?", answer: "Bhopal", options: ["Bhopal", "Indore", "Gwalior", "Jabalpur"] },
  { question: "Capital of Kerala?", answer: "Thiruvananthapuram", options: ["Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur"] },
  { question: "Capital of Odisha?", answer: "Bhubaneswar", options: ["Bhubaneswar", "Cuttack", "Puri", "Rourkela"] },
  { question: "Capital of Assam?", answer: "Dispur", options: ["Dispur", "Guwahati", "Silchar", "Jorhat"] },
  { question: "Capital of Telangana?", answer: "Hyderabad", options: ["Hyderabad", "Warangal", "Karimnagar", "Nizamabad"] },
  { question: "Capital of Andhra Pradesh?", answer: "Amaravati", options: ["Amaravati", "Hyderabad", "Vijayawada", "Tirupati"] },
  { question: "Capital of Goa?", answer: "Panaji", options: ["Panaji", "Margao", "Vasco", "Mapusa"] },
  { question: "Capital of HP?", answer: "Shimla", options: ["Shimla", "Manali", "Dharamshala", "Solan"] },
  { question: "Capital of Uttarakhand?", answer: "Dehradun", options: ["Dehradun", "Haridwar", "Nainital", "Mussoorie"] },
  { question: "Capital of Jammu & Kashmir?", answer: "Srinagar (summer)", options: ["Srinagar (summer)", "Jammu", "Leh", "Anantnag"] },
  { question: "Which is the longest river in India?", answer: "Ganga", options: ["Ganga", "Yamuna", "Godavari", "Narmada"] },
  { question: "Which river is called the 'Sorrow of Bihar'?", answer: "Kosi", options: ["Kosi", "Ganga", "Son", "Gandak"] },
  { question: "Which is the largest state in India by area?", answer: "Rajasthan", options: ["Rajasthan", "Madhya Pradesh", "Maharashtra", "Uttar Pradesh"] },
  { question: "Which is the largest state in India by population?", answer: "Uttar Pradesh", options: ["Uttar Pradesh", "Bihar", "Maharashtra", "West Bengal"] },
  { question: "Which is the smallest state in India by area?", answer: "Goa", options: ["Goa", "Sikkim", "Tripura", "Kerala"] },
  { question: "Which Indian state has the longest coastline?", answer: "Gujarat", options: ["Gujarat", "Tamil Nadu", "Andhra Pradesh", "Maharashtra"] },
  { question: "Which mountain range separates India from China?", answer: "The Himalayas", options: ["The Himalayas", "Western Ghats", "Eastern Ghats", "Aravalli"] },
  { question: "Which mountains run along India's west coast?", answer: "Western Ghats", options: ["Western Ghats", "Eastern Ghats", "Himalayas", "Vindhya"] },
  { question: "Which mountains run along India's east coast?", answer: "Eastern Ghats", options: ["Eastern Ghats", "Western Ghats", "Himalayas", "Satpura"] },
  { question: "Which is the oldest mountain range in India?", answer: "Aravalli Range", options: ["Aravalli Range", "Himalayas", "Western Ghats", "Vindhya"] },
  { question: "Which desert is found in Rajasthan?", answer: "Thar Desert", options: ["Thar Desert", "Sahara Desert", "Gobi Desert", "Kalahari Desert"] },
  { question: "Which is the highest peak in India?", answer: "Kanchenjunga", options: ["Kanchenjunga", "Nanda Devi", "Mount Everest", "K2"] },
  { question: "Which strait separates India and Sri Lanka?", answer: "Palk Strait", options: ["Palk Strait", "Bering Strait", "Malacca Strait", "Bosphorus"] },
  { question: "Which sea lies to the west of India?", answer: "Arabian Sea", options: ["Arabian Sea", "Bay of Bengal", "Indian Ocean", "Red Sea"] },
  { question: "Which bay lies to the east of India?", answer: "Bay of Bengal", options: ["Bay of Bengal", "Arabian Sea", "Red Sea", "Caspian Sea"] },
  { question: "Which is the southernmost point of mainland India?", answer: "Kanyakumari", options: ["Kanyakumari", "Kashmir", "Kerala", "Goa"] },
  { question: "Which Indian islands are in the Bay of Bengal?", answer: "Andaman and Nicobar Islands", options: ["Andaman and Nicobar Islands", "Lakshadweep", "Maldives", "Sri Lanka"] },
  { question: "Which Indian islands are in the Arabian Sea?", answer: "Lakshadweep", options: ["Lakshadweep", "Andaman and Nicobar Islands", "Maldives", "Sri Lanka"] },
  { question: "Which river flows through Gujarat and meets the Arabian Sea?", answer: "Narmada", options: ["Narmada", "Ganga", "Brahmaputra", "Godavari"] },
  { question: "Which river is called the 'Ganga of the South'?", answer: "Godavari", options: ["Godavari", "Krishna", "Kaveri", "Narmada"] },
  { question: "Which river flows through Assam?", answer: "Brahmaputra", options: ["Brahmaputra", "Ganga", "Yamuna", "Godavari"] },
  { question: "Which two rivers meet at Prayagraj along with a mythical third?", answer: "Ganga and Yamuna", options: ["Ganga and Yamuna", "Ganga and Godavari", "Yamuna and Narmada", "Krishna and Kaveri"] },
  { question: "Which Indian city is called the 'Manchester of India'?", answer: "Ahmedabad", options: ["Ahmedabad", "Mumbai", "Kanpur", "Surat"] },
  { question: "Which plateau covers much of peninsular India?", answer: "Deccan Plateau", options: ["Deccan Plateau", "Tibetan Plateau", "Chota Nagpur Plateau", "Malwa Plateau"] },
  { question: "Which region of India is rich in minerals like coal and iron?", answer: "Chota Nagpur Plateau", options: ["Chota Nagpur Plateau", "Deccan Plateau", "Gangetic Plain", "Thar Desert"] },
  { question: "Which plain is the most fertile region in India?", answer: "Indo-Gangetic Plain", options: ["Indo-Gangetic Plain", "Deccan Plateau", "Thar Desert", "Malwa Plateau"] },
  { question: "Which Indian state is known as the 'Spice Garden of India'?", answer: "Kerala", options: ["Kerala", "Tamil Nadu", "Karnataka", "Goa"] },
  { question: "Which Indian state is known as 'God's Own Country'?", answer: "Kerala", options: ["Kerala", "Goa", "Tamil Nadu", "Karnataka"] },
  { question: "Which Indian state is called the 'Land of Five Rivers'?", answer: "Punjab", options: ["Punjab", "Haryana", "Rajasthan", "Gujarat"] },
  { question: "Which Indian state is famous for tea gardens?", answer: "Assam", options: ["Assam", "Punjab", "Rajasthan", "Gujarat"] },
  { question: "Which line of latitude passes through the middle of India?", answer: "Tropic of Cancer", options: ["Tropic of Cancer", "Equator", "Tropic of Capricorn", "Prime Meridian"] },
  { question: "Which Indian city lies exactly on the Tropic of Cancer?", answer: "Bhopal", options: ["Bhopal", "Delhi", "Mumbai", "Chennai"] },
  { question: "Which Indian state has the most forest cover by percentage?", answer: "Mizoram", options: ["Mizoram", "Kerala", "Assam", "Sikkim"] },
  { question: "What is the name of India's national river?", answer: "Ganga", options: ["Ganga", "Yamuna", "Godavari", "Brahmaputra"] },
  { question: "Which Indian mountain is the second-highest peak in India?", answer: "Nanda Devi", options: ["Nanda Devi", "Kanchenjunga", "K2", "Kamet"] },
  { question: "Which country lies to the north of India?", answer: "China", options: ["China", "Pakistan", "Nepal", "Myanmar"] },
  { question: "Which country lies to the west of India?", answer: "Pakistan", options: ["Pakistan", "China", "Nepal", "Bangladesh"] },
  { question: "Which country lies to the east of India (bordering)?", answer: "Myanmar", options: ["Myanmar", "China", "Pakistan", "Nepal"] },
  { question: "How many countries border India by land?", answer: "7", options: ["7", "5", "6", "8"] },
  { question: "Which is the largest coral reef system in the world?", answer: "Great Barrier Reef", options: ["Great Barrier Reef", "Belize Barrier Reef", "Red Sea Coral Reef", "Andaman Coral Reef"] },
  { question: "Which continent has the most population?", answer: "Asia", options: ["Asia", "Africa", "Europe", "North America"] },
  { question: "Which continent has the least population?", answer: "Antarctica", options: ["Antarctica", "Australia", "Europe", "South America"] },
  { question: "What is the total number of oceans that border Antarctica called together?", answer: "Southern Ocean", options: ["Southern Ocean", "Arctic Ocean", "Indian Ocean", "Atlantic Ocean"] },
  { question: "Which country has the most volcanoes?", answer: "Indonesia", options: ["Indonesia", "Japan", "USA", "Philippines"] },
  { question: "Which is the world's largest archipelago (island nation)?", answer: "Indonesia", options: ["Indonesia", "Philippines", "Japan", "Maldives"] },
  { question: "What is the term for land completely surrounded by another country?", answer: "Enclave", options: ["Enclave", "Peninsula", "Isthmus", "Archipelago"] },
  { question: "What is a country with no coastline called?", answer: "Landlocked country", options: ["Landlocked country", "Island nation", "Peninsula", "Archipelago"] },
  { question: "Name a landlocked country in Asia.", answer: "Nepal", options: ["Nepal", "Sri Lanka", "Indonesia", "Philippines"] },
  { question: "Name a landlocked country in Europe.", answer: "Switzerland", options: ["Switzerland", "France", "Spain", "Italy"] },
  { question: "What do we call a narrow strip of land joining two larger land areas?", answer: "Isthmus", options: ["Isthmus", "Peninsula", "Strait", "Delta"] },
  { question: "What do we call a narrow strip of water joining two seas?", answer: "Strait", options: ["Strait", "Isthmus", "Delta", "Gulf"] },
  { question: "What do we call a part of a sea partly enclosed by land?", answer: "Gulf", options: ["Gulf", "Strait", "Delta", "Isthmus"] },
  { question: "Name a famous gulf near India.", answer: "Gulf of Khambhat", options: ["Gulf of Khambhat", "Gulf of Mexico", "Persian Gulf", "Gulf of Aden"] },
  { question: "What is the fan-shaped land formed where a river meets the sea called?", answer: "Delta", options: ["Delta", "Gulf", "Strait", "Isthmus"] },
  { question: "Which Indian river forms a large delta with the Brahmaputra?", answer: "Ganga", options: ["Ganga", "Yamuna", "Godavari", "Krishna"] },
  { question: "What do we call the imaginary line at 0° longitude?", answer: "Prime Meridian", options: ["Prime Meridian", "Equator", "Tropic of Cancer", "International Date Line"] },
  { question: "Which city does the Prime Meridian pass through?", answer: "Greenwich (London)", options: ["Greenwich (London)", "Paris", "Rome", "New York"] },
  { question: "What do we call the line at 180° longitude?", answer: "International Date Line", options: ["International Date Line", "Prime Meridian", "Equator", "Tropic Line"] },
  { question: "Which hemisphere is India located in (north-south)?", answer: "Northern Hemisphere", options: ["Northern Hemisphere", "Southern Hemisphere", "Eastern Hemisphere only", "Western Hemisphere only"] },
  { question: "Which hemisphere is Australia located in (north-south)?", answer: "Southern Hemisphere", options: ["Southern Hemisphere", "Northern Hemisphere", "Eastern Hemisphere only", "Western Hemisphere only"] },
  { question: "What is the name of the layer of gases around Earth?", answer: "Atmosphere", options: ["Atmosphere", "Lithosphere", "Hydrosphere", "Biosphere"] },
  { question: "What is the name for all the water on Earth together?", answer: "Hydrosphere", options: ["Hydrosphere", "Atmosphere", "Lithosphere", "Biosphere"] },
  { question: "What is the name for the solid outer layer of Earth?", answer: "Lithosphere", options: ["Lithosphere", "Atmosphere", "Hydrosphere", "Biosphere"] },
  { question: "What is the layer of Earth where living things exist called?", answer: "Biosphere", options: ["Biosphere", "Atmosphere", "Hydrosphere", "Lithosphere"] },
  { question: "Which is the driest place on Earth?", answer: "Atacama Desert", options: ["Atacama Desert", "Sahara Desert", "Thar Desert", "Gobi Desert"] },
  { question: "Which is the wettest place on Earth?", answer: "Mawsynram, India", options: ["Mawsynram, India", "Cherrapunji", "Amazon", "Bangkok"] },
  { question: "Which Indian place is famous for being one of the wettest in the world?", answer: "Cherrapunji", options: ["Cherrapunji", "Jaisalmer", "Leh", "Jodhpur"] },
  { question: "Which is the coldest place on Earth ever recorded?", answer: "Antarctica", options: ["Antarctica", "Siberia", "Greenland", "Alaska"] },
  { question: "Which is the hottest place on Earth ever recorded?", answer: "Death Valley, USA", options: ["Death Valley, USA", "Sahara Desert", "Thar Desert", "Dasht-e Lut"] },
  { question: "Which desert is the largest in Asia?", answer: "Gobi Desert", options: ["Gobi Desert", "Thar Desert", "Arabian Desert", "Kyzylkum Desert"] },
  { question: "Which is the largest island country made up of thousands of islands, in Southeast Asia?", answer: "Indonesia", options: ["Indonesia", "Philippines", "Malaysia", "Vietnam"] },
  { question: "What are people who study earthquakes called?", answer: "Seismologists", options: ["Seismologists", "Geologists", "Meteorologists", "Volcanologists"] },
  { question: "What are people who study weather called?", answer: "Meteorologists", options: ["Meteorologists", "Seismologists", "Geologists", "Astronomers"] },
  { question: "What instrument measures earthquakes?", answer: "Seismograph", options: ["Seismograph", "Barometer", "Thermometer", "Anemometer"] },
  { question: "What instrument measures rainfall?", answer: "Rain gauge", options: ["Rain gauge", "Barometer", "Thermometer", "Seismograph"] },
  { question: "What instrument measures wind speed?", answer: "Anemometer", options: ["Anemometer", "Barometer", "Thermometer", "Rain gauge"] },
  { question: "What instrument measures air pressure?", answer: "Barometer", options: ["Barometer", "Thermometer", "Anemometer", "Rain gauge"] },
  { question: "What is the scientific name for a map book?", answer: "Atlas", options: ["Atlas", "Almanac", "Encyclopedia", "Globe"] },
  { question: "What is a round model of the Earth called?", answer: "Globe", options: ["Globe", "Atlas", "Map", "Chart"] },


]);
