/* ============================================================
   🗺️  GEOGRAPHY — Class 4
   ------------------------------------------------------------
   HOW TO EDIT THIS FILE
   • Each { ... } line below is ONE question.
   • Keep this exact shape:
       { question: "your question?", answer: "Correct", options: ["Correct","B","C","D"] }
   • RULES:
       - Give exactly 4 options.
       - The "answer" text must EXACTLY match one of the 4 options.
       - Wrap text in "double quotes". If your text has a " inside it,
         write it as \" (a backslash then a quote).
   • Add or delete question lines freely.
   • Save the file, then refresh the quiz page — changes appear instantly.
   ============================================================ */
registerQuiz("geography", 4, [
  { question: "Longest river in world?", answer: "Nile", options: ["Nile", "Amazon", "Ganga", "Mississippi"] },
  { question: "Longest river in India?", answer: "Ganga", options: ["Ganga", "Yamuna", "Brahmaputra", "Godavari"] },
  { question: "Largest lake in world?", answer: "Caspian Sea", options: ["Caspian Sea", "Lake Superior", "Victoria", "Baikal"] },
  { question: "Deepest lake in world?", answer: "Lake Baikal", options: ["Lake Baikal", "Caspian", "Tanganyika", "Superior"] },
  { question: "Tallest mountain in world?", answer: "Mt Everest", options: ["Mt Everest", "K2", "Kanchenjunga", "Lhotse"] },
  { question: "Highest mountain in India?", answer: "Kanchenjunga", options: ["Kanchenjunga", "Mt Everest", "Nanda Devi", "K2"] },
  { question: "Largest desert in world?", answer: "Sahara", options: ["Sahara", "Thar", "Gobi", "Arabian"] },
  { question: "Largest desert in India?", answer: "Thar", options: ["Thar", "Sahara", "Gobi", "Kalahari"] },
  { question: "Largest country by area?", answer: "Russia", options: ["Russia", "Canada", "USA", "China"] },
  { question: "Smallest country in world?", answer: "Vatican City", options: ["Vatican City", "Monaco", "Nauru", "Tuvalu"] },
  { question: "Most populated country?", answer: "India", options: ["India", "China", "USA", "Indonesia"] },
  { question: "Country with most languages?", answer: "Papua New Guinea", options: ["Papua New Guinea", "India", "China", "Russia"] },
  { question: "Land of rising sun?", answer: "Japan", options: ["Japan", "China", "Korea", "Thailand"] },
  { question: "Land of midnight sun?", answer: "Norway", options: ["Norway", "Russia", "Canada", "Iceland"] },
  { question: "River that flows through Egypt?", answer: "Nile", options: ["Nile", "Amazon", "Tigris", "Euphrates"] },
  { question: "River that flows through Brazil?", answer: "Amazon", options: ["Amazon", "Nile", "Mississippi", "Yangtze"] },
  { question: "River that flows through China?", answer: "Yangtze", options: ["Yangtze", "Ganga", "Mekong", "Amur"] },
  { question: "River where Delhi is?", answer: "Yamuna", options: ["Yamuna", "Ganga", "Saraswati", "Krishna"] },
  { question: "River where Varanasi is?", answer: "Ganga", options: ["Ganga", "Yamuna", "Saraswati", "Krishna"] },
  { question: "River where Kolkata is?", answer: "Hooghly", options: ["Hooghly", "Ganga", "Yamuna", "Brahmaputra"] },
  { question: "Which is the second-longest river in the world?", answer: "Amazon", options: ["Amazon", "Nile", "Yangtze", "Mississippi"] },
  { question: "Which is the longest river in Asia?", answer: "Yangtze", options: ["Yangtze", "Ganga", "Mekong", "Indus"] },
  { question: "Which is the longest river in Europe?", answer: "Volga", options: ["Volga", "Danube", "Rhine", "Seine"] },
  { question: "Which is the longest river in Africa besides the Nile system overall?", answer: "Congo River", options: ["Congo River", "Niger River", "Zambezi River", "Orange River"] },
  { question: "Which is the longest river in North America?", answer: "Missouri River", options: ["Missouri River", "Mississippi River", "Colorado River", "Rio Grande"] },
  { question: "Which is the largest ocean in the world?", answer: "Pacific Ocean", options: ["Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean"] },
  { question: "Which is the largest gulf in the world?", answer: "Gulf of Mexico", options: ["Gulf of Mexico", "Persian Gulf", "Gulf of Aden", "Gulf of Khambhat"] },
  { question: "Which is the largest bay in the world?", answer: "Bay of Bengal", options: ["Bay of Bengal", "Hudson Bay", "Gulf of Mexico", "Bay of Biscay"] },
  { question: "Which is the largest peninsula in the world?", answer: "Arabian Peninsula", options: ["Arabian Peninsula", "Indian Peninsula", "Iberian Peninsula", "Scandinavian Peninsula"] },
  { question: "Which is the highest plateau in the world?", answer: "Tibetan Plateau", options: ["Tibetan Plateau", "Deccan Plateau", "Colorado Plateau", "Bolivian Plateau"] },
  { question: "Which is the largest plateau by area in the world?", answer: "Tibetan Plateau", options: ["Tibetan Plateau", "Deccan Plateau", "East African Plateau", "Antarctic Plateau"] },
  { question: "Which is the deepest point in any ocean?", answer: "Challenger Deep", options: ["Challenger Deep", "Puerto Rico Trench", "Java Trench", "Tonga Trench"] },
  { question: "Which mountain is the second-highest in the world?", answer: "K2", options: ["K2", "Kanchenjunga", "Lhotse", "Makalu"] },
  { question: "Which mountain range contains Mount Everest?", answer: "The Himalayas", options: ["The Himalayas", "The Andes", "The Alps", "The Karakoram"] },
  { question: "Which country has the most glaciers outside the polar regions?", answer: "Pakistan", options: ["Pakistan", "India", "Nepal", "China"] },
  { question: "Which is the largest sand desert in the world?", answer: "Sahara Desert", options: ["Sahara Desert", "Arabian Desert", "Thar Desert", "Kalahari Desert"] },
  { question: "Which desert covers parts of Botswana and Namibia?", answer: "Kalahari Desert", options: ["Kalahari Desert", "Sahara Desert", "Namib Desert", "Thar Desert"] },
  { question: "Which desert lies along the coast of Namibia?", answer: "Namib Desert", options: ["Namib Desert", "Kalahari Desert", "Sahara Desert", "Gobi Desert"] },
  { question: "Which is the largest rainforest in the world?", answer: "Amazon Rainforest", options: ["Amazon Rainforest", "Congo Rainforest", "Daintree Rainforest", "Sundarbans"] },
  { question: "Which is the second-largest rainforest in the world?", answer: "Congo Rainforest", options: ["Congo Rainforest", "Amazon Rainforest", "Daintree Rainforest", "Borneo Rainforest"] },
  { question: "Which is the largest mangrove forest in the world?", answer: "Sundarbans", options: ["Sundarbans", "Amazon Rainforest", "Congo Rainforest", "Daintree Rainforest"] },
  { question: "Which countries share the Sundarbans forest?", answer: "India and Bangladesh", options: ["India and Bangladesh", "India and Myanmar", "India and Nepal", "Bangladesh and Myanmar"] },
  { question: "Which is the largest salt desert in the world?", answer: "Salar de Uyuni", options: ["Salar de Uyuni", "Rann of Kutch", "Danakil Depression", "Bonneville Salt Flats"] },
  { question: "Which famous salt marsh is located in Gujarat, India?", answer: "Rann of Kutch", options: ["Rann of Kutch", "Sundarbans", "Thar Desert", "Chilika Lake"] },
  { question: "Which is the largest lagoon in India?", answer: "Chilika Lake", options: ["Chilika Lake", "Pulicat Lake", "Vembanad Lake", "Sambhar Lake"] },
  { question: "Which is the largest saltwater lake in India?", answer: "Chilika Lake", options: ["Chilika Lake", "Sambhar Lake", "Pulicat Lake", "Wular Lake"] },
  { question: "Which is the largest freshwater lake in India?", answer: "Wular Lake", options: ["Wular Lake", "Dal Lake", "Chilika Lake", "Loktak Lake"] },
  { question: "Which is the largest man-made lake in India?", answer: "Govind Sagar", options: ["Govind Sagar", "Wular Lake", "Dal Lake", "Chilika Lake"] },
  { question: "Which country has the most lakes in the world?", answer: "Canada", options: ["Canada", "Russia", "USA", "Finland"] },
  { question: "Which country is known as the 'Land of a Thousand Lakes'?", answer: "Finland", options: ["Finland", "Canada", "Sweden", "Norway"] },
  { question: "What is the deepest lake in the world?", answer: "Lake Baikal", options: ["Lake Baikal", "Caspian Sea", "Lake Tanganyika", "Lake Superior"] },
  { question: "Which lake holds the most fresh water in the world?", answer: "Lake Baikal", options: ["Lake Baikal", "Lake Superior", "Caspian Sea", "Lake Victoria"] },
  { question: "Which is the largest freshwater lake by area?", answer: "Lake Superior", options: ["Lake Superior", "Lake Victoria", "Lake Baikal", "Lake Huron"] },
  { question: "Which is the largest saltwater lake in the world?", answer: "Caspian Sea", options: ["Caspian Sea", "Dead Sea", "Aral Sea", "Great Salt Lake"] },
  { question: "Which sea is shrinking rapidly due to water use?", answer: "Aral Sea", options: ["Aral Sea", "Caspian Sea", "Dead Sea", "Black Sea"] },
  { question: "Which sea has no outlet and is extremely salty, near Israel and Jordan?", answer: "Dead Sea", options: ["Dead Sea", "Red Sea", "Caspian Sea", "Black Sea"] },
  { question: "Which strait separates Asia and North America?", answer: "Bering Strait", options: ["Bering Strait", "Malacca Strait", "Palk Strait", "Strait of Gibraltar"] },
  { question: "Which strait separates Europe and Africa?", answer: "Strait of Gibraltar", options: ["Strait of Gibraltar", "Bering Strait", "Bosphorus", "Strait of Hormuz"] },
  { question: "Which strait separates Europe and Asia at Istanbul?", answer: "Bosphorus", options: ["Bosphorus", "Strait of Gibraltar", "Bering Strait", "Strait of Malacca"] },
  { question: "Which strait is a major oil shipping route near Iran?", answer: "Strait of Hormuz", options: ["Strait of Hormuz", "Strait of Malacca", "Bosphorus", "Bering Strait"] },
  { question: "Which strait connects the Indian and Pacific Oceans near Indonesia?", answer: "Strait of Malacca", options: ["Strait of Malacca", "Strait of Hormuz", "Bering Strait", "Bosphorus"] },
  { question: "Which canal connects the Mediterranean Sea and the Red Sea?", answer: "Suez Canal", options: ["Suez Canal", "Panama Canal", "Kiel Canal", "Corinth Canal"] },
  { question: "Which canal connects the Atlantic and Pacific Oceans?", answer: "Panama Canal", options: ["Panama Canal", "Suez Canal", "Kiel Canal", "Corinth Canal"] },
  { question: "Which country built and controls the Panama Canal today?", answer: "Panama", options: ["Panama", "USA", "Colombia", "Costa Rica"] },
  { question: "Which is the world's largest coral reef system?", answer: "Great Barrier Reef", options: ["Great Barrier Reef", "Belize Barrier Reef", "Red Sea Coral Reef", "Florida Reef"] },
  { question: "Where is the Great Barrier Reef located?", answer: "Australia", options: ["Australia", "Philippines", "Indonesia", "Fiji"] },
  { question: "Which country has the most time zones due to its size?", answer: "France", options: ["France", "Russia", "USA", "UK"] },
  { question: "Which country has the highest number of neighboring countries?", answer: "China", options: ["China", "Russia", "Brazil", "India"] },
  { question: "Which two countries share the world's longest international border?", answer: "Canada and USA", options: ["Canada and USA", "USA and Mexico", "Russia and China", "India and China"] },
  { question: "Which African country is completely surrounded by South Africa?", answer: "Lesotho", options: ["Lesotho", "Eswatini", "Botswana", "Namibia"] },
  { question: "Which small country is surrounded by Italy?", answer: "Vatican City / San Marino", options: ["Vatican City / San Marino", "Monaco", "Liechtenstein", "Andorra"] },
  { question: "Which is the world's smallest country by area?", answer: "Vatican City", options: ["Vatican City", "Monaco", "San Marino", "Liechtenstein"] },
  { question: "Which is the largest landlocked country in the world?", answer: "Kazakhstan", options: ["Kazakhstan", "Mongolia", "Bolivia", "Chad"] },
  { question: "Which continent has the most landlocked countries?", answer: "Africa", options: ["Africa", "Asia", "Europe", "South America"] },
  { question: "Which is the highest capital city in the world?", answer: "La Paz, Bolivia", options: ["La Paz, Bolivia", "Quito, Ecuador", "Kathmandu, Nepal", "Thimphu, Bhutan"] },
  { question: "Which is the lowest point of land on Earth?", answer: "Dead Sea shore", options: ["Dead Sea shore", "Death Valley", "Caspian Sea shore", "Amazon Basin"] },
  { question: "Which desert has the tallest sand dunes in the world?", answer: "Namib Desert", options: ["Namib Desert", "Sahara Desert", "Gobi Desert", "Thar Desert"] },
  { question: "Which country has the world's tallest waterfall, Angel Falls?", answer: "Venezuela", options: ["Venezuela", "Brazil", "Colombia", "Guyana"] },
  { question: "Which is the largest hot spring area in the world?", answer: "Yellowstone, USA", options: ["Yellowstone, USA", "Rotorua, New Zealand", "Iceland", "Turkey"] },
  { question: "Which country has the most active geysers?", answer: "USA (Yellowstone)", options: ["USA (Yellowstone)", "Iceland", "New Zealand", "Chile"] },
  { question: "Which mountain range separates Europe from Asia in Russia?", answer: "Ural Mountains", options: ["Ural Mountains", "Caucasus Mountains", "Carpathian Mountains", "Alps"] },
  { question: "Which mountain range lies between the Black and Caspian Seas?", answer: "Caucasus Mountains", options: ["Caucasus Mountains", "Ural Mountains", "Carpathian Mountains", "Alps"] },
  { question: "Which is the highest mountain in Africa?", answer: "Mount Kilimanjaro", options: ["Mount Kilimanjaro", "Mount Kenya", "Mount Elgon", "Table Mountain"] },
  { question: "Which country is Mount Kilimanjaro located in?", answer: "Tanzania", options: ["Tanzania", "Kenya", "Uganda", "Ethiopia"] },
  { question: "Which is the highest mountain in North America?", answer: "Denali (Mount McKinley)", options: ["Denali (Mount McKinley)", "Mount Whitney", "Mount Logan", "Pikes Peak"] },
  { question: "Which is the highest mountain in South America?", answer: "Aconcagua", options: ["Aconcagua", "Chimborazo", "Huascaran", "Cotopaxi"] },
  { question: "Which is the highest mountain in Europe?", answer: "Mount Elbrus", options: ["Mount Elbrus", "Mont Blanc", "Matterhorn", "Mount Etna"] },
  { question: "Which is the highest active volcano in the world?", answer: "Ojos del Salado", options: ["Ojos del Salado", "Mount Etna", "Mount Fuji", "Krakatoa"] },
  { question: "Which country has the most volcanoes overall?", answer: "Indonesia", options: ["Indonesia", "Japan", "USA", "Philippines"] },
  { question: "Which sea separates India and East Africa broadly?", answer: "Indian Ocean", options: ["Indian Ocean", "Arabian Sea", "Red Sea", "Persian Gulf"] },
  { question: "Which country's coastline is the longest in the world?", answer: "Canada", options: ["Canada", "Indonesia", "Russia", "Norway"] },
  { question: "Which state in India has the largest number of rivers?", answer: "Assam", options: ["Assam", "Kerala", "West Bengal", "Odisha"] },
  { question: "Which Indian river is known as the 'Sorrow of Bengal'?", answer: "Damodar", options: ["Damodar", "Hooghly", "Kosi", "Teesta"] },
  { question: "Which Indian river is called 'Dakshin Ganga'?", answer: "Godavari", options: ["Godavari", "Krishna", "Kaveri", "Narmada"] },
  { question: "Which Indian mountain pass connects India and China in Sikkim?", answer: "Nathu La", options: ["Nathu La", "Rohtang Pass", "Zoji La", "Khardung La"] },
  { question: "Which is the highest motorable pass in India?", answer: "Khardung La", options: ["Khardung La", "Rohtang Pass", "Nathu La", "Zoji La"] },
  { question: "Which is the world's largest river island?", answer: "Majuli, India", options: ["Majuli, India", "Ilha do Bananal", "Marajo Island", "Manhattan"] },
  { question: "Which river is Majuli island located in?", answer: "Brahmaputra", options: ["Brahmaputra", "Ganga", "Yamuna", "Godavari"] },
  { question: "Which is the largest delta in the world?", answer: "Sundarbans Delta", options: ["Sundarbans Delta", "Nile Delta", "Mississippi Delta", "Mekong Delta"] },

]);
