/* ============================================================
   🗺️  GEOGRAPHY — Class 2
   ------------------------------------------------------------
   HOW TO EDIT THIS FILE
   • Each { ... } line below is ONE question.
   • Keep this exact shape:
       { question: "your question?", answer: "Correct", options: ["Correct","B","C","D"] }
   • RULES:
       - Give exactly 4 options.
       - The "answer" text must EXACTLY match one of the 4 options.
       - Wrap text in "double quotes". If your text has a " inside it,
         write it as \" (a backslash then a quote).
   • Add or delete question lines freely.
   • Save the file, then refresh the quiz page — changes appear instantly.
   ============================================================ */
registerQuiz("geography", 2, [
  { question: "How many directions?", answer: "4", options: ["4", "3", "5", "6"] },
  { question: "Direction opposite to East?", answer: "West", options: ["West", "North", "South", "Up"] },
  { question: "Direction opposite to North?", answer: "South", options: ["South", "East", "West", "Up"] },
  { question: "How many continents?", answer: "7", options: ["7", "5", "6", "8"] },
  { question: "How many oceans?", answer: "5", options: ["5", "4", "6", "7"] },
  { question: "Largest continent?", answer: "Asia", options: ["Asia", "Africa", "Europe", "Antarctica"] },
  { question: "Smallest continent?", answer: "Australia", options: ["Australia", "Europe", "Asia", "Antarctica"] },
  { question: "Largest ocean?", answer: "Pacific", options: ["Pacific", "Atlantic", "Indian", "Arctic"] },
  { question: "Smallest ocean?", answer: "Arctic", options: ["Arctic", "Atlantic", "Indian", "Pacific"] },
  { question: "India is in which continent?", answer: "Asia", options: ["Asia", "Africa", "Europe", "Australia"] },
  { question: "Egypt is in which continent?", answer: "Africa", options: ["Africa", "Asia", "Europe", "America"] },
  { question: "France is in which continent?", answer: "Europe", options: ["Europe", "Asia", "Africa", "America"] },
  { question: "USA is in which continent?", answer: "North America", options: ["North America", "South America", "Europe", "Asia"] },
  { question: "Brazil is in which continent?", answer: "South America", options: ["South America", "North America", "Africa", "Asia"] },
  { question: "Coldest continent?", answer: "Antarctica", options: ["Antarctica", "Africa", "Asia", "Australia"] },
  { question: "Hottest continent?", answer: "Africa", options: ["Africa", "Asia", "Antarctica", "Europe"] },
  { question: "Country with Eiffel Tower?", answer: "France", options: ["France", "Italy", "UK", "Germany"] },
  { question: "Country with Great Wall?", answer: "China", options: ["China", "Japan", "India", "Korea"] },
  { question: "Country with Statue of Liberty?", answer: "USA", options: ["USA", "UK", "France", "Russia"] },
  { question: "Country with Pyramids?", answer: "Egypt", options: ["Egypt", "India", "Mexico", "Greece"] },
  { question: "Which continent is the smallest by population among the 7?", answer: "Antarctica", options: ["Antarctica", "Australia", "Europe", "Africa"] },
  { question: "Which continent has the most countries?", answer: "Africa", options: ["Africa", "Asia", "Europe", "South America"] },
  { question: "Which continent is known as the 'Dark Continent'?", answer: "Africa", options: ["Africa", "Asia", "Europe", "Australia"] },
  { question: "Which continent is India part of?", answer: "Asia", options: ["Asia", "Africa", "Europe", "Australia"] },
  { question: "Which is the second-largest continent?", answer: "Africa", options: ["Africa", "Asia", "North America", "South America"] },
  { question: "Which is the third-largest continent?", answer: "North America", options: ["North America", "Africa", "South America", "Europe"] },
  { question: "Which continent has no permanent human residents?", answer: "Antarctica", options: ["Antarctica", "Australia", "Asia", "Europe"] },
  { question: "Which ocean lies between America and Europe/Africa?", answer: "Atlantic Ocean", options: ["Atlantic Ocean", "Pacific Ocean", "Indian Ocean", "Arctic Ocean"] },
  { question: "Which ocean is closest to India?", answer: "Indian Ocean", options: ["Indian Ocean", "Pacific Ocean", "Atlantic Ocean", "Arctic Ocean"] },
  { question: "Which ocean is the coldest?", answer: "Arctic Ocean", options: ["Arctic Ocean", "Pacific Ocean", "Indian Ocean", "Atlantic Ocean"] },
  { question: "Which country has the most people in the world?", answer: "India", options: ["India", "China", "USA", "Indonesia"] },
  { question: "Which country has the largest area in the world?", answer: "Russia", options: ["Russia", "Canada", "China", "USA"] },
  { question: "Which is the second-largest country by area?", answer: "Canada", options: ["Canada", "USA", "China", "Brazil"] },
  { question: "Which country is known as the Land of the Rising Sun?", answer: "Japan", options: ["Japan", "China", "Korea", "Thailand"] },
  { question: "Which country is famous for the Kangaroo?", answer: "Australia", options: ["Australia", "New Zealand", "South Africa", "India"] },
  { question: "Which country is famous for the Maple Leaf flag?", answer: "Canada", options: ["Canada", "USA", "UK", "France"] },
  { question: "Which country is home to the Amazon rainforest mainly?", answer: "Brazil", options: ["Brazil", "Peru", "Colombia", "Argentina"] },
  { question: "Which country has the Sahara Desert mostly?", answer: "Algeria", options: ["Algeria", "Egypt", "Libya", "Morocco"] },
  { question: "Which country is shaped like a boot?", answer: "Italy", options: ["Italy", "Spain", "Greece", "Portugal"] },
  { question: "Which country has the Big Ben clock tower?", answer: "UK", options: ["UK", "France", "Germany", "Ireland"] },
  { question: "Which country is famous for tulips and windmills?", answer: "Netherlands", options: ["Netherlands", "Belgium", "Denmark", "Germany"] },
  { question: "Which country has the most time zones?", answer: "Russia", options: ["Russia", "USA", "China", "France"] },
  { question: "Which is the smallest continent?", answer: "Australia", options: ["Australia", "Europe", "Antarctica", "South America"] },
  { question: "Which African country is famous for the Great Pyramids?", answer: "Egypt", options: ["Egypt", "Sudan", "Libya", "Morocco"] },
  { question: "What is the name of the desert in Australia?", answer: "Outback", options: ["Outback", "Sahara", "Thar", "Gobi"] },
  { question: "Which sea lies between Europe and Africa mostly?", answer: "Mediterranean Sea", options: ["Mediterranean Sea", "Red Sea", "Black Sea", "Caspian Sea"] },
  { question: "Which mountain range is in Europe, famous for skiing?", answer: "The Alps", options: ["The Alps", "The Himalayas", "The Andes", "The Rockies"] },
  { question: "Which mountain range runs through South America?", answer: "The Andes", options: ["The Andes", "The Alps", "The Himalayas", "The Rockies"] },
  { question: "Which mountain range is in North America?", answer: "The Rockies", options: ["The Rockies", "The Alps", "The Andes", "The Himalayas"] },
  { question: "What is the world's longest mountain range?", answer: "The Andes", options: ["The Andes", "The Alps", "The Himalayas", "The Rockies"] },
  { question: "What is the world's largest hot desert?", answer: "Sahara", options: ["Sahara", "Thar", "Gobi", "Kalahari"] },
  { question: "What is the largest cold desert in the world?", answer: "Antarctic Desert", options: ["Antarctic Desert", "Sahara", "Gobi", "Thar"] },
  { question: "Which river is the longest in the world?", answer: "Nile", options: ["Nile", "Amazon", "Ganga", "Yangtze"] },
  { question: "Which river carries the most water in the world?", answer: "Amazon", options: ["Amazon", "Nile", "Ganga", "Mississippi"] },
  { question: "Which river flows through many countries in Europe?", answer: "Danube", options: ["Danube", "Nile", "Amazon", "Volga"] },
  { question: "Which river is sacred to Hindus in India?", answer: "Ganga", options: ["Ganga", "Yamuna", "Godavari", "Krishna"] },
  { question: "What is the name of the biggest island in the world?", answer: "Greenland", options: ["Greenland", "Madagascar", "Borneo", "Iceland"] },
  { question: "Which country is entirely an island continent?", answer: "Australia", options: ["Australia", "New Zealand", "Madagascar", "Japan"] },
  { question: "Which line divides Earth into Northern and Southern halves?", answer: "Equator", options: ["Equator", "Prime Meridian", "Tropic of Cancer", "International Date Line"] },
  { question: "How many continents are there on Earth?", answer: "7", options: ["7", "5", "6", "8"] },
  { question: "How many oceans are there on Earth?", answer: "5", options: ["5", "3", "4", "6"] },
  { question: "Which is the warmest ocean?", answer: "Indian Ocean", options: ["Indian Ocean", "Arctic Ocean", "Southern Ocean", "Pacific Ocean"] },
  { question: "What do we call the imaginary lines running east-west on a map?", answer: "Latitudes", options: ["Latitudes", "Longitudes", "Borders", "Meridians"] },
  { question: "What do we call the imaginary lines running north-south on a map?", answer: "Longitudes", options: ["Longitudes", "Latitudes", "Borders", "Parallels"] },
  { question: "Which continent is home to the Great Barrier Reef?", answer: "Australia", options: ["Australia", "Asia", "Africa", "Europe"] },
  { question: "Which is the driest continent (besides Antarctica)?", answer: "Australia", options: ["Australia", "Asia", "Africa", "Europe"] },
  { question: "Which country has both Asia and Europe parts?", answer: "Russia", options: ["Russia", "Turkey", "Egypt", "Kazakhstan"] },
  { question: "Which country lies between Europe and Asia and is called a bridge?", answer: "Turkey", options: ["Turkey", "Russia", "Egypt", "Iran"] },
  { question: "Which continent has the Amazon rainforest?", answer: "South America", options: ["South America", "Africa", "Asia", "North America"] },
  { question: "What is the capital city known for Big Ben?", answer: "London", options: ["London", "Paris", "Berlin", "Rome"] },
  { question: "What is the name of the famous canal connecting the Mediterranean and Red seas?", answer: "Suez Canal", options: ["Suez Canal", "Panama Canal", "Erie Canal", "Kiel Canal"] },
  { question: "What is the name of the famous canal in Central America?", answer: "Panama Canal", options: ["Panama Canal", "Suez Canal", "Erie Canal", "Kiel Canal"] },
  { question: "Which country has the most active volcanoes?", answer: "Indonesia", options: ["Indonesia", "Japan", "Philippines", "USA"] },
  { question: "Which is the tallest waterfall in the world?", answer: "Angel Falls", options: ["Angel Falls", "Niagara Falls", "Victoria Falls", "Iguazu Falls"] },
  { question: "Which famous waterfall is on the border of USA and Canada?", answer: "Niagara Falls", options: ["Niagara Falls", "Angel Falls", "Victoria Falls", "Iguazu Falls"] },
  { question: "Which famous waterfall is in Africa?", answer: "Victoria Falls", options: ["Victoria Falls", "Niagara Falls", "Angel Falls", "Iguazu Falls"] },
  { question: "Which is the largest freshwater lake by area?", answer: "Lake Superior", options: ["Lake Superior", "Lake Victoria", "Lake Baikal", "Caspian Sea"] },
  { question: "Which lake in Africa is the largest?", answer: "Lake Victoria", options: ["Lake Victoria", "Lake Chad", "Lake Tanganyika", "Lake Malawi"] },
  { question: "What is the world's deepest ocean trench?", answer: "Mariana Trench", options: ["Mariana Trench", "Java Trench", "Puerto Rico Trench", "Peru-Chile Trench"] },
  { question: "Which country is famous for the Great Wall?", answer: "China", options: ["China", "Japan", "Korea", "Mongolia"] },
  { question: "Which country is famous for the Eiffel Tower?", answer: "France", options: ["France", "Italy", "Spain", "Germany"] },
  { question: "Which country is famous for the Colosseum?", answer: "Italy", options: ["Italy", "Greece", "Spain", "France"] },
  { question: "Which country is famous for the Taj Mahal?", answer: "India", options: ["India", "Pakistan", "Bangladesh", "Nepal"] },
  { question: "Which country is famous for kangaroos and koalas?", answer: "Australia", options: ["Australia", "New Zealand", "South Africa", "Brazil"] },
  { question: "Which country is famous for the Statue of Liberty?", answer: "USA", options: ["USA", "UK", "France", "Canada"] },
  { question: "Which country is home to Mount Fuji?", answer: "Japan", options: ["Japan", "China", "Korea", "Philippines"] },
  { question: "Which country has the most population in Africa?", answer: "Nigeria", options: ["Nigeria", "Egypt", "Ethiopia", "South Africa"] },
  { question: "Which is the largest country in South America?", answer: "Brazil", options: ["Brazil", "Argentina", "Peru", "Colombia"] },
  { question: "Which continent is the coldest?", answer: "Antarctica", options: ["Antarctica", "Europe", "Asia", "North America"] },
  { question: "Which continent has the most rainforests?", answer: "South America", options: ["South America", "Africa", "Asia", "Australia"] },
  { question: "Which sea is the saltiest in the world?", answer: "Dead Sea", options: ["Dead Sea", "Red Sea", "Black Sea", "Caspian Sea"] },
  { question: "Which desert is the largest cold desert in Asia?", answer: "Gobi Desert", options: ["Gobi Desert", "Thar Desert", "Sahara Desert", "Kalahari Desert"] },
  { question: "Which country has both a desert and snowy mountains famously?", answer: "China", options: ["China", "Japan", "Sri Lanka", "Singapore"] },
  { question: "Which country's flag has a maple leaf?", answer: "Canada", options: ["Canada", "USA", "UK", "Australia"] },
  { question: "What is the name of Earth's only natural satellite?", answer: "Moon", options: ["Moon", "Sun", "Mars", "Venus"] },
  { question: "Which is the closest planet to the sun?", answer: "Mercury", options: ["Mercury", "Venus", "Earth", "Mars"] },
  { question: "What do we call people who study maps and places?", answer: "Geographers", options: ["Geographers", "Astronomers", "Historians", "Biologists"] },
  { question: "What is the name for the boundary line between two countries?", answer: "Border", options: ["Border", "Coast", "Equator", "Bridge"] },
  { question: "Which country is an island nation famous for sushi?", answer: "Japan", options: ["Japan", "China", "Korea", "Vietnam"] },
  { question: "Which country is famous for the Leaning Tower of Pisa?", answer: "Italy", options: ["Italy", "France", "Spain", "Greece"] },


]);
