/* ============================================================
   🏛️  CAPITALS — Class 3
   ------------------------------------------------------------
   HOW TO EDIT THIS FILE
   • Each { ... } line below is ONE question.
   • Keep this exact shape:
       { question: "your question?", answer: "Correct", options: ["Correct","B","C","D"] }
   • RULES:
       - Give exactly 4 options.
       - The "answer" text must EXACTLY match one of the 4 options.
       - Wrap text in "double quotes". If your text has a " inside it,
         write it as \" (a backslash then a quote).
   • Add or delete question lines freely.
   • Save the file, then refresh the quiz page — changes appear instantly.
   ============================================================ */
registerQuiz("capitals", 3, [
  { question: "Capital of Pakistan?", answer: "Islamabad", options: ["Islamabad", "Karachi", "Lahore", "Peshawar"] },
  { question: "Capital of Bangladesh?", answer: "Dhaka", options: ["Dhaka", "Chittagong", "Khulna", "Sylhet"] },
  { question: "Capital of Sri Lanka?", answer: "Colombo (commercial) / Sri Jayawardenepura Kotte (admin)", options: ["Colombo (commercial) / Sri Jayawardenepura Kotte (admin)", "Kandy", "Galle", "Jaffna"] },
  { question: "Capital of Nepal?", answer: "Kathmandu", options: ["Kathmandu", "Pokhara", "Lalitpur", "Bhaktapur"] },
  { question: "Capital of Bhutan?", answer: "Thimphu", options: ["Thimphu", "Paro", "Punakha", "Phuentsholing"] },
  { question: "Capital of Myanmar?", answer: "Naypyidaw", options: ["Naypyidaw", "Yangon", "Mandalay", "Bagan"] },
  { question: "Capital of Afghanistan?", answer: "Kabul", options: ["Kabul", "Kandahar", "Herat", "Mazar"] },
  { question: "Capital of Iran?", answer: "Tehran", options: ["Tehran", "Isfahan", "Mashhad", "Shiraz"] },
  { question: "Capital of Iraq?", answer: "Baghdad", options: ["Baghdad", "Basra", "Mosul", "Erbil"] },
  { question: "Capital of Saudi Arabia?", answer: "Riyadh", options: ["Riyadh", "Jeddah", "Mecca", "Medina"] },
  { question: "Capital of UAE?", answer: "Abu Dhabi", options: ["Abu Dhabi", "Dubai", "Sharjah", "Ajman"] },
  { question: "Capital of Turkey?", answer: "Ankara", options: ["Ankara", "Istanbul", "Izmir", "Bursa"] },
  { question: "Capital of Indonesia?", answer: "Jakarta (also Nusantara new)", options: ["Jakarta (also Nusantara new)", "Bali", "Surabaya", "Medan"] },
  { question: "Capital of Malaysia?", answer: "Kuala Lumpur", options: ["Kuala Lumpur", "Penang", "Johor Bahru", "Kuching"] },
  { question: "Capital of Thailand?", answer: "Bangkok", options: ["Bangkok", "Chiang Mai", "Phuket", "Pattaya"] },
  { question: "Capital of Vietnam?", answer: "Hanoi", options: ["Hanoi", "Ho Chi Minh", "Da Nang", "Hue"] },
  { question: "Capital of South Korea?", answer: "Seoul", options: ["Seoul", "Busan", "Incheon", "Daegu"] },
  { question: "Capital of North Korea?", answer: "Pyongyang", options: ["Pyongyang", "Hamhung", "Chongjin", "Kaesong"] },
  { question: "Capital of Singapore?", answer: "Singapore", options: ["Singapore", "Kuala Lumpur", "Manila", "Bangkok"] },
  { question: "Capital of Philippines?", answer: "Manila", options: ["Manila", "Cebu", "Davao", "Quezon"] },
  { question: "Capital of Kazakhstan?", answer: "Astana", options: ["Astana", "Almaty", "Shymkent", "Karaganda"] },
  { question: "Capital of India's neighbour China's region Tibet capital city?", answer: "Lhasa", options: ["Lhasa", "Shigatse", "Nyingchi", "Chamdo"] },
  { question: "Capital of Hong Kong (special administrative region)?", answer: "Hong Kong", options: ["Hong Kong", "Kowloon", "Macau", "Shenzhen"] },
  { question: "Capital of Macau?", answer: "Macau", options: ["Macau", "Taipa", "Coloane", "Zhuhai"] },
  { question: "Capital of Taiwan?", answer: "Taipei", options: ["Taipei", "Kaohsiung", "Taichung", "Tainan"] },
  { question: "Which country's capital is Canberra?", answer: "Australia", options: ["Australia", "Austria", "New Zealand", "Ireland"] },
  { question: "Which country's capital is Ottawa?", answer: "Canada", options: ["Canada", "USA", "Mexico", "Cuba"] },
  { question: "Which country's capital is Cairo?", answer: "Egypt", options: ["Egypt", "Sudan", "Libya", "Ethiopia"] },
  { question: "Which country's capital is Brasilia?", answer: "Brazil", options: ["Brazil", "Argentina", "Peru", "Chile"] },
  { question: "Which country's capital is Wellington?", answer: "New Zealand", options: ["New Zealand", "Australia", "Fiji", "Samoa"] },
  { question: "Which country's capital is Bern?", answer: "Switzerland", options: ["Switzerland", "Austria", "Belgium", "Sweden"] },
  { question: "Which country's capital is Ankara?", answer: "Turkey", options: ["Turkey", "Greece", "Syria", "Iran"] },
  { question: "Which country's capital is Nairobi?", answer: "Kenya", options: ["Kenya", "Nigeria", "Ghana", "Uganda"] },
  { question: "Which country's capital is Jakarta?", answer: "Indonesia", options: ["Indonesia", "Malaysia", "Thailand", "Vietnam"] },
  { question: "Which country's capital is Seoul?", answer: "South Korea", options: ["South Korea", "North Korea", "Japan", "China"] },
  { question: "Capital of India's Delhi region full name?", answer: "National Capital Territory of Delhi", options: ["National Capital Territory of Delhi", "Delhi State", "Old Delhi", "New Delhi City"] },
  { question: "Capital of Jharkhand?", answer: "Ranchi", options: ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro"] },
  { question: "Capital of Chhattisgarh?", answer: "Raipur", options: ["Raipur", "Bhilai", "Bilaspur", "Korba"] },
  { question: "Capital of Arunachal Pradesh?", answer: "Itanagar", options: ["Itanagar", "Naharlagun", "Tawang", "Pasighat"] },
  { question: "Capital of Assam?", answer: "Dispur", options: ["Dispur", "Guwahati", "Silchar", "Jorhat"] },
  { question: "Capital of Yemen's neighbour Oman?", answer: "Muscat", options: ["Muscat", "Salalah", "Sohar", "Nizwa"] },
  { question: "Capital of Bahrain (island nation)?", answer: "Manama", options: ["Manama", "Muharraq", "Riffa", "Sitra"] },
  { question: "Capital of Palestine?", answer: "Ramallah", options: ["Ramallah", "Gaza City", "Bethlehem", "Hebron"] },
  { question: "Capital of Kuwait (Gulf nation)?", answer: "Kuwait City", options: ["Kuwait City", "Al Jahra", "Salmiya", "Hawalli"] },
  { question: "Capital of Sri Lanka's legislative capital?", answer: "Sri Jayawardenepura Kotte", options: ["Sri Jayawardenepura Kotte", "Colombo", "Kandy", "Galle"] },
  { question: "Capital of Malaysia's federal territory (administrative)?", answer: "Putrajaya", options: ["Putrajaya", "Kuala Lumpur", "Penang", "Johor Bahru"] },
  { question: "Capital of Myanmar's former capital?", answer: "Yangon", options: ["Yangon", "Naypyidaw", "Mandalay", "Bago"] },
  { question: "Capital of India's former capital under British rule?", answer: "Calcutta", options: ["Calcutta", "Delhi", "Bombay", "Madras"] },
  { question: "Capital of Nepal's largest city and capital?", answer: "Kathmandu", options: ["Kathmandu", "Pokhara", "Lalitpur", "Biratnagar"] },
  { question: "Capital of China's financial hub (not capital)?", answer: "Shanghai", options: ["Shanghai", "Beijing", "Guangzhou", "Shenzhen"] },
  { question: "Which sea does Mumbai lie near?", answer: "Arabian Sea", options: ["Arabian Sea", "Bay of Bengal", "Indian Ocean", "Red Sea"] },
  { question: "Kolkata lies on which river?", answer: "Hooghly", options: ["Hooghly", "Yamuna", "Godavari", "Krishna"] },
  { question: "Country whose capital is Male?", answer: "Maldives", options: ["Maldives", "Mauritius", "Seychelles", "Sri Lanka"] },
  { question: "Country whose capital is Thimphu?", answer: "Bhutan", options: ["Bhutan", "Nepal", "Tibet", "Sikkim"] },
  { question: "Country whose capital is Kathmandu?", answer: "Nepal", options: ["Nepal", "Bhutan", "India", "Tibet"] },
  { question: "Country whose capital is Dhaka?", answer: "Bangladesh", options: ["Bangladesh", "Myanmar", "India", "Nepal"] },
  { question: "Country whose capital is Islamabad?", answer: "Pakistan", options: ["Pakistan", "Afghanistan", "Iran", "India"] },
  { question: "Country whose capital is Kabul?", answer: "Afghanistan", options: ["Afghanistan", "Pakistan", "Iran", "Tajikistan"] },
  { question: "Country whose capital is Naypyidaw?", answer: "Myanmar", options: ["Myanmar", "Thailand", "Laos", "Vietnam"] },
  { question: "Country whose capital is Bangkok?", answer: "Thailand", options: ["Thailand", "Vietnam", "Laos", "Cambodia"] },
  { question: "Country whose capital is Hanoi?", answer: "Vietnam", options: ["Vietnam", "Laos", "Cambodia", "Thailand"] },
  { question: "Country whose capital is Manila?", answer: "Philippines", options: ["Philippines", "Indonesia", "Malaysia", "Vietnam"] },
  { question: "Country whose capital is Kuala Lumpur?", answer: "Malaysia", options: ["Malaysia", "Singapore", "Indonesia", "Brunei"] },
  { question: "Country whose capital is Beijing?", answer: "China", options: ["China", "Japan", "Mongolia", "South Korea"] },
  { question: "Country whose capital is Tokyo?", answer: "Japan", options: ["Japan", "South Korea", "China", "Taiwan"] },
  { question: "Country whose capital is Moscow?", answer: "Russia", options: ["Russia", "Ukraine", "Belarus", "Kazakhstan"] },
  { question: "Country whose capital is New Delhi?", answer: "India", options: ["India", "Pakistan", "Bangladesh", "Nepal"] },
  { question: "India's smallest state by area?", answer: "Goa", options: ["Goa", "Sikkim", "Tripura", "Kerala"] },
  { question: "Rajasthan's famous Pink City is which city?", answer: "Jaipur", options: ["Jaipur", "Udaipur", "Jodhpur", "Bikaner"] },
  { question: "Rajasthan's Blue City is which city?", answer: "Jodhpur", options: ["Jodhpur", "Jaipur", "Udaipur", "Ajmer"] },
  { question: "Which city is known as the City of Lakes?", answer: "Udaipur", options: ["Udaipur", "Jaipur", "Jodhpur", "Bikaner"] },
  { question: "Which Indian city is called the Silicon Valley of India?", answer: "Bengaluru", options: ["Bengaluru", "Hyderabad", "Pune", "Chennai"] },
  { question: "Which UAE city is the business hub (not capital)?", answer: "Dubai", options: ["Dubai", "Abu Dhabi", "Sharjah", "Ajman"] },
  { question: "Which Pakistani city was once its capital?", answer: "Karachi", options: ["Karachi", "Lahore", "Peshawar", "Multan"] },
  { question: "Which Turkish city was once its capital?", answer: "Istanbul", options: ["Istanbul", "Izmir", "Antalya", "Bursa"] },
  { question: "Which Brazilian city was once its capital?", answer: "Rio de Janeiro", options: ["Rio de Janeiro", "Sao Paulo", "Salvador", "Recife"] },
  { question: "Which Nigerian city was once its capital?", answer: "Lagos", options: ["Lagos", "Kano", "Ibadan", "Port Harcourt"] },
  { question: "Which South African city holds the parliament?", answer: "Cape Town", options: ["Cape Town", "Pretoria", "Johannesburg", "Durban"] },
  { question: "Which South African city is the judicial capital?", answer: "Bloemfontein", options: ["Bloemfontein", "Pretoria", "Cape Town", "Durban"] },
  { question: "Israel's largest city (not capital)?", answer: "Tel Aviv", options: ["Tel Aviv", "Haifa", "Eilat", "Jerusalem"] },
  { question: "Which US city was the first capital of the USA?", answer: "New York City", options: ["New York City", "Philadelphia", "Boston", "Washington D.C."] },
  { question: "Which Canadian province's capital is Toronto?", answer: "Ontario", options: ["Ontario", "Quebec", "British Columbia", "Alberta"] },
  { question: "Which Australian city is the capital of New South Wales?", answer: "Sydney", options: ["Sydney", "Melbourne", "Brisbane", "Perth"] },
  { question: "Which Australian city is the capital of Victoria?", answer: "Melbourne", options: ["Melbourne", "Sydney", "Adelaide", "Hobart"] },
  { question: "Egypt's ancient capital in the pharaoh era?", answer: "Memphis", options: ["Memphis", "Thebes", "Alexandria", "Giza"] },
  { question: "Iraq's ancient capital of Babylonia?", answer: "Babylon", options: ["Babylon", "Nineveh", "Ur", "Uruk"] },
  { question: "Greece's ancient city-state famed for warriors?", answer: "Sparta", options: ["Sparta", "Athens", "Corinth", "Thebes"] },
  { question: "Italy's ancient empire's capital?", answer: "Rome", options: ["Rome", "Milan", "Naples", "Venice"] },
  { question: "Which city is home to the UN headquarters?", answer: "New York City", options: ["New York City", "Washington D.C.", "Geneva", "The Hague"] },
  { question: "Which city hosts the International Court of Justice?", answer: "The Hague", options: ["The Hague", "Geneva", "Brussels", "Amsterdam"] },
  { question: "Which Swiss city hosts many UN offices?", answer: "Geneva", options: ["Geneva", "Zurich", "Bern", "Basel"] },
  { question: "Which Belgian city is the EU headquarters?", answer: "Brussels", options: ["Brussels", "Antwerp", "Ghent", "Bruges"] },
  { question: "India's financial capital?", answer: "Mumbai", options: ["Mumbai", "New Delhi", "Kolkata", "Chennai"] },
  { question: "India's IT capital?", answer: "Bengaluru", options: ["Bengaluru", "Hyderabad", "Chennai", "Pune"] },
  { question: "Which city is called the City of Nawabs?", answer: "Lucknow", options: ["Lucknow", "Hyderabad", "Bhopal", "Delhi"] },
  { question: "Which city is called the City of Joy?", answer: "Kolkata", options: ["Kolkata", "Mumbai", "Chennai", "Delhi"] },
  { question: "Which city is called the Pearl City of India?", answer: "Hyderabad", options: ["Hyderabad", "Chennai", "Surat", "Jaipur"] },
  { question: "Which city is called the Garden City of India?", answer: "Bengaluru", options: ["Bengaluru", "Chandigarh", "Mysuru", "Pune"] },
  { question: "Which city is known as the Gateway of India?", answer: "Mumbai", options: ["Mumbai", "Chennai", "Kolkata", "Goa"] },
  { question: "Which city is home to the Taj Mahal?", answer: "Agra", options: ["Agra", "Lucknow", "Delhi", "Jaipur"] },
  { question: "Which city hosts the Kumbh Mela most famously?", answer: "Prayagraj", options: ["Prayagraj", "Haridwar", "Nashik", "Ujjain"] },
  { question: "Which holy city lies on the Ganga in UP?", answer: "Varanasi", options: ["Varanasi", "Prayagraj", "Ayodhya", "Mathura"] },

]);
