/* ============================================================
   🏛️  CAPITALS — Class 2
   ------------------------------------------------------------
   HOW TO EDIT THIS FILE
   • Each { ... } line below is ONE question.
   • Keep this exact shape:
       { question: "your question?", answer: "Correct", options: ["Correct","B","C","D"] }
   • RULES:
       - Give exactly 4 options.
       - The "answer" text must EXACTLY match one of the 4 options.
       - Wrap text in "double quotes". If your text has a " inside it,
         write it as \" (a backslash then a quote).
   • Add or delete question lines freely.
   • Save the file, then refresh the quiz page — changes appear instantly.
   ============================================================ */
registerQuiz("capitals", 2, [
  { question: "Capital of Jharkhand?", answer: "Ranchi", options: ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro"] },
  { question: "Capital of Chhattisgarh?", answer: "Raipur", options: ["Raipur", "Bilaspur", "Korba", "Durg"] },
  { question: "Capital of Tripura?", answer: "Agartala", options: ["Agartala", "Udaipur", "Kailashahar", "Dharmanagar"] },
  { question: "Capital of Manipur?", answer: "Imphal", options: ["Imphal", "Thoubal", "Bishnupur", "Senapati"] },
  { question: "Capital of Meghalaya?", answer: "Shillong", options: ["Shillong", "Tura", "Jowai", "Nongstoin"] },
  { question: "Capital of Mizoram?", answer: "Aizawl", options: ["Aizawl", "Lunglei", "Champhai", "Kolasib"] },
  { question: "Capital of Nagaland?", answer: "Kohima", options: ["Kohima", "Dimapur", "Mokokchung", "Wokha"] },
  { question: "Capital of Sikkim?", answer: "Gangtok", options: ["Gangtok", "Pelling", "Namchi", "Mangan"] },
  { question: "Capital of Arunachal Pradesh?", answer: "Itanagar", options: ["Itanagar", "Tawang", "Pasighat", "Naharlagun"] },
  { question: "Capital of USA?", answer: "Washington DC", options: ["Washington DC", "New York", "LA", "Chicago"] },
  { question: "Capital of UK?", answer: "London", options: ["London", "Manchester", "Liverpool", "Birmingham"] },
  { question: "Capital of France?", answer: "Paris", options: ["Paris", "Lyon", "Marseille", "Nice"] },
  { question: "Capital of Japan?", answer: "Tokyo", options: ["Tokyo", "Osaka", "Kyoto", "Nagoya"] },
  { question: "Capital of China?", answer: "Beijing", options: ["Beijing", "Shanghai", "Guangzhou", "Shenzhen"] },
  { question: "Capital of Russia?", answer: "Moscow", options: ["Moscow", "St Petersburg", "Kazan", "Sochi"] },
  { question: "Capital of Germany?", answer: "Berlin", options: ["Berlin", "Munich", "Frankfurt", "Hamburg"] },
  { question: "Capital of Italy?", answer: "Rome", options: ["Rome", "Milan", "Naples", "Turin"] },
  { question: "Capital of Spain?", answer: "Madrid", options: ["Madrid", "Barcelona", "Valencia", "Seville"] },
  { question: "Capital of Australia?", answer: "Canberra", options: ["Canberra", "Sydney", "Melbourne", "Perth"] },
  { question: "Capital of Canada?", answer: "Ottawa", options: ["Ottawa", "Toronto", "Vancouver", "Montreal"] },
  { question: "Capital of Zimbabwe?", answer: "Harare", options: ["Harare", "Bulawayo", "Gweru", "Mutare"] },
  { question: "Capital of Zambia?", answer: "Lusaka", options: ["Lusaka", "Ndola", "Kitwe", "Livingstone"] },
  { question: "Capital of Uganda?", answer: "Kampala", options: ["Kampala", "Entebbe", "Gulu", "Jinja"] },
  { question: "Capital of Angola?", answer: "Luanda", options: ["Luanda", "Huambo", "Lobito", "Benguela"] },
  { question: "Capital of Mozambique?", answer: "Maputo", options: ["Maputo", "Beira", "Nampula", "Matola"] },
  { question: "Capital of Rwanda?", answer: "Kigali", options: ["Kigali", "Butare", "Gisenyi", "Ruhengeri"] },
  { question: "Capital of Somalia?", answer: "Mogadishu", options: ["Mogadishu", "Hargeisa", "Kismayo", "Baidoa"] },
  { question: "Capital of Sudan?", answer: "Khartoum", options: ["Khartoum", "Omdurman", "Port Sudan", "Kassala"] },
  { question: "Capital of Libya?", answer: "Tripoli", options: ["Tripoli", "Benghazi", "Misrata", "Sabha"] },
  { question: "Capital of Tunisia?", answer: "Tunis", options: ["Tunis", "Sfax", "Sousse", "Kairouan"] },
  { question: "Capital of Algeria?", answer: "Algiers", options: ["Algiers", "Oran", "Constantine", "Annaba"] },
  { question: "Capital of Senegal?", answer: "Dakar", options: ["Dakar", "Thies", "Kaolack", "Saint-Louis"] },
  { question: "Capital of Ivory Coast?", answer: "Yamoussoukro", options: ["Yamoussoukro", "Abidjan", "Bouake", "Daloa"] },
  { question: "Capital of Cameroon?", answer: "Yaounde", options: ["Yaounde", "Douala", "Garoua", "Bamenda"] },
  { question: "Capital of Madagascar?", answer: "Antananarivo", options: ["Antananarivo", "Toamasina", "Mahajanga", "Fianarantsoa"] },
  { question: "Capital of Botswana?", answer: "Gaborone", options: ["Gaborone", "Francistown", "Molepolole", "Maun"] },
  { question: "Capital of Namibia?", answer: "Windhoek", options: ["Windhoek", "Walvis Bay", "Swakopmund", "Oshakati"] },
  { question: "Capital of Malawi?", answer: "Lilongwe", options: ["Lilongwe", "Blantyre", "Mzuzu", "Zomba"] },
  { question: "Capital of Mali?", answer: "Bamako", options: ["Bamako", "Segou", "Sikasso", "Mopti"] },
  { question: "Capital of Niger?", answer: "Niamey", options: ["Niamey", "Zinder", "Maradi", "Agadez"] },
  { question: "Capital of Bolivia?", answer: "Sucre", options: ["Sucre", "La Paz", "Santa Cruz", "Cochabamba"] },
  { question: "Capital of Ecuador?", answer: "Quito", options: ["Quito", "Guayaquil", "Cuenca", "Manta"] },
  { question: "Capital of Paraguay?", answer: "Asuncion", options: ["Asuncion", "Ciudad del Este", "Encarnacion", "Pedro Juan"] },
  { question: "Capital of Uruguay?", answer: "Montevideo", options: ["Montevideo", "Salto", "Paysandu", "Rivera"] },
  { question: "Capital of Guyana?", answer: "Georgetown", options: ["Georgetown", "Linden", "New Amsterdam", "Bartica"] },
  { question: "Capital of Panama?", answer: "Panama City", options: ["Panama City", "Colon", "David", "La Chorrera"] },
  { question: "Capital of Costa Rica?", answer: "San Jose", options: ["San Jose", "Alajuela", "Cartago", "Limon"] },
  { question: "Capital of Nicaragua?", answer: "Managua", options: ["Managua", "Leon", "Granada", "Masaya"] },
  { question: "Capital of Honduras?", answer: "Tegucigalpa", options: ["Tegucigalpa", "San Pedro Sula", "La Ceiba", "Choloma"] },
  { question: "Capital of El Salvador?", answer: "San Salvador", options: ["San Salvador", "Santa Ana", "San Miguel", "Soyapango"] },
  { question: "Capital of Guatemala?", answer: "Guatemala City", options: ["Guatemala City", "Quetzaltenango", "Escuintla", "Mixco"] },
  { question: "Capital of Belize?", answer: "Belmopan", options: ["Belmopan", "Belize City", "San Ignacio", "Orange Walk"] },
  { question: "Capital of Jamaica?", answer: "Kingston", options: ["Kingston", "Montego Bay", "Spanish Town", "Portmore"] },
  { question: "Capital of Haiti?", answer: "Port-au-Prince", options: ["Port-au-Prince", "Cap-Haitien", "Gonaives", "Les Cayes"] },
  { question: "Capital of Dominican Republic?", answer: "Santo Domingo", options: ["Santo Domingo", "Santiago", "La Romana", "San Cristobal"] },
  { question: "Capital of Bahamas?", answer: "Nassau", options: ["Nassau", "Freeport", "West End", "Marsh Harbour"] },
  { question: "Capital of Trinidad and Tobago?", answer: "Port of Spain", options: ["Port of Spain", "San Fernando", "Arima", "Scarborough"] },
  { question: "Capital of Ukraine's neighbour Belarus?", answer: "Minsk", options: ["Minsk", "Gomel", "Vitebsk", "Mogilev"] },
  { question: "Capital of Serbia?", answer: "Belgrade", options: ["Belgrade", "Novi Sad", "Nis", "Kragujevac"] },
  { question: "Capital of Croatia?", answer: "Zagreb", options: ["Zagreb", "Split", "Rijeka", "Osijek"] },
  { question: "Capital of Bulgaria?", answer: "Sofia", options: ["Sofia", "Plovdiv", "Varna", "Burgas"] },
  { question: "Capital of Slovakia?", answer: "Bratislava", options: ["Bratislava", "Kosice", "Presov", "Zilina"] },
  { question: "Capital of Slovenia?", answer: "Ljubljana", options: ["Ljubljana", "Maribor", "Celje", "Kranj"] },
  { question: "Capital of Iceland?", answer: "Reykjavik", options: ["Reykjavik", "Akureyri", "Kopavogur", "Hafnarfjordur"] },
  { question: "Capital of Luxembourg?", answer: "Luxembourg City", options: ["Luxembourg City", "Esch-sur-Alzette", "Differdange", "Dudelange"] },
  { question: "Capital of Malta?", answer: "Valletta", options: ["Valletta", "Birkirkara", "Mosta", "Qormi"] },
  { question: "Capital of Cyprus?", answer: "Nicosia", options: ["Nicosia", "Limassol", "Larnaca", "Paphos"] },
  { question: "Capital of Estonia?", answer: "Tallinn", options: ["Tallinn", "Tartu", "Narva", "Parnu"] },
  { question: "Capital of Latvia?", answer: "Riga", options: ["Riga", "Daugavpils", "Liepaja", "Jelgava"] },
  { question: "Capital of Lithuania?", answer: "Vilnius", options: ["Vilnius", "Kaunas", "Klaipeda", "Siauliai"] },
  { question: "Capital of Albania?", answer: "Tirana", options: ["Tirana", "Durres", "Vlore", "Shkoder"] },
  { question: "Capital of Bosnia and Herzegovina?", answer: "Sarajevo", options: ["Sarajevo", "Banja Luka", "Tuzla", "Mostar"] },
  { question: "Capital of North Macedonia?", answer: "Skopje", options: ["Skopje", "Bitola", "Kumanovo", "Prilep"] },
  { question: "Capital of Montenegro?", answer: "Podgorica", options: ["Podgorica", "Niksic", "Herceg Novi", "Budva"] },
  { question: "Capital of Moldova?", answer: "Chisinau", options: ["Chisinau", "Tiraspol", "Balti", "Bender"] },
  { question: "Capital of Georgia?", answer: "Tbilisi", options: ["Tbilisi", "Batumi", "Kutaisi", "Rustavi"] },
  { question: "Capital of Armenia?", answer: "Yerevan", options: ["Yerevan", "Gyumri", "Vanadzor", "Vagharshapat"] },
  { question: "Capital of Azerbaijan?", answer: "Baku", options: ["Baku", "Ganja", "Sumqayit", "Mingachevir"] },
  { question: "Capital of Kyrgyzstan?", answer: "Bishkek", options: ["Bishkek", "Osh", "Jalal-Abad", "Karakol"] },
  { question: "Capital of Tajikistan?", answer: "Dushanbe", options: ["Dushanbe", "Khujand", "Kulob", "Bokhtar"] },
  { question: "Capital of Turkmenistan?", answer: "Ashgabat", options: ["Ashgabat", "Turkmenabat", "Dashoguz", "Mary"] },
  { question: "Capital of Yemen?", answer: "Sanaa", options: ["Sanaa", "Aden", "Taiz", "Hodeidah"] },
  { question: "Capital of East Timor?", answer: "Dili", options: ["Dili", "Baucau", "Maliana", "Suai"] },
  { question: "Capital of Brunei?", answer: "Bandar Seri Begawan", options: ["Bandar Seri Begawan", "Kuala Belait", "Seria", "Tutong"] },
  { question: "Capital of Papua New Guinea?", answer: "Port Moresby", options: ["Port Moresby", "Lae", "Mount Hagen", "Madang"] },
  { question: "Capital of Samoa?", answer: "Apia", options: ["Apia", "Salelologa", "Asau", "Mulifanua"] },
  { question: "Capital of Tonga?", answer: "Nuku'alofa", options: ["Nuku'alofa", "Neiafu", "Haveluloto", "Vaini"] },
  { question: "Capital of Kazakhstan's neighbour Uzbekistan?", answer: "Tashkent", options: ["Tashkent", "Samarkand", "Bukhara", "Namangan"] },
  { question: "Capital of Mongolia?", answer: "Ulaanbaatar", options: ["Ulaanbaatar", "Erdenet", "Darkhan", "Choibalsan"] },
  { question: "Capital of Vatican City?", answer: "Vatican City", options: ["Vatican City", "Rome", "Naples", "Florence"] },
  { question: "Capital of San Marino?", answer: "San Marino", options: ["San Marino", "Serravalle", "Borgo Maggiore", "Domagnano"] },
  { question: "Capital of Monaco?", answer: "Monaco", options: ["Monaco", "Monte Carlo", "La Condamine", "Fontvieille"] },
  { question: "Capital of Liechtenstein?", answer: "Vaduz", options: ["Vaduz", "Schaan", "Balzers", "Triesen"] },
  { question: "Capital of Andorra?", answer: "Andorra la Vella", options: ["Andorra la Vella", "Escaldes", "Encamp", "Sant Julia"] },
  { question: "Capital of North Korea?", answer: "Pyongyang", options: ["Pyongyang", "Hamhung", "Chongjin", "Nampo"] },
  { question: "Capital of Sikkim (India)?", answer: "Gangtok", options: ["Gangtok", "Namchi", "Gyalshing", "Mangan"] },
  { question: "Capital of Tripura (India)?", answer: "Agartala", options: ["Agartala", "Udaipur", "Dharmanagar", "Kailashahar"] },
  { question: "Capital of Manipur (India)?", answer: "Imphal", options: ["Imphal", "Churachandpur", "Thoubal", "Bishnupur"] },
  { question: "Capital of Meghalaya (India)?", answer: "Shillong", options: ["Shillong", "Tura", "Jowai", "Nongstoin"] },
  { question: "Capital of Mizoram (India)?", answer: "Aizawl", options: ["Aizawl", "Lunglei", "Champhai", "Serchhip"] },
  { question: "Capital of Nagaland (India)?", answer: "Kohima", options: ["Kohima", "Dimapur", "Mokokchung", "Tuensang"] },




]);
