/* ============================================================
   🏛️  CAPITALS — Class 1
   ------------------------------------------------------------
   HOW TO EDIT THIS FILE
   • Each { ... } line below is ONE question.
   • Keep this exact shape:
       { question: "your question?", answer: "Correct", options: ["Correct","B","C","D"] }
   • RULES:
       - Give exactly 4 options.
       - The "answer" text must EXACTLY match one of the 4 options.
       - Wrap text in "double quotes". If your text has a " inside it,
         write it as \" (a backslash then a quote).
   • Add or delete question lines freely.
   • Save the file, then refresh the quiz page — changes appear instantly.
   ============================================================ */
registerQuiz("capitals", 1, [
  { question: "Capital of India?", answer: "New Delhi", options: ["New Delhi", "Mumbai", "Kolkata", "Chennai"] },
  { question: "Capital of Maharashtra?", answer: "Mumbai", options: ["Mumbai", "Pune", "Nagpur", "Nashik"] },
  { question: "Capital of Tamil Nadu?", answer: "Chennai", options: ["Chennai", "Madurai", "Salem", "Coimbatore"] },
  { question: "Capital of West Bengal?", answer: "Kolkata", options: ["Kolkata", "Howrah", "Asansol", "Siliguri"] },
  { question: "Capital of Karnataka?", answer: "Bengaluru", options: ["Bengaluru", "Mysuru", "Mangaluru", "Hubli"] },
  { question: "Capital of Rajasthan?", answer: "Jaipur", options: ["Jaipur", "Jodhpur", "Udaipur", "Kota"] },
  { question: "Capital of UP?", answer: "Lucknow", options: ["Lucknow", "Kanpur", "Agra", "Varanasi"] },
  { question: "Capital of Bihar?", answer: "Patna", options: ["Patna", "Gaya", "Bhagalpur", "Muzaffarpur"] },
  { question: "Capital of Gujarat?", answer: "Gandhinagar", options: ["Gandhinagar", "Ahmedabad", "Surat", "Vadodara"] },
  { question: "Capital of Punjab?", answer: "Chandigarh", options: ["Chandigarh", "Amritsar", "Ludhiana", "Patiala"] },
  { question: "Capital of MP?", answer: "Bhopal", options: ["Bhopal", "Indore", "Gwalior", "Jabalpur"] },
  { question: "Capital of Kerala?", answer: "Thiruvananthapuram", options: ["Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur"] },
  { question: "Capital of Andhra Pradesh?", answer: "Amaravati", options: ["Amaravati", "Hyderabad", "Vijayawada", "Tirupati"] },
  { question: "Capital of Telangana?", answer: "Hyderabad", options: ["Hyderabad", "Warangal", "Karimnagar", "Nizamabad"] },
  { question: "Capital of Odisha?", answer: "Bhubaneswar", options: ["Bhubaneswar", "Cuttack", "Puri", "Rourkela"] },
  { question: "Capital of Assam?", answer: "Dispur", options: ["Dispur", "Guwahati", "Silchar", "Jorhat"] },
  { question: "Capital of Haryana?", answer: "Chandigarh", options: ["Chandigarh", "Faridabad", "Gurgaon", "Hisar"] },
  { question: "Capital of Goa?", answer: "Panaji", options: ["Panaji", "Margao", "Vasco", "Mapusa"] },
  { question: "Capital of Uttarakhand?", answer: "Dehradun", options: ["Dehradun", "Haridwar", "Nainital", "Mussoorie"] },
  { question: "Capital of HP?", answer: "Shimla", options: ["Shimla", "Manali", "Dharamshala", "Solan"] },
  { question: "Capital of Jammu and Kashmir?", answer: "Srinagar", options: ["Srinagar", "Jammu", "Leh", "Ladakh"] },
  { question: "Capital of Ladakh?", answer: "Leh", options: ["Leh", "Srinagar", "Kargil", "Jammu"] },
  { question: "Capital of Puducherry?", answer: "Puducherry", options: ["Puducherry", "Karaikal", "Mahe", "Yanam"] },
  { question: "Capital of Andaman and Nicobar Islands?", answer: "Port Blair", options: ["Port Blair", "Kavaratti", "Diglipur", "Havelock"] },
  { question: "Capital of Lakshadweep?", answer: "Kavaratti", options: ["Kavaratti", "Port Blair", "Agatti", "Minicoy"] },
  { question: "Capital of Chandigarh (UT)?", answer: "Chandigarh", options: ["Chandigarh", "Panchkula", "Mohali", "Zirakpur"] },
  { question: "Capital of USA?", answer: "Washington D.C.", options: ["Washington D.C.", "New York", "Los Angeles", "Chicago"] },
  { question: "Capital of United Kingdom?", answer: "London", options: ["London", "Manchester", "Liverpool", "Birmingham"] },
  { question: "Capital of France?", answer: "Paris", options: ["Paris", "Lyon", "Marseille", "Nice"] },
  { question: "Capital of Japan?", answer: "Tokyo", options: ["Tokyo", "Osaka", "Kyoto", "Nagoya"] },
  { question: "Capital of China?", answer: "Beijing", options: ["Beijing", "Shanghai", "Guangzhou", "Hong Kong"] },
  { question: "Capital of Russia?", answer: "Moscow", options: ["Moscow", "St. Petersburg", "Novosibirsk", "Kazan"] },
  { question: "Capital of Germany?", answer: "Berlin", options: ["Berlin", "Munich", "Hamburg", "Frankfurt"] },
  { question: "Capital of Italy?", answer: "Rome", options: ["Rome", "Milan", "Naples", "Venice"] },
  { question: "Capital of Spain?", answer: "Madrid", options: ["Madrid", "Barcelona", "Valencia", "Seville"] },
  { question: "Capital of Australia?", answer: "Canberra", options: ["Canberra", "Sydney", "Melbourne", "Perth"] },
  { question: "Capital of Canada?", answer: "Ottawa", options: ["Ottawa", "Toronto", "Vancouver", "Montreal"] },
  { question: "Capital of Brazil?", answer: "Brasilia", options: ["Brasilia", "Rio de Janeiro", "Sao Paulo", "Salvador"] },
  { question: "Capital of Egypt?", answer: "Cairo", options: ["Cairo", "Alexandria", "Giza", "Luxor"] },
  { question: "Capital of South Africa?", answer: "Pretoria", options: ["Pretoria", "Cape Town", "Johannesburg", "Durban"] },
  { question: "Capital of Mexico?", answer: "Mexico City", options: ["Mexico City", "Cancun", "Guadalajara", "Monterrey"] },
  { question: "Capital of South Korea?", answer: "Seoul", options: ["Seoul", "Busan", "Incheon", "Daegu"] },
  { question: "Capital of Indonesia?", answer: "Jakarta", options: ["Jakarta", "Bali", "Surabaya", "Bandung"] },
  { question: "Capital of Nepal?", answer: "Kathmandu", options: ["Kathmandu", "Pokhara", "Lalitpur", "Biratnagar"] },
  { question: "Capital of Sri Lanka?", answer: "Colombo", options: ["Colombo", "Kandy", "Galle", "Jaffna"] },
  { question: "Capital of Bangladesh?", answer: "Dhaka", options: ["Dhaka", "Chittagong", "Khulna", "Sylhet"] },
  { question: "Capital of Pakistan?", answer: "Islamabad", options: ["Islamabad", "Karachi", "Lahore", "Peshawar"] },
  { question: "Capital of Bhutan?", answer: "Thimphu", options: ["Thimphu", "Paro", "Punakha", "Phuentsholing"] },
  { question: "Capital of Afghanistan?", answer: "Kabul", options: ["Kabul", "Kandahar", "Herat", "Mazar-i-Sharif"] },
  { question: "Capital of Myanmar?", answer: "Naypyidaw", options: ["Naypyidaw", "Yangon", "Mandalay", "Bago"] },
  { question: "Capital of Maldives?", answer: "Male", options: ["Male", "Addu City", "Fuvahmulah", "Hulhumale"] },
  { question: "Capital of New Zealand?", answer: "Wellington", options: ["Wellington", "Auckland", "Christchurch", "Hamilton"] },
  { question: "Capital of Switzerland?", answer: "Bern", options: ["Bern", "Zurich", "Geneva", "Basel"] },
  { question: "Capital of Netherlands?", answer: "Amsterdam", options: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht"] },
  { question: "Capital of Greece?", answer: "Athens", options: ["Athens", "Thessaloniki", "Patras", "Sparta"] },
  { question: "Capital of Turkey?", answer: "Ankara", options: ["Ankara", "Istanbul", "Izmir", "Antalya"] },
  { question: "Capital of Thailand?", answer: "Bangkok", options: ["Bangkok", "Phuket", "Chiang Mai", "Pattaya"] },
  { question: "Capital of Singapore?", answer: "Singapore", options: ["Singapore", "Jurong", "Woodlands", "Sentosa"] },
  { question: "Capital of Malaysia?", answer: "Kuala Lumpur", options: ["Kuala Lumpur", "Penang", "Johor Bahru", "Malacca"] },
  { question: "Capital of Vietnam?", answer: "Hanoi", options: ["Hanoi", "Ho Chi Minh City", "Da Nang", "Hue"] },
  { question: "Capital of Argentina?", answer: "Buenos Aires", options: ["Buenos Aires", "Cordoba", "Rosario", "Mendoza"] },
  { question: "Capital of Saudi Arabia?", answer: "Riyadh", options: ["Riyadh", "Jeddah", "Mecca", "Medina"] },
  { question: "Capital of UAE?", answer: "Abu Dhabi", options: ["Abu Dhabi", "Dubai", "Sharjah", "Ajman"] },
  { question: "Capital of Iran?", answer: "Tehran", options: ["Tehran", "Isfahan", "Shiraz", "Mashhad"] },
  { question: "Capital of Iraq?", answer: "Baghdad", options: ["Baghdad", "Basra", "Mosul", "Erbil"] },
  { question: "Capital of Israel?", answer: "Jerusalem", options: ["Jerusalem", "Tel Aviv", "Haifa", "Eilat"] },
  { question: "Capital of Kenya?", answer: "Nairobi", options: ["Nairobi", "Mombasa", "Kisumu", "Nakuru"] },
  { question: "Capital of Nigeria?", answer: "Abuja", options: ["Abuja", "Lagos", "Kano", "Ibadan"] },
  { question: "Capital of Sweden?", answer: "Stockholm", options: ["Stockholm", "Gothenburg", "Malmo", "Uppsala"] },
  { question: "Capital of Norway?", answer: "Oslo", options: ["Oslo", "Bergen", "Trondheim", "Stavanger"] },
  { question: "Capital of Denmark?", answer: "Copenhagen", options: ["Copenhagen", "Aarhus", "Odense", "Aalborg"] },
  { question: "Capital of Finland?", answer: "Helsinki", options: ["Helsinki", "Espoo", "Tampere", "Turku"] },
  { question: "Capital of Poland?", answer: "Warsaw", options: ["Warsaw", "Krakow", "Lodz", "Gdansk"] },
  { question: "Capital of Austria?", answer: "Vienna", options: ["Vienna", "Graz", "Linz", "Salzburg"] },
  { question: "Capital of Portugal?", answer: "Lisbon", options: ["Lisbon", "Porto", "Braga", "Coimbra"] },
  { question: "Capital of Ireland?", answer: "Dublin", options: ["Dublin", "Cork", "Galway", "Limerick"] },
  { question: "Capital of Belgium?", answer: "Brussels", options: ["Brussels", "Antwerp", "Ghent", "Bruges"] },
  { question: "Capital of Cuba?", answer: "Havana", options: ["Havana", "Santiago de Cuba", "Camaguey", "Holguin"] },
  { question: "Capital of Chile?", answer: "Santiago", options: ["Santiago", "Valparaiso", "Concepcion", "Antofagasta"] },
  { question: "Capital of Peru?", answer: "Lima", options: ["Lima", "Cusco", "Arequipa", "Trujillo"] },
  { question: "Capital of Colombia?", answer: "Bogota", options: ["Bogota", "Medellin", "Cali", "Cartagena"] },
  { question: "Capital of Philippines?", answer: "Manila", options: ["Manila", "Cebu City", "Davao City", "Quezon City"] },
  { question: "Capital of Ukraine?", answer: "Kyiv", options: ["Kyiv", "Kharkiv", "Odesa", "Lviv"] },
  { question: "Capital of Poland's neighbour Czech Republic?", answer: "Prague", options: ["Prague", "Brno", "Ostrava", "Plzen"] },
  { question: "Capital of Hungary?", answer: "Budapest", options: ["Budapest", "Debrecen", "Szeged", "Miskolc"] },
  { question: "Capital of Cambodia?", answer: "Phnom Penh", options: ["Phnom Penh", "Siem Reap", "Battambang", "Sihanoukville"] },
  { question: "Capital of Laos?", answer: "Vientiane", options: ["Vientiane", "Luang Prabang", "Pakse", "Savannakhet"] },
  { question: "Capital of Qatar?", answer: "Doha", options: ["Doha", "Al Wakrah", "Al Rayyan", "Lusail"] },
  { question: "Capital of Kuwait?", answer: "Kuwait City", options: ["Kuwait City", "Al Ahmadi", "Hawalli", "Jahra"] },
  { question: "Capital of Oman?", answer: "Muscat", options: ["Muscat", "Salalah", "Sohar", "Nizwa"] },
  { question: "Capital of Bahrain?", answer: "Manama", options: ["Manama", "Muharraq", "Riffa", "Isa Town"] },
  { question: "Capital of Jordan?", answer: "Amman", options: ["Amman", "Zarqa", "Irbid", "Aqaba"] },
  { question: "Capital of Lebanon?", answer: "Beirut", options: ["Beirut", "Tripoli", "Sidon", "Tyre"] },
  { question: "Capital of Syria?", answer: "Damascus", options: ["Damascus", "Aleppo", "Homs", "Latakia"] },
  { question: "Capital of Ghana?", answer: "Accra", options: ["Accra", "Kumasi", "Tamale", "Takoradi"] },
  { question: "Capital of Ethiopia?", answer: "Addis Ababa", options: ["Addis Ababa", "Gondar", "Mekelle", "Bahir Dar"] },
  { question: "Capital of Tanzania?", answer: "Dodoma", options: ["Dodoma", "Dar es Salaam", "Zanzibar City", "Arusha"] },
  { question: "Capital of Morocco?", answer: "Rabat", options: ["Rabat", "Casablanca", "Marrakesh", "Fez"] },
  { question: "Capital of Fiji?", answer: "Suva", options: ["Suva", "Nadi", "Lautoka", "Labasa"] },




]);
