/* ============================================================
   🏛️  CAPITALS — Class 4
   ------------------------------------------------------------
   HOW TO EDIT THIS FILE
   • Each { ... } line below is ONE question.
   • Keep this exact shape:
       { question: "your question?", answer: "Correct", options: ["Correct","B","C","D"] }
   • RULES:
       - Give exactly 4 options.
       - The "answer" text must EXACTLY match one of the 4 options.
       - Wrap text in "double quotes". If your text has a " inside it,
         write it as \" (a backslash then a quote).
   • Add or delete question lines freely.
   • Save the file, then refresh the quiz page — changes appear instantly.
   ============================================================ */
registerQuiz("capitals", 4, [
  { question: "Capital of Brazil?", answer: "Brasilia", options: ["Brasilia", "Rio de Janeiro", "Sao Paulo", "Salvador"] },
  { question: "Capital of Argentina?", answer: "Buenos Aires", options: ["Buenos Aires", "Cordoba", "Rosario", "Mendoza"] },
  { question: "Capital of Mexico?", answer: "Mexico City", options: ["Mexico City", "Cancun", "Guadalajara", "Monterrey"] },
  { question: "Capital of Egypt?", answer: "Cairo", options: ["Cairo", "Alexandria", "Giza", "Luxor"] },
  { question: "Capital of South Africa?", answer: "Pretoria (admin)", options: ["Pretoria (admin)", "Cape Town", "Johannesburg", "Durban"] },
  { question: "Capital of Kenya?", answer: "Nairobi", options: ["Nairobi", "Mombasa", "Kisumu", "Nakuru"] },
  { question: "Capital of Nigeria?", answer: "Abuja", options: ["Abuja", "Lagos", "Kano", "Ibadan"] },
  { question: "Capital of Ethiopia?", answer: "Addis Ababa", options: ["Addis Ababa", "Dire Dawa", "Mekelle", "Gondar"] },
  { question: "Capital of Greece?", answer: "Athens", options: ["Athens", "Thessaloniki", "Patras", "Larissa"] },
  { question: "Capital of Portugal?", answer: "Lisbon", options: ["Lisbon", "Porto", "Coimbra", "Braga"] },
  { question: "Capital of Netherlands?", answer: "Amsterdam", options: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht"] },
  { question: "Capital of Belgium?", answer: "Brussels", options: ["Brussels", "Antwerp", "Ghent", "Bruges"] },
  { question: "Capital of Switzerland?", answer: "Bern", options: ["Bern", "Zurich", "Geneva", "Basel"] },
  { question: "Capital of Sweden?", answer: "Stockholm", options: ["Stockholm", "Gothenburg", "Malmo", "Uppsala"] },
  { question: "Capital of Norway?", answer: "Oslo", options: ["Oslo", "Bergen", "Trondheim", "Stavanger"] },
  { question: "Capital of Denmark?", answer: "Copenhagen", options: ["Copenhagen", "Aarhus", "Odense", "Aalborg"] },
  { question: "Capital of Finland?", answer: "Helsinki", options: ["Helsinki", "Tampere", "Turku", "Espoo"] },
  { question: "Capital of Poland?", answer: "Warsaw", options: ["Warsaw", "Krakow", "Lodz", "Wroclaw"] },
  { question: "Capital of Austria?", answer: "Vienna", options: ["Vienna", "Salzburg", "Graz", "Linz"] },
  { question: "Capital of Ireland?", answer: "Dublin", options: ["Dublin", "Cork", "Galway", "Limerick"] },
  { question: "Capital of California (US state)?", answer: "Sacramento", options: ["Sacramento", "Los Angeles", "San Francisco", "San Diego"] },
  { question: "Capital of New York (US state)?", answer: "Albany", options: ["Albany", "New York City", "Buffalo", "Rochester"] },
  { question: "Capital of Texas (US state)?", answer: "Austin", options: ["Austin", "Houston", "Dallas", "San Antonio"] },
  { question: "Capital of Florida (US state)?", answer: "Tallahassee", options: ["Tallahassee", "Miami", "Orlando", "Tampa"] },
  { question: "Capital of Illinois (US state)?", answer: "Springfield", options: ["Springfield", "Chicago", "Peoria", "Rockford"] },
  { question: "Capital of Pennsylvania (US state)?", answer: "Harrisburg", options: ["Harrisburg", "Philadelphia", "Pittsburgh", "Allentown"] },
  { question: "Capital of Ohio (US state)?", answer: "Columbus", options: ["Columbus", "Cleveland", "Cincinnati", "Toledo"] },
  { question: "Capital of Georgia (US state)?", answer: "Atlanta", options: ["Atlanta", "Savannah", "Augusta", "Columbus"] },
  { question: "Capital of Alaska (US state)?", answer: "Juneau", options: ["Juneau", "Anchorage", "Fairbanks", "Sitka"] },
  { question: "Capital of Hawaii (US state)?", answer: "Honolulu", options: ["Honolulu", "Hilo", "Kailua", "Kaneohe"] },
  { question: "Capital of New South Wales (Australia)?", answer: "Sydney", options: ["Sydney", "Melbourne", "Brisbane", "Canberra"] },
  { question: "Capital of Queensland (Australia)?", answer: "Brisbane", options: ["Brisbane", "Cairns", "Gold Coast", "Townsville"] },
  { question: "Capital of Western Australia?", answer: "Perth", options: ["Perth", "Fremantle", "Bunbury", "Broome"] },
  { question: "Capital of South Australia?", answer: "Adelaide", options: ["Adelaide", "Whyalla", "Mount Gambier", "Gawler"] },
  { question: "Capital of Tasmania (Australia)?", answer: "Hobart", options: ["Hobart", "Launceston", "Devonport", "Burnie"] },
  { question: "Capital of Ontario (Canada)?", answer: "Toronto", options: ["Toronto", "Ottawa", "Hamilton", "London"] },
  { question: "Capital of Quebec (Canada)?", answer: "Quebec City", options: ["Quebec City", "Montreal", "Laval", "Gatineau"] },
  { question: "Capital of British Columbia (Canada)?", answer: "Victoria", options: ["Victoria", "Vancouver", "Surrey", "Kelowna"] },
  { question: "Capital of Bavaria (Germany)?", answer: "Munich", options: ["Munich", "Nuremberg", "Augsburg", "Regensburg"] },
  { question: "Capital of Catalonia (Spain)?", answer: "Barcelona", options: ["Barcelona", "Girona", "Tarragona", "Lleida"] },
  { question: "Capital of Tuscany (Italy)?", answer: "Florence", options: ["Florence", "Pisa", "Siena", "Livorno"] },
  { question: "Capital of Scotland (UK)?", answer: "Edinburgh", options: ["Edinburgh", "Glasgow", "Aberdeen", "Dundee"] },
  { question: "Capital of Wales (UK)?", answer: "Cardiff", options: ["Cardiff", "Swansea", "Newport", "Wrexham"] },
  { question: "Capital of Northern Ireland (UK)?", answer: "Belfast", options: ["Belfast", "Derry", "Lisburn", "Newry"] },
  { question: "Capital of England (UK)?", answer: "London", options: ["London", "Birmingham", "Manchester", "Leeds"] },
  { question: "Capital of Sao Paulo (Brazil state)?", answer: "Sao Paulo", options: ["Sao Paulo", "Campinas", "Santos", "Sorocaba"] },
  { question: "Capital of Buenos Aires Province (Argentina)?", answer: "La Plata", options: ["La Plata", "Buenos Aires City", "Mar del Plata", "Bahia Blanca"] },
  { question: "Capital of Western Cape (South Africa)?", answer: "Cape Town", options: ["Cape Town", "Stellenbosch", "George", "Paarl"] },
  { question: "Capital of Gauteng (South Africa)?", answer: "Johannesburg", options: ["Johannesburg", "Pretoria", "Soweto", "Vereeniging"] },
  { question: "Capital of Punjab (Pakistan)?", answer: "Lahore", options: ["Lahore", "Multan", "Faisalabad", "Rawalpindi"] },
  { question: "Capital of Sindh (Pakistan)?", answer: "Karachi", options: ["Karachi", "Hyderabad (Pakistan)", "Sukkur", "Larkana"] },
  { question: "Capital of California's largest city?", answer: "Los Angeles", options: ["Los Angeles", "Sacramento", "San Diego", "San Jose"] },
  { question: "Which country's capital is Rabat?", answer: "Morocco", options: ["Morocco", "Algeria", "Tunisia", "Libya"] },
  { question: "Which country's capital is Tunis?", answer: "Tunisia", options: ["Tunisia", "Morocco", "Libya", "Algeria"] },
  { question: "Which country's capital is Algiers?", answer: "Algeria", options: ["Algeria", "Tunisia", "Morocco", "Libya"] },
  { question: "Which country's capital is Tripoli?", answer: "Libya", options: ["Libya", "Lebanon", "Tunisia", "Algeria"] },
  { question: "Which country's capital is Accra?", answer: "Ghana", options: ["Ghana", "Nigeria", "Senegal", "Ivory Coast"] },
  { question: "Which country's capital is Dakar?", answer: "Senegal", options: ["Senegal", "Mali", "Ghana", "Guinea"] },
  { question: "Which country's capital is Kampala?", answer: "Uganda", options: ["Uganda", "Kenya", "Tanzania", "Rwanda"] },
  { question: "Which country's capital is Kigali?", answer: "Rwanda", options: ["Rwanda", "Burundi", "Uganda", "Congo"] },
  { question: "Which country's capital is Lusaka?", answer: "Zambia", options: ["Zambia", "Zimbabwe", "Malawi", "Mozambique"] },
  { question: "Which country's capital is Harare?", answer: "Zimbabwe", options: ["Zimbabwe", "Zambia", "Botswana", "Namibia"] },
  { question: "Which country's capital is Windhoek?", answer: "Namibia", options: ["Namibia", "Botswana", "Angola", "Zambia"] },
  { question: "Which country's capital is Gaborone?", answer: "Botswana", options: ["Botswana", "Namibia", "Zimbabwe", "South Africa"] },
  { question: "Which country's capital is Maputo?", answer: "Mozambique", options: ["Mozambique", "Zimbabwe", "Malawi", "Tanzania"] },
  { question: "Which country's capital is Luanda?", answer: "Angola", options: ["Angola", "Congo", "Namibia", "Zambia"] },
  { question: "Which country's capital is Addis Ababa?", answer: "Ethiopia", options: ["Ethiopia", "Eritrea", "Somalia", "Sudan"] },
  { question: "Which country's capital is Khartoum?", answer: "Sudan", options: ["Sudan", "Egypt", "Ethiopia", "Chad"] },
  { question: "Which country's capital is Yaounde?", answer: "Cameroon", options: ["Cameroon", "Nigeria", "Chad", "Gabon"] },
  { question: "Which country's capital is Libreville?", answer: "Gabon", options: ["Gabon", "Congo", "Cameroon", "Angola"] },
  { question: "Which country's capital is Brazzaville?", answer: "Republic of the Congo", options: ["Republic of the Congo", "DR Congo", "Gabon", "Angola"] },
  { question: "Which country's capital is Kinshasa?", answer: "DR Congo", options: ["DR Congo", "Republic of the Congo", "Angola", "Zambia"] },
  { question: "Which country's capital is Antananarivo?", answer: "Madagascar", options: ["Madagascar", "Mauritius", "Comoros", "Seychelles"] },
  { question: "Which country's capital is Port Louis?", answer: "Mauritius", options: ["Mauritius", "Madagascar", "Seychelles", "Comoros"] },
  { question: "Which country's capital is Victoria?", answer: "Seychelles", options: ["Seychelles", "Mauritius", "Madagascar", "Comoros"] },
  { question: "Which country's capital is Asuncion?", answer: "Paraguay", options: ["Paraguay", "Uruguay", "Bolivia", "Argentina"] },
  { question: "Which country's capital is Montevideo?", answer: "Uruguay", options: ["Uruguay", "Paraguay", "Argentina", "Chile"] },
  { question: "Which country's capital is Quito?", answer: "Ecuador", options: ["Ecuador", "Peru", "Colombia", "Bolivia"] },
  { question: "Which country's capital is La Paz / Sucre?", answer: "Bolivia", options: ["Bolivia", "Peru", "Ecuador", "Paraguay"] },
  { question: "Which country's capital is Caracas?", answer: "Venezuela", options: ["Venezuela", "Colombia", "Guyana", "Brazil"] },
  { question: "Which country's capital is Georgetown?", answer: "Guyana", options: ["Guyana", "Suriname", "Venezuela", "Brazil"] },
  { question: "Which country's capital is Paramaribo?", answer: "Suriname", options: ["Suriname", "Guyana", "Venezuela", "French Guiana"] },
  { question: "Which country's capital is Panama City?", answer: "Panama", options: ["Panama", "Costa Rica", "Colombia", "Nicaragua"] },
  { question: "Which country's capital is San Jose?", answer: "Costa Rica", options: ["Costa Rica", "Panama", "Nicaragua", "Honduras"] },
  { question: "Which country's capital is Managua?", answer: "Nicaragua", options: ["Nicaragua", "Honduras", "El Salvador", "Costa Rica"] },
  { question: "Which country's capital is Tegucigalpa?", answer: "Honduras", options: ["Honduras", "Nicaragua", "Guatemala", "El Salvador"] },
  { question: "Which country's capital is Guatemala City?", answer: "Guatemala", options: ["Guatemala", "Belize", "Honduras", "Mexico"] },
  { question: "Which country's capital is Havana?", answer: "Cuba", options: ["Cuba", "Jamaica", "Haiti", "Bahamas"] },
  { question: "Which country's capital is Kingston?", answer: "Jamaica", options: ["Jamaica", "Cuba", "Haiti", "Trinidad and Tobago"] },
  { question: "Which country's capital is Santo Domingo?", answer: "Dominican Republic", options: ["Dominican Republic", "Haiti", "Cuba", "Puerto Rico"] },
  { question: "Which country's capital is Nassau?", answer: "Bahamas", options: ["Bahamas", "Bermuda", "Cuba", "Jamaica"] },
  { question: "Which country's capital is Reykjavik?", answer: "Iceland", options: ["Iceland", "Norway", "Denmark", "Finland"] },
  { question: "Which country's capital is Copenhagen?", answer: "Denmark", options: ["Denmark", "Norway", "Sweden", "Iceland"] },
  { question: "Which country's capital is Stockholm?", answer: "Sweden", options: ["Sweden", "Norway", "Denmark", "Finland"] },
  { question: "Which country's capital is Oslo?", answer: "Norway", options: ["Norway", "Sweden", "Denmark", "Finland"] },
  { question: "Which country's capital is Helsinki?", answer: "Finland", options: ["Finland", "Sweden", "Norway", "Estonia"] },
  { question: "Which country's capital is Warsaw?", answer: "Poland", options: ["Poland", "Czech Republic", "Germany", "Slovakia"] },
  { question: "Which country's capital is Vienna?", answer: "Austria", options: ["Austria", "Germany", "Switzerland", "Hungary"] },

  { question: "Which country's capital is Lisbon?", answer: "Portugal", options: ["Portugal", "Spain", "Italy", "Greece"] },
  { question: "Which country's capital is Dublin?", answer: "Ireland", options: ["Ireland", "UK", "Iceland", "France"] },
  { question: "Which country's capital is Brussels?", answer: "Belgium", options: ["Belgium", "Netherlands", "France", "Luxembourg"] },
]);
