/* ============================================================
   🏛️  CAPITALS — Class 5
   ------------------------------------------------------------
   HOW TO EDIT THIS FILE
   • Each { ... } line below is ONE question.
   • Keep this exact shape:
       { question: "your question?", answer: "Correct", options: ["Correct","B","C","D"] }
   • RULES:
       - Give exactly 4 options.
       - The "answer" text must EXACTLY match one of the 4 options.
       - Wrap text in "double quotes". If your text has a " inside it,
         write it as \" (a backslash then a quote).
   • Add or delete question lines freely.
   • Save the file, then refresh the quiz page — changes appear instantly.
   ============================================================ */
registerQuiz("capitals", 5, [
  { question: "Capital of Kazakhstan?", answer: "Astana", options: ["Astana", "Almaty", "Shymkent", "Karaganda"] },
  { question: "Capital of Uzbekistan?", answer: "Tashkent", options: ["Tashkent", "Samarkand", "Bukhara", "Khiva"] },
  { question: "Capital of Mongolia?", answer: "Ulaanbaatar", options: ["Ulaanbaatar", "Erdenet", "Darkhan", "Khovd"] },
  { question: "Capital of New Zealand?", answer: "Wellington", options: ["Wellington", "Auckland", "Christchurch", "Dunedin"] },
  { question: "Capital of Israel (recognized by some)?", answer: "Jerusalem", options: ["Jerusalem", "Tel Aviv", "Haifa", "Eilat"] },
  { question: "Capital of Jordan?", answer: "Amman", options: ["Amman", "Petra", "Aqaba", "Irbid"] },
  { question: "Capital of Lebanon?", answer: "Beirut", options: ["Beirut", "Tripoli", "Sidon", "Tyre"] },
  { question: "Capital of Syria?", answer: "Damascus", options: ["Damascus", "Aleppo", "Homs", "Latakia"] },
  { question: "Capital of Cuba?", answer: "Havana", options: ["Havana", "Santiago", "Camaguey", "Holguin"] },
  { question: "Capital of Chile?", answer: "Santiago", options: ["Santiago", "Valparaiso", "Concepcion", "La Serena"] },
  { question: "Capital of Peru?", answer: "Lima", options: ["Lima", "Cusco", "Arequipa", "Trujillo"] },
  { question: "Capital of Colombia?", answer: "Bogota", options: ["Bogota", "Medellin", "Cali", "Cartagena"] },
  { question: "Capital of Venezuela?", answer: "Caracas", options: ["Caracas", "Maracaibo", "Valencia", "Barquisimeto"] },
  { question: "Capital of Morocco?", answer: "Rabat", options: ["Rabat", "Casablanca", "Marrakech", "Fez"] },
  { question: "Capital of Algeria?", answer: "Algiers", options: ["Algiers", "Oran", "Constantine", "Annaba"] },
  { question: "Capital of Tunisia?", answer: "Tunis", options: ["Tunis", "Sfax", "Sousse", "Kairouan"] },
  { question: "Capital of Czech Republic?", answer: "Prague", options: ["Prague", "Brno", "Ostrava", "Plzen"] },
  { question: "Capital of Hungary?", answer: "Budapest", options: ["Budapest", "Debrecen", "Szeged", "Miskolc"] },
  { question: "Capital of Romania?", answer: "Bucharest", options: ["Bucharest", "Cluj", "Iasi", "Timisoara"] },
  { question: "Capital of Vatican City?", answer: "Vatican City", options: ["Vatican City", "Rome", "Florence", "Milan"] },
  { question: "Capital of South Africa's three capital cities together (executive)?", answer: "Pretoria", options: ["Pretoria", "Cape Town", "Bloemfontein", "Johannesburg"] },
  { question: "Capital of Bolivia's constitutional capital (judicial)?", answer: "Sucre", options: ["Sucre", "La Paz", "Santa Cruz", "Cochabamba"] },
  { question: "Capital of Bolivia's seat of government (administrative)?", answer: "La Paz", options: ["La Paz", "Sucre", "Santa Cruz", "Cochabamba"] },
  { question: "Capital of Netherlands' seat of government (though Amsterdam is official capital)?", answer: "The Hague", options: ["The Hague", "Amsterdam", "Rotterdam", "Utrecht"] },
  { question: "Capital of Israel's capital as recognized by most of the world?", answer: "Jerusalem", options: ["Jerusalem", "Tel Aviv", "Haifa", "Eilat"] },
  { question: "Capital of Sri Lanka's administrative capital?", answer: "Sri Jayawardenepura Kotte", options: ["Sri Jayawardenepura Kotte", "Colombo", "Kandy", "Galle"] },
  { question: "Capital of Malaysia's administrative capital (federal government seat)?", answer: "Putrajaya", options: ["Putrajaya", "Kuala Lumpur", "Johor Bahru", "Penang"] },
  { question: "Capital of Ivory Coast's official capital (though Abidjan is largest)?", answer: "Yamoussoukro", options: ["Yamoussoukro", "Abidjan", "Bouake", "Daloa"] },
  { question: "Capital of Tanzania's official capital (though Dar es Salaam is bigger)?", answer: "Dodoma", options: ["Dodoma", "Dar es Salaam", "Zanzibar City", "Arusha"] },
  { question: "Capital of Nigeria's capital before Abuja?", answer: "Lagos", options: ["Lagos", "Abuja", "Kano", "Ibadan"] },
  { question: "Capital of Brazil's capital before Brasilia?", answer: "Rio de Janeiro", options: ["Rio de Janeiro", "Sao Paulo", "Salvador", "Brasilia"] },
  { question: "Capital of Pakistan's capital before Islamabad?", answer: "Karachi", options: ["Karachi", "Lahore", "Rawalpindi", "Peshawar"] },
  { question: "Capital of Turkey's capital before Ankara?", answer: "Istanbul", options: ["Istanbul", "Izmir", "Bursa", "Antalya"] },
  { question: "Capital of Australia's capital before Canberra?", answer: "Melbourne", options: ["Melbourne", "Sydney", "Adelaide", "Perth"] },
  { question: "Capital of Kazakhstan's former capital before Astana?", answer: "Almaty", options: ["Almaty", "Astana", "Shymkent", "Karaganda"] },
  { question: "Capital of Myanmar's capital before Naypyidaw?", answer: "Yangon", options: ["Yangon", "Mandalay", "Bago", "Taunggyi"] },
  { question: "Capital of Germany's capital before reunification (West Germany)?", answer: "Bonn", options: ["Bonn", "Berlin", "Munich", "Frankfurt"] },
  { question: "Capital of Russia's capital before Moscow (in Tsarist era)?", answer: "Saint Petersburg", options: ["Saint Petersburg", "Moscow", "Novgorod", "Kiev"] },
  { question: "Capital of USA's capital before Washington D.C.?", answer: "Philadelphia", options: ["Philadelphia", "New York City", "Boston", "Baltimore"] },
  { question: "Capital of China's capital during much of imperial history besides Beijing?", answer: "Nanjing", options: ["Nanjing", "Beijing", "Shanghai", "Xian"] },
  { question: "Capital of India's capital before it moved to New Delhi in 1911?", answer: "Calcutta", options: ["Calcutta", "Bombay", "Madras", "Delhi"] },
  { question: "Capital of Egypt's capital in ancient times (New Kingdom)?", answer: "Thebes", options: ["Thebes", "Cairo", "Memphis", "Alexandria"] },
  { question: "Which two cities does Rajasthan share fame for forts, besides Jaipur?", answer: "Jodhpur", options: ["Jodhpur", "Bikaner", "Alwar", "Bharatpur"] },
  { question: "Country whose capital is Yaounde?", answer: "Cameroon", options: ["Cameroon", "Chad", "Nigeria", "Gabon"] },
  { question: "Country whose capital is N'Djamena?", answer: "Chad", options: ["Chad", "Niger", "Sudan", "Cameroon"] },
  { question: "Country whose capital is Niamey?", answer: "Niger", options: ["Niger", "Nigeria", "Mali", "Chad"] },
  { question: "Country whose capital is Bamako?", answer: "Mali", options: ["Mali", "Niger", "Senegal", "Guinea"] },
  { question: "Country whose capital is Conakry?", answer: "Guinea", options: ["Guinea", "Guinea-Bissau", "Sierra Leone", "Liberia"] },
  { question: "Country whose capital is Freetown?", answer: "Sierra Leone", options: ["Sierra Leone", "Liberia", "Guinea", "Ghana"] },
  { question: "Country whose capital is Monrovia?", answer: "Liberia", options: ["Liberia", "Sierra Leone", "Ivory Coast", "Guinea"] },
  { question: "Country whose capital is Lome?", answer: "Togo", options: ["Togo", "Benin", "Ghana", "Nigeria"] },
  { question: "Country whose capital is Porto-Novo?", answer: "Benin", options: ["Benin", "Togo", "Nigeria", "Niger"] },
  { question: "Country whose capital is Nouakchott?", answer: "Mauritania", options: ["Mauritania", "Mali", "Senegal", "Morocco"] },
  { question: "Country whose capital is Bissau?", answer: "Guinea-Bissau", options: ["Guinea-Bissau", "Guinea", "Senegal", "Gambia"] },
  { question: "Country whose capital is Banjul?", answer: "The Gambia", options: ["The Gambia", "Senegal", "Guinea-Bissau", "Mauritania"] },
  { question: "Country whose capital is Praia?", answer: "Cape Verde", options: ["Cape Verde", "Sao Tome and Principe", "Guinea-Bissau", "Senegal"] },
  { question: "Country whose capital is Sao Tome?", answer: "Sao Tome and Principe", options: ["Sao Tome and Principe", "Cape Verde", "Equatorial Guinea", "Gabon"] },
  { question: "Country whose capital is Malabo?", answer: "Equatorial Guinea", options: ["Equatorial Guinea", "Gabon", "Cameroon", "Congo"] },
  { question: "Country whose capital is Bujumbura?", answer: "Burundi", options: ["Burundi", "Rwanda", "Tanzania", "DR Congo"] },
  { question: "Country whose capital is Asmara?", answer: "Eritrea", options: ["Eritrea", "Ethiopia", "Djibouti", "Sudan"] },
  { question: "Country whose capital is Djibouti?", answer: "Djibouti", options: ["Djibouti", "Eritrea", "Somalia", "Ethiopia"] },
  { question: "Country whose capital is Juba?", answer: "South Sudan", options: ["South Sudan", "Sudan", "Uganda", "Kenya"] },
  { question: "Country whose capital is Lilongwe?", answer: "Malawi", options: ["Malawi", "Zambia", "Mozambique", "Tanzania"] },
  { question: "Country whose capital is Bishkek?", answer: "Kyrgyzstan", options: ["Kyrgyzstan", "Tajikistan", "Uzbekistan", "Kazakhstan"] },
  { question: "Country whose capital is Dushanbe?", answer: "Tajikistan", options: ["Tajikistan", "Kyrgyzstan", "Turkmenistan", "Uzbekistan"] },
  { question: "Country whose capital is Ashgabat?", answer: "Turkmenistan", options: ["Turkmenistan", "Uzbekistan", "Tajikistan", "Iran"] },
  { question: "Country whose capital is Tashkent?", answer: "Uzbekistan", options: ["Uzbekistan", "Kazakhstan", "Turkmenistan", "Kyrgyzstan"] },
  { question: "Country whose capital is Ulaanbaatar?", answer: "Mongolia", options: ["Mongolia", "Kazakhstan", "Russia", "China"] },
  { question: "Country whose capital is Astana?", answer: "Kazakhstan", options: ["Kazakhstan", "Uzbekistan", "Mongolia", "Kyrgyzstan"] },
  { question: "Country whose capital is Yerevan?", answer: "Armenia", options: ["Armenia", "Georgia", "Azerbaijan", "Turkey"] },
  { question: "Country whose capital is Tbilisi?", answer: "Georgia", options: ["Georgia", "Armenia", "Azerbaijan", "Russia"] },
  { question: "Country whose capital is Baku?", answer: "Azerbaijan", options: ["Azerbaijan", "Armenia", "Georgia", "Turkmenistan"] },
  { question: "Country whose capital is Chisinau?", answer: "Moldova", options: ["Moldova", "Romania", "Ukraine", "Belarus"] },
  { question: "Country whose capital is Podgorica?", answer: "Montenegro", options: ["Montenegro", "Serbia", "Bosnia and Herzegovina", "Albania"] },
  { question: "Country whose capital is Skopje?", answer: "North Macedonia", options: ["North Macedonia", "Albania", "Bulgaria", "Serbia"] },
  { question: "Country whose capital is Sarajevo?", answer: "Bosnia and Herzegovina", options: ["Bosnia and Herzegovina", "Croatia", "Serbia", "Montenegro"] },
  { question: "Country whose capital is Tirana?", answer: "Albania", options: ["Albania", "North Macedonia", "Montenegro", "Kosovo"] },
  { question: "Country whose capital is Pristina?", answer: "Kosovo", options: ["Kosovo", "Albania", "Serbia", "Montenegro"] },
  { question: "Country whose capital is Vilnius?", answer: "Lithuania", options: ["Lithuania", "Latvia", "Estonia", "Poland"] },
  { question: "Country whose capital is Riga?", answer: "Latvia", options: ["Latvia", "Lithuania", "Estonia", "Belarus"] },
  { question: "Country whose capital is Tallinn?", answer: "Estonia", options: ["Estonia", "Latvia", "Lithuania", "Finland"] },
  { question: "Country whose capital is Bratislava?", answer: "Slovakia", options: ["Slovakia", "Czech Republic", "Hungary", "Austria"] },
  { question: "Country whose capital is Ljubljana?", answer: "Slovenia", options: ["Slovenia", "Croatia", "Austria", "Hungary"] },
  { question: "Country whose capital is Zagreb?", answer: "Croatia", options: ["Croatia", "Slovenia", "Bosnia and Herzegovina", "Serbia"] },
  { question: "Country whose capital is Belgrade?", answer: "Serbia", options: ["Serbia", "Croatia", "Bosnia and Herzegovina", "Montenegro"] },
  { question: "Country whose capital is Bucharest?", answer: "Romania", options: ["Romania", "Bulgaria", "Hungary", "Moldova"] },
  { question: "Country whose capital is Sofia?", answer: "Bulgaria", options: ["Bulgaria", "Romania", "Serbia", "North Macedonia"] },
  { question: "Country whose capital is Budapest?", answer: "Hungary", options: ["Hungary", "Austria", "Slovakia", "Romania"] },
  { question: "Country whose capital is Bandar Seri Begawan?", answer: "Brunei", options: ["Brunei", "Malaysia", "Indonesia", "Philippines"] },
  { question: "Country whose capital is Dili?", answer: "East Timor", options: ["East Timor", "Indonesia", "Philippines", "Papua New Guinea"] },
  { question: "Country whose capital is Port Moresby?", answer: "Papua New Guinea", options: ["Papua New Guinea", "Fiji", "Solomon Islands", "Vanuatu"] },
  { question: "Country whose capital is Honiara?", answer: "Solomon Islands", options: ["Solomon Islands", "Vanuatu", "Fiji", "Papua New Guinea"] },
  { question: "Country whose capital is Port Vila?", answer: "Vanuatu", options: ["Vanuatu", "Solomon Islands", "Fiji", "Samoa"] },
  { question: "Country whose capital is Suva?", answer: "Fiji", options: ["Fiji", "Vanuatu", "Tonga", "Samoa"] },
  { question: "Country whose capital is Apia?", answer: "Samoa", options: ["Samoa", "Tonga", "Fiji", "Vanuatu"] },
  { question: "Country whose capital is Nuku'alofa?", answer: "Tonga", options: ["Tonga", "Samoa", "Fiji", "Vanuatu"] },

  { question: "Country whose capital is Manama?", answer: "Bahrain", options: ["Bahrain", "Qatar", "Kuwait", "UAE"] },
  { question: "Country whose capital is Doha?", answer: "Qatar", options: ["Qatar", "Bahrain", "UAE", "Oman"] },
  { question: "Country whose capital is Muscat?", answer: "Oman", options: ["Oman", "Yemen", "UAE", "Qatar"] },
  { question: "Country whose capital is Sanaa?", answer: "Yemen", options: ["Yemen", "Oman", "Saudi Arabia", "Somalia"] },
  { question: "Country whose capital is Amman?", answer: "Jordan", options: ["Jordan", "Syria", "Lebanon", "Iraq"] },
]);
